### ISSUE TITLE
.tmp_update 3.54 patch

### ISSUE THREAD

**Issue by 7zxkv** [jimgraygit/Onion#100]
hi, I followed the readme procedure for patching 3.26 to 3.54. Subsequently I saw that the .tmp_update directory did not delete itself on the sdcard, I do not know if it was used and if the patch was applied correctly, it does not seem normal to me as a procedure. 

Can you confirm?

Moreover why the readme speaks about beta version and not the link on /releases? 

thx

**Comment by InertiAGruik** [comment]
I think that's why a lot of fonctions seems lacking on this update, just look a the last 4 or 5 posts, they are all about it.

**Comment by willbelr** [comment]
They advise to leave it there, see commit 506e6e32f5b2c2

**Comment by Sichroteph** [comment]
the .tmp_update is important to keep on your sd card, otherwise you will break things. This is normal.
