### ISSUE TITLE
Decrease in Arcade performance (3.06 > 3.54)

### ISSUE THREAD

**Issue by willbelr** [jimgraygit/Onion#102]
Following an update from v3.06 to v3.54 (not patched, full upgrade), the performance of some Arcade games is a lot worse. Dragon breed used to play fine, but after update it is slow with a lot of audio crackling. Revert to to v3.06 fixed it.

**Comment by srcamarda** [comment]
I noticed that in almost all emulators on this version. Enabling frame skip solved it for me.

**Comment by InertiAGruik** [comment]
3.55 il better for shinobi (s16) for example, on the 3.54 it was better than before but still some crackling music, now it's near perfect.
