### ISSUE TITLE
Feature Request: Make the Onion Installer a toggle

### ISSUE THREAD

**Issue by IllustratedMan-code** [jimgraygit/Onion#103]
It would be awesome if I could toggle systems on and off from the Installer. Right now, the Installer removes systems from the menu once they are installed. They can be removed manually but can't be reinstalled. 

Looking at the c file, it looked like it would be pretty simple. There just needs to be a check on the files in the Emu directory to create checkmarks in the menu. Some sort of removal method would also be needed.

I would make a pull request, but I'm not really sure how the project is built (or how friendly you are to pull requests). How are the releases created?

**Comment by Sichroteph** [comment]
done.
