### ISSUE TITLE
Grid filters should NOT be the default 

### ISSUE THREAD

**Issue by historymaker118** [jimgraygit/Onion#107]
Grid filters are extremely subjective and imo look absolutely awful at the best of times and significantly worse the smaller the screen is. Having this be the default option when the previous options were not an issue, is forcing (what I can only assume must be the majority of) people to have to go into the settings and spend several hours experimenting with the 50+ filter options to try and find one that looks correct on the device.

I've had to roll back from the latest version because I'm not going to go through all that and how things were set up before was better, even if it means I miss out on some of the new onion functionality.

**Comment by Sichroteph** [comment]
You actually miss a lot. And filters are easy to remove. Grid3x is popular, thanks for your suggestion.

**Comment by historymaker118** [comment]
Just because it's "easy to remove" does not mean that it should be there by default. The filters should be opt-in. This issue should not be 'closed' as it has not been resolved.
