### ISSUE TITLE
Can’t run any GBA roms after v3.55

### ISSUE THREAD

**Issue by Rafalas** [jimgraygit/Onion#111]
Hi! Has anyone experienced this? Any GBA titles seems to run after the last version. All roms were working before :(

**Comment by Olywa** [comment]
@Rafalas No issues with GBA at 3.55 here, I think we'd have heard more folk shout if it was broken so something must be off with your update or config. Are all your roms present in Roms\GBA and in .gba or .bin format ? GBA is using the gpsp core which doesn't support zipped roms.

**Comment by jmoneymc** [comment]
I'm actually having this issue as well. Fresh install and GBA games won't even show up when they're in the Roms folder, but they DO work when they're in the GBAHacks folder, but I have to go into the retroarch menu for that. I'm on the 3.7 beta. Thank you.

**Comment by Olywa** [comment]
@jmoneymc this issue was closed so you should either open a new one or even better, join the discord (https://discord.com/channels/529983248114122762/891336865540620338) where folk can help you solve the issue. I'm running 3.7 myself and can view & play GBA Roms fine.
