### ISSUE TITLE
Stuck in cartridge mode

### ISSUE THREAD

**Issue by jcdoll** [jimgraygit/Onion#114]
I just installed the latest release (3.55) on my new Mini.

Things were great, until I tried enabling the launcher (Cartridge mode). It properly puts me into the last game that I played upon startup. However, when I quit the game (menu+start) it immediately powers off the device and doesn't provide me with the opportunity to press the menu button to get back to the main menu. The screen goes black regardless of any additional inputs. I can get into the Retroarch menu (menu+select) but can't figure out how to get back to the main menu without powering off the device.

I fiddled around with a handful of files in .tmp_update to try to manually get out of cartridge mode (deleting the relevant text files, clearing their contents, clearing the cartridge mode game) to no avail.

Any tips for exiting cartridge mode via SD card editing? Also - is getting stuck in cartridge mode a known issue?

Thanks!

**Comment by jcdoll** [comment]
Oops, I just found the fix.

Reading /SD/App/OnionLauncher/launch.sh makes it clear which files to manually adjust in order to get out of the loop.

Regardless - quick heads up that in the latest release it's possible to get stuck in launcher mode. Might be relevant that I'm using a custom theme via the Theme Switcher app.

**Comment by Sichroteph** [comment]
thanks for your input. this shortcut allows to disable it : select + start + r2 + l2 + menu
