### ISSUE TITLE
KOF games not available in the list of neogeo emulator

### ISSUE THREAD

**Issue by Takumaz** [jimgraygit/Onion#115]
Hello,

the kof(king of fighters)  games are in the right folder but are not showing up in the game list of neo geo console :( the only way i found to play is to launch it directly from retro arch 

Why are the game not showing of in the list but avilable when you browse trough retro arch ?

**Comment by Sichroteph** [comment]
It should work by replacing the config.json file by this one in emu / arcade
[config.zip](https://github.com/jimgraygit/Onion/files/8458508/config.zip)
