### ISSUE TITLE
questions about 3.6

### ISSUE THREAD

**Issue by 7zxkv** [jimgraygit/Onion#117]
Hi,

why use mame2003+ rather than fba by default, I remind you that mame2003+ is based on a very old mame set (based on 0.78 and slightly supplemented since. But we are at 242, more than 15 years later!) and therefore offers far fewer games than fba. Does it really make sense?

Given the update rate, why not offer a real diff update between 3.55 and 3.6 (patching tools exist to make the difference in a perfect way) it would still be much more practical for us to test regularly, especially given the number updates that follow each other.

Last point: saves states of old cores that no longer worked in 3.54 and 3.55, does it work again? (I specify that the cores are all compatible with saves states in principle, so I don't understand what's going on here)

Best regards

ps: sorry for my bad english.

**Comment by Sichroteph** [comment]
Thanks for your points. FB alpha is still on the expert tab, we choose mame2003+ as a general consensus on our user base. 
The diffs between 3.55 and 3.6 would not make sense since the installer change, all the onion ressources needs to be copied so a fresh install is the only solution.
