### ISSUE TITLE
Wrong link on Wiki

### ISSUE THREAD

**Issue by thyrlian** [jimgraygit/Onion#118]
Thank you for the great repo!

On the wiki page, where the BIOS files are mentioned, there is one link pointing to the wrong place.

* Go to [Wiki page](https://github.com/jimgraygit/Onion/wiki/2.-Onion-Emulators-&-Ports)
* Under **Amiga CD32**
* There is a link: https://github.com/midwan/amiberry/wiki/Kickstart-ROMs-(BIOS)

**Expected**:
https://github.com/midwan/amiberry/wiki/Kickstart-ROMs-(BIOS)

**Actual**:
https://github.com/jimgraygit/Onion/wiki/2.-Onion-Emulators-&-Ports

**Comment by thyrlian** [comment]
Same for **PC98**:

**Expected**:
https://docs.libretro.com/library/neko_project_ii_kai/#bios

**Actual**:
https://github.com/jimgraygit/Onion/wiki/2.-Onion-Emulators-&-Ports

**Comment by Sichroteph** [comment]
Thanks, it is fixed !
