### ISSUE TITLE
Cartridge mode/ audio distortion issue

### ISSUE THREAD

**Issue by Pixelprim3** [jimgraygit/Onion#119]
On version 3.6 of the onion OS, I came across an issue with the cartridge mode as well as the audio for the default Gameboy emulator. Basically I was trying to use the cartridge functionality on Pokemon Crystal, but for whatever reason the device wasn't booting directly into the game. I kept trying to use the cartridge functionality and eventually doing so distorted the audio for all of the GameBoy Color emulators/cores. This issue also brought about the problem of Pokemon Crystal occasionally crashing upon startup.

**Comment by Sichroteph** [comment]
I would say it is a bad install.
When you launch the games in the miyoo menu, you still have this audio issues I presume ?

**Comment by Pixelprim3** [comment]
I can't seem to get back to the miyoo menu, and when I put in an sd card with nothing but roms on it, it doesn't seem to read the card. Also upon further testing, the audio distortion seems to effect every core. If you would like I could add a zip file of the contents of my SD card.

**Comment by Sichroteph** [comment]
Please install a fresh v3.6 and tell us if it fixed your issue. You probably have a bad install. Also look at the available shortcuts on the main page.
