### ISSUE TITLE
universe bios

### ISSUE THREAD

**Issue by 7zxkv** [jimgraygit/Onion#120]
Hi,

in neogeo core (no expert mode / according to the wiki it is lr-fbalpha2012), how do i get the unibios to be used? Even when selected, the configuration does not load it (and the core save settings do not change anything), this is a problem that goes back several versions.

thx

**Comment by Sichroteph** [comment]
Did you looked at this page ?
https://github.com/jimgraygit/Onion/wiki/2.-Onion-Emulators-&-Ports

**Comment by 7zxkv** [comment]
Yes !

**Comment by Sichroteph** [comment]
3qu1n0x answered in this thread :
https://discord.com/channels/529983248114122762/891336865540620338/964787542509621328

"So, I realised I had an "older" neogeo.zip which didn't include the 4.0 UniBios. So, I first got that and replaced the one in /BIOS also in /Roms/NeoGeo and /Roms/Arcade
Once I selected "UniBios" as the system, it then used the 4.0 UniBios that I had selected in the bios options from Menu/Select. UniBios options are selectable when you see the bios screen by hitting Y-B-A on the MiYoo
I was then able to turn on "blood" in MetalSlug. Once this was all done I rebooted/turned off/turned on and it held all my settings.
I'll make a video later tonight when I have a free moment"

Does this solve your issue ?

**Comment by 7zxkv** [comment]
ok it's good.

it's "neo geo mode" that I didn't see. you can select the bios from the list, if you don't activate the "mode" nothing will happen. it's really not clear retroarch for that I think but hey it's ok subject closed.

PS: On the other hand it would be good to solve the problem of the names of files/roms in the lists, the classification is not always correct, it would be necessary to be able to classify that according to several types.
