### ISSUE TITLE
Onyan theme has messed up menus

### ISSUE THREAD

**Issue by IllustratedMan-code** [jimgraygit/Onion#121]
When the menu button is pressed inside a menu, the add favorite menu and the refresh roms menu have overlapping button directions as shown in these screenshots:
![MainUI_001](https://user-images.githubusercontent.com/60514384/162831917-21ed3c7c-fd90-44ca-b92b-3b5516a7d969.png)
![MainUI_003](https://user-images.githubusercontent.com/60514384/162831944-ce386020-6965-4af9-b854-58a5e2ca0670.png)
I have used several themes, and this is the only one with the issue that I found.

**Comment by IllustratedMan-code** [comment]
I went through several more themes, and a lot of them did show this issue.

**Comment by Sichroteph** [comment]
Thanks !

**Comment by Sichroteph** [comment]
So I have investigate a bit on it and found other themes that break at this specific menu. I contacted their creator, hoping that they will fix it soon. Thank you.
