### ISSUE TITLE
D-Pad is not configured for Mame 2003+ Arcade

### ISSUE THREAD

**Issue by dwmccoy** [jimgraygit/Onion#122]
Install Arcade(Mame 2003+) from CONSOLES menu.  Launch any rom.  The directional D-Pad functions for Up, Down, Left, or Right do not work.  Installing Final Burn Alpha and Final Burn Nero from the EXPERT menu has a working functional D-Pad but the Screen is rotated 90 degrees on all Vertical roms tested.  Installation of Mame 2003+ from the expert menu also does not have a working D-Pad.  Looks like the D-Pad can be configured pressing the MENU Button and choosing Input (general) and then configure the P1 UP, DOWN, LEFT, RIGHT from there.  I would expect the D-Pad to work without any end user configuration after a fresh installation.

**Comment by Sichroteph** [comment]
I think it is fixed for the next version, thanks
