### ISSUE TITLE
OpenBOR not finding any pak files / Onion 3.6

### ISSUE THREAD

**Issue by rnzr** [jimgraygit/Onion#124]
OpenBOR launches just fine but is not able to find any paks. Tried different case-sensitive versions of the path to/in /RApp with no luck.

**Comment by dwmccoy** [comment]
This also occurs on the 3.7 beta series as well.  After looking through the configuration files I was able to determine OpenBOR is looking for the *.pak files in the /App/PlayActivity/Paks folder.  If you move the OpenBOR *.pak files to this folder they are displayed and can be started, but the video display is out of range and does not display correctly.  Also when you install OpenBOR from the Onion Installer Expert section, It puts a SNESEXAMPLE folder in the /RApp/OpenBOR folder.  This folder should not be there as it is for a SNES9X core.

**Comment by rnzr** [comment]
what @dwmccoy said still applies to 3.8.1
@dwmccoy, how did you find  out that it looks for the paks in the playactivity folder? couldnt find a reference in the config inside the openbor folder.

**Comment by dwmccoy** [comment]
I think it was in the launch.sh script.  It was pointed to the /App/PlayActivity folder.  When I looked inside it, there was a paks folder.  Once I placed the pak files into that folder they loaded, but were not playable.  This currently does not work for 3.81.

**Comment by bubblegoosenut** [comment]
I am also on 3.7.1  OpenBor will either launch with no paks listed with an error that says (IIRC) that a logfile.txt is missing; or it will load with all the paks listed, but if I try to choose one the game's audio will play behind the openbor screen and openbor will crash.

**Comment by rnzr** [comment]
until this is fixed there is a workaround. posted it here https://www.reddit.com/r/MiyooMini/comments/ua208z/anyone_know_the_path_for_pak_files_in_open_bor/i5zsht8/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

**Comment by itchyd** [comment]
> until this is fixed there is a workaround. posted it here https://www.reddit.com/r/MiyooMini/comments/ua208z/anyone_know_the_path_for_pak_files_in_open_bor/i5zsht8/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

This fix does not seem to be working any longer.  I can get the games to be visible in the openbor menu by adding them to /rapps/openbor/launch/ they unfortunately will not launch though even with parasyte installed.  Thanks!

**Comment by dwmccoy** [comment]
The following is a working solution for Onion OS 3.10.5.  Please report if it works for you.

DO NOT Install OpenBOR from the Onion OS Installer as it is currently broken.

Download parasyte [https://github.com/steward-fu/miyoo-mini/releases/download/stock/parasyte_20220125.zip](url)
Download OpenBOR [https://github.com/steward-fu/miyoo-mini/releases/download/stock/openbor_20220422.zip](url)

Unzip parasyte and place the parasyte folder in /App folder on root of SDCARD
Unzip OpenBOR and place openbor folder in /EMU folder on root of SDCARD

Edit the config.json file located in /Emu/openbor to have following values

{
"label":"OpenBOR",
"icon":"icon.png",
"iconsel":"icon.png",
"launch":"launch.sh",
"rompath":"./Paks",
"imgpath":"./Imgs",
"useswap":1,
"shortname":0,
"hidebios":0,
"extlist":"pak|PAK"
}


Edit the launch.sh file located in /EMU/openbor to have following values

#!/bin/sh

killall audioserver
killall audioserver.mod

mydir=`dirname "$0"`
midir="/mnt/SDCARD/App/parasyte/rootfs"

export HOME=$mydir
export PATH=$mydir:$midir/usr/local/sbin:$midir/usr/local/bin:$midir/usr/sbin:$midir/usr/bin:$midir/sbin:$midir/bin:$PATH
export LD_LIBRARY_PATH=$mydir/lib:$midir/lib:$midir/usr/lib:$LD_LIBRARY_PATH
export SDL_VIDEODRIVER=mmiyoo
export SDL_AUDIODRIVER=mmiyoo
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

cd $mydir
./OpenBOR "$1"

/mnt/SDCARD/miyoo/app/audioserver &


Place all game pak files into the /EMU/openbor/Pak folder

Launch OpenBOR from the Consoles Menu ...... Enjoy

**Comment by dwmccoy** [comment]
> Well this adds open bor to consoles with a nice icon, it lets me enter the openbor paks list, but when i launch one of my paks it hangs on the loading screen. 2x I was able to turn off the console with the power button by holding it for a few seconds which game me the save + power shutdown screen but the last time I tried to launch a pak it locked up the console and I had to pull the battery.

What game are you trying to play?  Make sure you have not installed OpenBOR from the expert menu of Onion OS.  If you have installed it from the Onion OS make sure to remove ALL directories associated with it.  Try deleting the Paks_cache2.db from the /EMU/openbor/Paks folder.  Refresh the ROMS from OpenBOR Console menu.

**Comment by itchyd** [comment]
I did have openbor from the installer.  I went into rapps and deleted the openbor folder.  Anything else I need to delete?

**Comment by itchyd** [comment]
Ok I deleted my installation of onion, reinstalled, installed open bor and parasyte per your instructions and IT WORKS!  Performance is poor, no sound, quitting is glitchy but it does work.  Thank you!! :)

**Comment by dwmccoy** [comment]
> Ok I deleted my installation of onion, reinstalled, installed open bor and parasyte per your instructions and IT WORKS! Performance is poor, no sound, quitting is glitchy but it does work. Thank you!! :)

Make sure you edit the launch.sh to match what I posted.  It will fix your sound.  Exit a game by pressing Menu Button x2 and what for it to exit.

**Comment by Sichroteph** [comment]
Is there something I can add in the github or in onion to help the user making this work ?

**Comment by Sichroteph** [comment]
Closing this ticket issue, don't hesitate to continue this in the discussion page.
