### ISSUE TITLE
SGB not working anymore

### ISSUE THREAD

**Issue by Wapp92** [jimgraygit/Onion#127]
Just to let you know, launching rom from the super game boy app goes black and exits. That core was working in previous build.

**Comment by leocmp** [comment]
I did a clean install and it's working normally on version 3.6

**Comment by Wapp92** [comment]
SGB needs the mgba core to be install. But mbga is a expert app, in my case by not installing a expert app i lose access to a consoles app. Can this be fix? so that consoles app don t have dependencies with expert app.

**Comment by IllustratedMan-code** [comment]
I can run GBC games just fine, what exactly are you having trouble with? 
Also, all the cores are installed under the hood, and you can switch to them in the retroarch settings without using the expert app installation.  The expert installation simply makes the cores available from the Extra Menu (after toggling expert view). The onion installer does what you want it to do. It just changes what you see by moving folders around.

**Comment by Wapp92** [comment]
Thanks, i was confuse because SGB didnt work for me and then it did work when install all app in expert. So i assume that some core wasn t move to the right place. But it could just be fluke.
