### ISSUE TITLE
TIC-80 does not run at full speed.

### ISSUE THREAD

**Issue by IllustratedMan-code** [jimgraygit/Onion#128]
Some games do not run at full speed. Stele and Supernova both appear to run at full speed, but super meat boy demake and Tiny Dungeon run at a snail's pace (about 4x slower than it should). Not sure if it is a quirk of the emulator or not. I tried enabling the threaded video setting, but it didn't seem to help.

**Comment by Edwardphantom** [comment]
me too , miku blade too not working, i try everything , whitout sucess, anyone know the maintainer of the tic80 core ?  TIC80 is really better than pico-8, if we can make it work , so it´s going to be amazing...

**Comment by Sichroteph** [comment]
Thanks for your inputs. I'll stay aware of any developments in this regards to try to improve this core performances.
