### ISSUE TITLE
Rotated games in Arcade

### ISSUE THREAD

**Issue by RevBlackie** [jimgraygit/Onion#130]
In the arcade console (fbalpha core), portrait games (Phoenix, Pac Man, etc.) are rotated 90 degrees counter-clockwise to landscape. This doesn’t happen in the MAME cores under the Expert tab, so I’m fairly sure it is based on a setting in the RA core, but I can’t find any way to change it. Is it possible to change this?

**Comment by DaPiMan** [comment]
@RevBlackie If you install 3.6 Mame2003+ is the standard Arcade core and works correctly. I cannot get FBA to rotation even with the toggle flipped in the settings for vertical mode either.

**Comment by RevBlackie** [comment]
Thanks, Jim! It's been driving me crazy, thinking I was missing something
obvious. And I didn't even realize 3.6 was out (I've been using 3.55, and
will update tonight!

Paul

**Comment by dwmccoy** [comment]
I know that Version 3.21 does not auto rotate the vertical games in any of the arcade cores.  Versions 3.54, 3.55, and version 3.60, all auto rotate vertical arcade games 90 counter clockwise which make these games unplayable.  It would be nice to know what has changed.  If you do a file compare of the retroarch.cfg files between versions, there is nothing that would indicate a difference that would break it.

**Comment by DaPiMan** [comment]
It's the FBA core that's the issue. Not the config.

**Comment by IllustratedMan-code** [comment]
Identical to #89
