### ISSUE TITLE
FEATURE REQUEST: Make the apps theme-able

### ISSUE THREAD

**Issue by IllustratedMan-code** [jimgraygit/Onion#131]
I realize this is a big ask, but it would be super cool if the apps matched the current theme. I think the easiest way to implement this would be to have some sort of config file (.json) that is shipped with the theme. During the installation process, there would be a script that would alter all of the colors in the png files based on the config file (seems pretty easy in c). The program could also alter the image at runtime, but there might be performance implications. The current apps look like they use a pretty small number of colors, so I don't think there would need to be any fancy image processing algorithms.  I'm envisioning something similar to [base16](https://github.com/chriskempson/base16) if that is familiar to anyone.

**Comment by Sichroteph** [comment]
Thanks for your suggestion, it is actually quite possible to do because all the pngs are accessible. However I feel like the designers has enough on their plate with theming the main menu, which is a lot of work. Please feel free to continue this in the discussion tab !
