### ISSUE TITLE
FEATURE REQUEST: add FBAHACK support

### ISSUE THREAD

**Issue by TaChao** [jimgraygit/Onion#132]
offical firmware support FBAHACK  but not find in onion

**Comment by IllustratedMan-code** [comment]
FBA (final burn alpha) is available in the expert menu. Is that what you are talking about?

**Comment by TaChao** [comment]
no ，there are some hack fba room
I upload emu files and a rom on google drive
https://drive.google.com/file/d/1bir58i6a2CJy-Bwppv75H6JBWXy9BOZY/view?usp=sharing

**Comment by IllustratedMan-code** [comment]
Is it a stand alone emulator or part of retroarch? I can't get into your drive folder

**Comment by TaChao** [comment]
> Is it a stand alone emulator or part of retroarch? I can't get into your drive folder
in config : Emu\FBAHACK\launch.sh
`HOME=$RA_DIR/ $RA_DIR/ra32.ss -v -L $RA_DIR/.retroarch/cores/fb_32b_libretro.so "$1"`
So copy fb_32b_libretro.so in FBAHACK dir to RetroArch\.retroarch\cores
You can run emulator . 
I don't know the emulator detail or source code. files copy from offical fw

**Comment by Sichroteph** [comment]
Closing ! Please feel free to add any feature request in the discussion tab.
