### ISSUE TITLE
SUGGESTION: Clarify the purpose of Onion Launcher to avoid confusion

### ISSUE THREAD

**Issue by Julian-MJK** [jimgraygit/Onion#136]
The issue #133 is also about this

**- The problem:**
I've seen some people be confused by Onion Launcher, and I myself was also very confused by its UX when I first started using it, that's why I suggested renaming it "Cartridge" because of the clearer purpose and UX of that app. But I've come to absolutely **love** Onion Launcher, it's amazing, but I had to wrap my head around what specifically it was and what it did before I started loving it, which genuinely took a bit of time. This can lead to people just turning it on, being confused by it, and turning it off again before giving it enough time to understand it. Adding something like a description or a more apt name & icon would go a long way.
**- The suggested solution:**
I want more people to turn it on and to use it, so that's why I'm suggesting some kind of change in the name, description or image of Onion Launcher, so that people who casually see it in Apps menu after following some guide to install Onion Launcher, will turn it on and understand it, instead of being frustrated and confused like I was and like Luvmaya in #133 is.

I think I put it well enough there so here's what I wrote in #133:

A clarification of what it's purpose can be described as
> Think of Onion Launcher as a launcher to hop between your recent games. If you quit it with B, you're out of it until you reboot.
It's for when you turn your Miyoo on and just want to play a recent game, not browse around for one. So find the games you like, boot them up once, and you can see them in Onion Launcher (with arrow left or right after pressing menu, maybe the ability to do that isn't very clear to new users).

A suggestion for communicating this to new users:
> Maybe a name or description change could help clarify this to new users, "Onion Launcher" kinda confused me at first too because it sounds like an all-encompassing solution, it's why I preferred the "Cartridge" name. What about changing the description of Onion Launcher from "A custom launcher." (tells the user nothing) to something like "Easily hop between recent games.", that should fit the screen

**- Changes to theming:**
Changing the name could also help, but the name is quite good for communicating to the user how essential and experience-changing the app is, it's not just a cartridge loader, it's a completely different console experience and UI. So I think the name is good, but the description is lacking, and the icon is quite generic as well, so what about bringing back the Cartridge iconography of the Cartridge app? Something like the enabled icon being a cartridge inserted, and the disabled being a cartridge ejected with an arrow pointing into the Miyoo. That could also help the user understand the UX

**- Changes to interface:**
I also find the new icons in the launcher a bit confusing, possibly because A & B is different on every controller, so I have to double check every time, unlike when the only actions where menu + start or menu + a. Maybe replacing the space-invader icon with a simple play icon ▶ would help as well. The list button doesn't look destructive, yet it completely quits Onion Launcher until you reboot it, so perhaps its icon should be replaced with the standard exit/leave symbol, the type that looks like [ -]> or something, or maybe just color it red to indicate the destructiveness, so that the user understands they're completely exiting the experience to the standard UI, which is a small change I think would also greatly help avoid UX confusion like in issue #133 . 

(**Subjective UX suggestion, personal opinion based on how I and I imagine others use the Miyoo:**
_The two additional icons, show activity & delete game, also add some confusion and are already doable in the Activity app. The delete-game-from-history button has the most destructive design, which is appropriate if it completely deletes it from activity, but in that case that has no need to be so easily accessible every time you exit a game, and should instead be relegated to the activity app. The shortcut to the activity app is also really redundant as you can already see the playtime for all your recent games in the OnionLauncher user interface (which will likely be the top games anytways). 
Thus I also suggest removing these two new options, as they add confusion and take away space that could instead be used to increase the size of the two icons that matter (Start & Exit) or that could fit some text, like previous versions of Onion. It feels bad to go back on changes, but sometimes new features add complexity that confuse new users, old users know the system by heart so they don't notice it, but in that case I personally think it's best to not hinder new users from understanding, by reducing needless complexity, and I don't think most people use the (great btw) activity view so frequently that its OnionLauncher shortcut adds more value than its extra clutter detracts._)

People can and seem to be confused about what the Onion Launcher does, and UI changes like these can communicate the strange UX of Onion Launcher better to the user.

**Comment by Jimmy-Z** [comment]
Thanks for the explanation.

**Comment by Jimmy-Z** [comment]
BTW power button doesn't seem to work, pressing menu will power it off instead, a little strange to me.

menu + power "sleep" works though.

3.7.1

**Comment by Sichroteph** [comment]
Thanks Julian, this post gave me ideas for a V4 if I ever find the time to do it. Closing this right now, please feel free to continue this in the discussion tab.
