### ISSUE TITLE
Still having trouble with PSX .chd files

### ISSUE THREAD

**Issue by SaintKevinH** [jimgraygit/Onion#140]
I've followed the instructions for installing the PSX emulators, but I can't get it to detect .chd files in the front end. I have added all the recommended BIOS files to the folder. I can open them directly through RetroArch and they play great, so I'm not sure what else there might be to do. it's very possible I'm just missing something, but I wanted to mention it anyway since .chd support was listed in the update notes for the most recent release.

**Comment by dwmccoy** [comment]
Looks like they made a typo or made a default game folder change.  I got my Playstation Games working by placing the games into the /Roms/PS   folder instead of the expected  /Roms/PSX   folder.

**Comment by SaintKevinH** [comment]
> Looks like they made a typo or made a default game folder change. I got my Playstation Games working by placing the games into the /Roms/PS folder instead of the expected /Roms/PSX folder.

Ah, great catch, thank you! That did it.
