### ISSUE TITLE
Wrong BIOS path on RetroArch

### ISSUE THREAD

**Issue by Dyno34** [jimgraygit/Onion#141]
Looking on the RetroArch config file, I discovered why I couldn't load my BIOS files:
The path indicated is /mnt/SDCARD/BIOS, so if your SD is not named like that your BIOS are not going to load.

I think it should be at least written somewhere, because, if I'm not wrong, on the Retro Game Corps tutorial it is said that you can name it whatever you want.

**Comment by dwmccoy** [comment]
I believe the path indicated is an internal linux mount point for Onion OS.  So in short, it is saying that your BIOS folder should be on the ROOT of the SDCARD.  The name SDCARD is internal to the OS and not what you name it.  You should be placing your BIOS files in the folder called BIOS on the ROOT of the SDCARD.

**Comment by Olywa** [comment]
yeah this is by design, the RGC guide is quite out of date now (was for a much earlier Onion release) but I agree it should probably be noted in the README.

**Comment by Sichroteph** [comment]
Thanks, I added "Copy your Bios files into the BIOS folder." in the installation instructions.
