### ISSUE TITLE
Move RetroArch saves and states to root of SD Card

### ISSUE THREAD

**Issue by erazemk** [jimgraygit/Onion#144]
According to [upgrade instructions](https://github.com/jimgraygit/Onion/wiki/1.-Installation-&-Overview-(Start-here!)#installation-upgrade), saves and states have to be backed up manually and re-added after the installation, but from what I understand, you can specify a custom RetroArch location for saves and states as such:

```
savefile_directory = "/absolute/path/to/saves"
savestate_directory = "/absolute/path/to/states"
```

Would it be possible to add this to Onion, so that the saves and states can be moved to the root of the SD Card (like BIOS files) and the installer can just keep them intact on upgrades?

**Comment by Sichroteph** [comment]
I like this idea, I will think about it

**Comment by erazemk** [comment]
@Sichroteph Can you please reopen this issue until it is implemented (if you intend to implement it at some point)?
