### ISSUE TITLE
Clean Dot mac app

### ISSUE THREAD

**Issue by Wapp92** [jimgraygit/Onion#145]
When i launch the app, my miyoo freez. 
I have a 128gb, 80gb full.
I presume that there isnt a gui and that it freez because it s scanning. 

If that is the case, it's pretty useless as is for large sdcard.

A gui to limit the search to a chosen folder or folders.

Add info text, to don t recommend use for larger than x gb card.

**Comment by Sichroteph** [comment]
I actually did not know it could be that slow, only tested on smaller cards.
Not sure if I will remove the app or add something in the description to warn the user. Thanks.
