### ISSUE TITLE
Simplified Chinese display

### ISSUE THREAD

**Issue by Mixcy** [jimgraygit/Onion#148]
3.81 onion
setting language Simplified Chinese,The main interface is not displayed
miyoo\app\lang\ch.lang
{
  "0":	" ",
  "1":	" ",
  "2":	" ",
  ...
}

**Comment by hungtcs** [comment]
Duplicate #138

**Comment by Mixcy** [comment]
> Duplicate #138 
3.8.1 It's added,but missing character.
this is the corresponding character
{
  "0": "复古模拟器",
  "1": "收藏",
  "2": "模拟器",
  "3": "街机",
  "4": "NEOGEO",
  "5": "FC",
  "6": "SFC",
  "7": "GB",
  "8": "GBA",
  "9": "MD",
  "10": "GPSP",
  "11": "SMS",
  "12": "PS",
  "13": "PCE",
  "14": "其他",
  "15": "设置",
  "16": "游戏信息",
  "17": "设备信息",
  "18": "最近游戏",
  "19": "文件",
  "20": "ADC信息",
  "21": "EncDec测试",
  "22": "按键映射",
  "23": "语言",
  "24": "音量",
  "25": "BGM音量",
  "26": "亮度",
  "27": "刷新Rom",
  "28": "恢复出厂设置",
  "29": "烧写模式",
  "30": "设备信息",
  "31": "硬件测试",
  "32": "ADC信息",
  "33": "状态:",
  "34": "延迟:",
  "35": "成功:",
  "36": "失败:",
  "37": "已停止",
  "38": "运行中",
  "39": "ADC:",
  "40": "充电中",
  "41": "OTG",
  "42": "连接断开",
  "43": "错误",
  "44": "收藏",
  "45": "取消",
  "46": "确认",
  "47": "秒",
  "48": "内",
  "49": "最近列表",
  "50": "清除",
  "51": "打开",
  "52": "删除",
  "53": "刷新",
  "54": "刷新Rom",
  "55": "加入收藏",
  "56": "升级",
  "57": "升级系统?",
  "58": "SD剩余空间\n%dM",
  "59": "型号",
  "60": "序列号",
  "61": "版本",
  "62": "CPU",
  "63": "%dMHz",
  "64": "内存",
  "65": "%dM",
  "66": "SD卡",
  "67": "恢复默认设置",
  "68": "恢复默认系统设置.\nTF卡内容不会删除",
  "69": "刷新TF卡上的rom",
  "70": "重置",
  "71": "常规键位",
  "72": "旋转键位",
  "73": "map3",
  "74": "位置",
  "75": "加载中",
  "76": "加载中",
  "77": "清除列表",
  "78": "清除最近游戏列表\nTF卡内容不会删除",
  "79": "清除收藏",
  "80": "清除所有收藏游戏\nTF卡内容不会删除",
  "81": "清除收藏",
  "82": "清除收藏游戏\nTF卡内容不会删除",
  "83": "扫描游戏",
  "84": "游戏信息",
  "85": "创建缓存",
  "86": "关机",
  "87": "还有%d秒关机",
  "88": "打开",
  "89": "返回",
  "90": "浏览",
  "91": "菜单",
  "92": "继续",
  "93": "保存",
  "94": "读取",
  "95": "音量",
  "96": "退出游戏",
  "97": "存档 %d/%d",
  "98": "空",
  "99": "没有图片",
  "100": "读取失败",
  "101": "保存失败",
  "102": "档位%d已保存",
  "103": "全屏",
  "104": "打开",
  "105": "关闭",
  "106": "原生菜单",
  "107": "软件应用",
  "108": "确定关闭设备?",
  "109": "IO测试",
  "110": "按键设置",
  "111": "退出",
  "112": "保存并退出",
  "113": "%d分后",
  "114": "从不",
  "115": "休眠",
  "116": "删除ROM",
  "117": "从列表中删除ROM?",
  "118": "颜色",
  "119": "亮度",
  "120": "色彩",
  "121": "饱和度",
  "122": "对比度",
  "123": "重启机器使设置生效",
  "124": "应用配置",
  "125": "主题",
  "126": "字体大小",
  "127": "默认",
  "128": "删除",
  "129": "音频修正",
  "130": "修正",
  "lang": "简体中文"
}
