### ISSUE TITLE
Arcade game list shows empty (path to roms is ok)

### ISSUE THREAD

**Issue by chapulanga** [jimgraygit/Onion#149]
After V3.8.1,  1976: ARC console shows an empty folder. All other consoles are just fine. Games are well arranged. The paths to roms from config.json are consistant. I create a new folder called MAME and routed from the emu config, dind't work. This issue began with 3.8.0 and continued with 3.8.1, relased this afternoon. Very fast updates deliver :)   awesome job.

Thanks.

**Comment by Lynsbian** [comment]
I had this issue too! Here's what I did to fix it: 
I went to the config file
Changed type file from "*" to "zip"
Now shows all games

**Comment by Sichroteph** [comment]
Thanks it will be fixed on the next release
