### ISSUE TITLE
Suggestion: Use .tar.zstd instead of plain small files.

### ISSUE THREAD

**Issue by Jimmy-Z** [jimgraygit/Onion#153]
I'd imagine the installer is bottlenecked by SD card IO, compressed installer will be smaller, so read is reduced, and zstd decompresses very fast so overall throughput should improve, also copying a big(ger) file compared to copying lots of small files is usually faster.

Also since the installer is always stored on SD card, this could save some space for users, though not really a concern these days.

**Comment by Sichroteph** [comment]
Thanks for your feedback, I'll consider it if I find an elegant way to implement it.
