### ISSUE TITLE
Mame Problems and FBAlpha Roms not showing up

### ISSUE THREAD

**Issue by bodobear** [jimgraygit/Onion#154]
Hi, got a problem with a few mame roms using standard ARCADE (mame2003+), Galaga88 is not starting anymore and Defender has no left/right controls. So I tried using FBA. 

After installing FBAlpha and copy a few roms into the FBALPHA roms folder i can´t see any games. 
I´m on the latest FW from 19042022 and Onion 3.8.2 (for any reason it says 3.8.1 during boot)

**Comment by bodobear** [comment]
Just installes a fresh 3.8.3 version, still the same issue FBALPHA roms not showing up. 
Got a few non working games like galaga88 etc running in other mame expert cores
but would be nice to have FBA for these titles again.

**Comment by bodobear** [comment]
Thank you !
Everythiing is working now. 
Is there a way to vertical flip the games in retopie ? Tried to change the settings without effect.

**Comment by dwmccoy** [comment]
Please refer to #89 

This appears to be an issue in the FBALPHA/FBNEO emulator.  Looks like an SDLv1 video driver library problem.

**Comment by Sichroteph** [comment]
Thanks for your feedbacks. Closing as it has been solved . (extlist is now zip|ZIP|7z|7Z|cue|CUE)
