### ISSUE TITLE
FEATURE REQUEST: Set Fast Forward Speed in Retroarch

### ISSUE THREAD

**Issue by mvergaraq** [jimgraygit/Onion#155]
Hi! In some versions of Retroarch I saw an option to set the FF speed to 2x, 3x, 4x, etc.

Can't find this option in the Miyoo Mini version, it would be great for RPG games.
Idk if this has anything to do with OnionOS though, but the current FF speed is way too overkill to speed up battles in a fun way.

**Comment by Sichroteph** [comment]
Settings > Frame Throttle > Fast-Forward Rate, you can change it to 2x, 3x, etc. 
Make the option to appear in user interface - menu item visibility.

**Comment by erazemk** [comment]
Kind of connected to this, is it possible to set fast forward as a toggle action instead of a hold action (so that if I press R2, it will stay in FF mode until I press it again)?

**Comment by Sichroteph** [comment]
Yes it is possible. Open retroarch from the apps, change your hotkeys and save configuration.

**Comment by mvergaraq** [comment]
No Frame Throttle present on my RetroArch settings: [https://ibb.co/x5stnz9](url)

Will try to reinstall OnionOS this weekend and check if I messed something up

**Comment by JitteryCore** [comment]
@mvergaraq , I just found it.

go to apps folder
Open retro arch
Go to settings
Go to user-interface
Go to menu item visibility
Go to settings
Scroll down to (show ‘File Browser’)
Make sure it’s toggled on

Now back out to the main menu of retro arch
Go to settings
Frame throttle should be there

🙃

**Comment by mvergaraq** [comment]
Awesome thank you! The item visibility comment went right through my head before lol, but I found the setting now :)
I hope this post helps someone

**Comment by Sichroteph** [comment]
Leaving this ticket open to help future users
