### ISSUE TITLE
Bring back option to hide "Expert" menu

### ISSUE THREAD

**Issue by erazemk** [jimgraygit/Onion#158]
I remember there being an app in older versions of Onion, which would let users hide the expert menu if they wanted. I think this should be present in newer versions of Onion as well, since it's useless having the menu option if there are no expert apps installed.

**Comment by Frenky81** [comment]
hello erazemk, I have the onion 3.8.2 installed  and if you go to the apps section, the first app is the expert mode, clicking on it activates or deactivates the expert mode. It is impossible that in your onion os this app is not there.

**Comment by erazemk** [comment]
> hello erazemk, I have the onion 3.8.2 installed and if you go to the apps section, the first app is the expert mode, clicking on it activates or deactivates the expert mode. It is impossible that in your onion os this app is not there.

I'm on 3.8.3 and I also checked the 3.8.3 zip file and can't find it there either.
I'll try downloading 3.7.1 and see if it's in that zip file.

**Comment by erazemk** [comment]
Ah, it seems that it was indeed removed in 3.8, @Frenky81 you must have manually copied over your old files in App.

This is the same folder (Core/App) from 3.7.1:
![image](https://user-images.githubusercontent.com/46302511/165523194-dce83f23-d1f7-4e9b-b27e-ef45e0e51165.png)

`Clean_View_Toggle` is the app I was looking for.

Hopefully Sichroteph will reconsider adding it back into 3.8.

**Comment by Sichroteph** [comment]
I will, just need to make the hack work with the new binary. Warning, if you use the old app on v3.8 you will break things.

**Comment by Frenky81** [comment]
In onion 3.8.2 there is this app ,i won't update to onion 3.8.3 ,i'll wait the next onion update because this app is fundamental for me!thanks for informations!

**Comment by Sichroteph** [comment]
Maybe this week end !

**Comment by Sichroteph** [comment]
It has been added in V3.9, thank you

**Comment by erazemk** [comment]
Thanks :)
