### ISSUE TITLE
Consider shipping with up-to-date libretro cheats preinstalled

### ISSUE THREAD

**Issue by erazemk** [jimgraygit/Onion#161]
[LibRetro database](https://github.com/libretro/libretro-database/tree/master/cht) has provided cheats for quite a few consoles. It *could* be beneficial to provide cheats for consoles that are available on the Mini (combined size of all the cheats is ~90 MB, Miyoo Mini supports < 50% of the consoles that have cheats provided, so ~45 MB).

These could be installed alongside a chosen console in Onion Installer, or just come in the `.retroarch/cheats` folder.

This would be a nice thing to have, but of course not totally necessary. If you disagree with having them preinstalled, I can add a wiki page explaining the exact process for enabling cheats on the Mini.

**Comment by 7zxkv** [comment]
I agree with this !

**Comment by 7zxkv** [comment]
it is a request that I made here:
https://github.com/jimgraygit/Onion/issues/152

personally i would agree

**Comment by Sichroteph** [comment]
> > The issue is that there are way too many files, copying them to the SD would take too long.
> 
> Do you mind if I write up a tutorial on adding cheats manually and you add it to the wiki under the F.A.Q., Onion for advanced users or a separate section?

Oh with pleasure

**Comment by erazemk** [comment]
@Sichroteph this is the text I came up with, you're free to change it if you want. I can also provide screenshots if needed.

```md
# Adding cheats

This guide will teach you how to add cheats for your RetroArch emulators.

Your first task is to find cheat files for your games (usually provided in `.cht` format). You can find them fairly easily online, but the recommended source is [LibRetro database](https://github.com/libretro/libretro-database), which has up-to-date cheats for most LibRetro supported emulators.

1. Download the [whole repository as a ZIP file](https://github.com/libretro/libretro-database/archive/refs/heads/master.zip) (Code -> Download ZIP),
1. Extract it and go into the `cht` directory (you will see cheats sorted by console),
1. Copy directories for consoles you want to your Miyoo Mini's SD card, into the `RetroArch/.retroarch/cheats` directory (you might have to enable showing hidden directories if you can't see the `.retroarch` directory),
1. Inside the `.retroarch` directory there will be a `retroarch.cfg` file, which you need to open in a text editor. Find the line with the option `quick_menu_show_cheats` and set it to `"true"` (so the whole line should be `quick_menu_show_cheats = "true"`),
1. Eject your SD card from your computer and plug it into the Miyoo Mini, then open up your favourite game (for which you have downloaded cheats),
1. Enter the RetroArch menu (press `Menu`, hold it, then press `Select`) and find the `Cheats -> Load Cheat File (Replace)` option. There you can find the cheat file in one of the directories. After choosing it you will be returned back to the cheats menu, but now you should see a number of cheats at the bottom (e.g. `Cheat #0`),
1. Select one of them, then toggle the `Enabled` switch to enable it.
```

**Comment by 7zxkv** [comment]
difference between: append and replace?

**Comment by erazemk** [comment]
> difference between: append and replace?

You can have multiple cheat files for the same game, replace will only show the new ones, append will add new ones to the bottom of the old ones.

**Comment by Wapp92** [comment]
> The issue is that there are way too many files, copying them to the SD would take too long.

That why i suggested to change the PATH for cheats in retroarche config for future build. Change it to a permanent folder like BIOS or ROM. Let the users download the cheat if they want separately.
