### ISSUE TITLE
Sega CD Build 3.8.3

### ISSUE THREAD

**Issue by Razzorik** [jimgraygit/Onion#162]
Im not seeing any of my Sega CD games in the console list, however i can access Sega CD games in my recent and favorite play lists.

**Comment by Sichroteph** [comment]
Did you refresh the list ? What is the file extensions your roms are using ?

**Comment by Razzorik** [comment]
Yea i refreshed the list, im using ,zip files. I also went and updated the firmware to the April release.

**Comment by dwmccoy** [comment]
If you look at the config.json file, ZIP file is not in the list of supported file types.  Personally I would use .ISO or .CHD for your file format types.

**Comment by Frenky81** [comment]
if you clicked on refresh roms and nothing happens ,the only explanation is that you are probably using a file extension that the emulator does not recognize, you have to go to the libretro site, on the page of that core you are using and see the list of supported extensions. Also check, in the file config.  of the emulator, that the folder in which you put the roms coincides with the one in the config.file  , otherwise edit the config.  putting in it the exact name of the folder you want to use for the roms.

**Comment by Frenky81** [comment]
anyway, i checked now, neither the genesis plus gx, nor the picodrive, that you use for the sega cd support .zip files, so go to archive.org,it's a gold mine and download a romset of the sega cd with one of the many extensions supported by the two cores. for example .iso, .chd, .bin etc ....

**Comment by Razzorik** [comment]
Why did they work on the original software and on Onion 3.5? I installed zip files on my system and they were read and used just fine. Again i can still play SegaCD games on my system that are on my favorites list and recently played list, even though i cant see them under the console. 

Its only when i updated my software from 3.54 to 3.8.3 that they went away from the console list.

**Comment by dwmccoy** [comment]
> Why did they work on the original software and on Onion 3.5? I installed zip files on my system and they were read and used just fine. Again i can still play SegaCD games on my system that are on my favorites list and recently played list, even though i cant see them under the console.
> 
> Its only when i updated my software from 3.54 to 3.8.3 that they went away from the console list.

Your current /EMU/SEGACD/config.json file should look like the following

{
"label":"1991: SCD",
"icon":"../../Icons/segacd.png",
"iconsel":"../../Icons/segacd.png",
"launch":"launch.sh",
"rompath":"../../Roms/SEGACD",
"imgpath":"../../Roms/SEGACD/Imgs",
"useswap":1,
"shortname":0,
"hidebios":1,
"extlist":"bin|BIN|chd|CHD|cue|CUE|iso|ISO"
}


Edit the "extlist" entry and add the zip file format as an option and see if it works.  See updated example below.

{
"label":"1991: SCD",
"icon":"../../Icons/segacd.png",
"iconsel":"../../Icons/segacd.png",
"launch":"launch.sh",
"rompath":"../../Roms/SEGACD",
"imgpath":"../../Roms/SEGACD/Imgs",
"useswap":1,
"shortname":0,
"hidebios":1,
"extlist":"bin|BIN|chd|CHD|cue|CUE|iso|ISO|zip|ZIP"
}

**Comment by Razzorik** [comment]
thank you @dwmccoy, that worked perfectly. The games are back and working.

**Comment by Sichroteph** [comment]
Added these new extensions for the next release, thanks !
