### ISSUE TITLE
FEATURE REQUEST: Walkthrough/Docs Popup

### ISSUE THREAD

**Issue by haysidney** [jimgraygit/Onion#163]
I’m not sure how realistic this is, but I’d love to be able to reference a walkthrough (just a txt file per game) on the Mini itself. In a perfect world I’d prefer a shortcut to switch between the game and a scrollable, bookmarkable (or it remembers your place somehow) walkthrough/notes screen. It can be readonly, just a txt file named after the currently playing ROM or something.

If it can’t run at the same time as Retroarch, maybe it could be accessed from the Onion Launcher when looking at a game?

I know there’s a lot of development happening right now, but one day I’d love to have this functionality. :)

**Comment by mutcianm** [comment]
Looks like a reasonable feature request for retroarch itself.
However a quick issue search didn't yield any well-formulated requests:
- https://github.com/libretro/RetroArch/issues/6752 
- https://github.com/libretro/RetroArch/issues/12159

**Comment by Sichroteph** [comment]
Thank you for your suggestion. It would be awesome indeed but needs quite a lot of development.
I added it in my todo list, however I can't promise if / when I will work on it.
