### ISSUE TITLE
Rom Image file format?

### ISSUE THREAD

**Issue by mcteapot** [jimgraygit/Onion#166]
What is the file format and size required for an image to show up for the corresponding roms?

Also for the Onion to recognize them, they need to be in the same imgs->Folder?

**Comment by dwmccoy** [comment]
File format is PNG 256x350.  The images need to be placed into /ROMS/Game System/Imgs folder.  The Imgs folder name is case sensitive.  Examples would be like the following

/Roms/FC/Imgs
/Roms/SFC/Imgs
/Roms/GB/Imgs.

**Comment by Sichroteph** [comment]
> File format is PNG 256x350. The images need to be placed into /ROMS/Game System/Imgs folder. The Imgs folder name is case sensitive. Examples would be like the following
> 
> /Roms/FC/Imgs /Roms/SFC/Imgs /Roms/GB/Imgs.

I hope you don't mind, I shamelessly copied your answer into the FAQ. Thank you.
