### ISSUE TITLE
Fix audio option inside settings

### ISSUE THREAD

**Issue by GhsVilela** [jimgraygit/Onion#167]
I'm having a problem with latest version 3.8.3 , if this setting is ON, emulation starts to get real fast and without any audio, with this option OFF, emulation works on normal speed but the audio is not good, this is going to be fixed on next updated?

**Comment by dwmccoy** [comment]
Official Miyoo Firmware dated 20220419 states that if your not using the stock OS, you should turn the sound fix off.  If your having sound issues in game, can you be more specific as to which emulator or system in general is affected?

**Comment by Sichroteph** [comment]
This option should have no effect as the audio server is disabled. (I should have hid this item)
Does your issue still persists on 3.9 ?

**Comment by GhsVilela** [comment]
I'm not at stock firmware 20220419 and onion 3.9, I'm going to update everything when I have some time and I let you guys know, the problem today is that emulation audio is having some crackling/popping, I didn't notice this on versions lower than 3.8.3, is affecting all systems/emulators.

**Comment by GhsVilela** [comment]
I was able to fixed it, I updated to last version of miyoo mini official firmware and then did a fresh  install of Onion OS 3.9.1, audio is perfect now. Guys, one last thing, why on this last version the power button is not only turning off the display but instead is shutting down the whole system? can I change this?

**Comment by graythen** [comment]
[BUG]I download the latest firmware vision V3.10.6. When I run the ONScripter, games run without voice. This problem is easy to solve in the official firmware. Just turn off the Fix audio in the setting menu, the ONS games will run with normal voice. But I can't find the Fix audio option in setting menu of Onion firmware. How can this problem be solved?

**Comment by Sichroteph** [comment]
https://github.com/jimgraygit/Onion/wiki/3.-FAQ-(Frequently-asked-questions)
