### ISSUE TITLE
Remap exit hot keys for retroarch. 

### ISSUE THREAD

**Issue by AndrewMc1** [jimgraygit/Onion#17]
Hey team, just a quick thought. 

Currently: [start] +[select] brings up the retroarch menu. Hitting them again exits back to the main UI. 

It feels a little counter intuitive if you want to tweak a setting and return to your game to check it out. 

Suggested changes: set [start] + [select] to open the retroarch menu and close the menu - returning to the game. Utilise the miyoo option button to exit back to the main UI instead.

**Comment by Sichroteph** [comment]
Andrew, there is another exit hotkey that you should like : Menu + start
