### ISSUE TITLE
Possible to enable load/save state in expert mode ?

### ISSUE THREAD

**Issue by ultimatecollections** [jimgraygit/Onion#170]
Thanks for the great os.
However, would it be possible to enable load/save state in the retroarch menu for all the emulators under the "expert" section ?
It would be a lot lot better as I'm using the PUAE emulator among other things, but i'm unable to save states and this is quite annoying.
I guess everybody will be happy to have these options enabled there as well :)
I don't know if it's a bug or a "feature" which is not enabled as of now ?
Thanks in advance :)

Stéphane

**Comment by Txori** [comment]
Hello. I have the same problem using lr-bluemsx, so being able to enable load/save state would be a great addition.

**Comment by Sichroteph** [comment]
If you don't have save states enabled, it is because of the core that does not provide this option yet. Nothing we can do on our side except watch for new cores that allows it.
