### ISSUE TITLE
New Themes are missing in V3.9

### ISSUE THREAD

**Issue by kjm1988** [jimgraygit/Onion#171]
The new themes don't seem to be included in V3.9 or V3.9.1.

**Comment by dwmccoy** [comment]
Themes are present in 3.9 and 3.91.  To enable, please install the Theme Switcher App located in APPS of the Onion OS installer.  Once installed, open the Theme Switcher App from the Apps menu and select your theme.

**Comment by kjm1988** [comment]
Thank you! :)

**Comment by kjm1988** [comment]
I have just double checked this and the option is definitely missing for MakoVII in my Theme Switcher, the theme doesn't appear in the folders when viewing the card on Windows either. I installed 3.9 to a fresh card and updated to 3.9.1.

**Comment by kjm1988** [comment]
Downloading the MakoVII theme from Reddit and creating a config.json works. I'm not sure how I'm missing the new themes?... my v3.9 theme folder contains:

HippoStock
Lilla
MakoVII (installed manually by me)
Miyoo blues
OnionBoy
Switch - Pixelshift

**Comment by dwmccoy** [comment]
That theme is not included in the default installation of 3.9 or 3.91.  To install that theme, please go to the Theme Repository located here -> https://github.com/jimgraygit/Onion/wiki/4.-Theme-Repository    and follow the installation guide for installing themes.

**Comment by kjm1988** [comment]
Perfect, thanks again!
