### ISSUE TITLE
FEATURE REQUEST: Hide part of rom name

### ISSUE THREAD

**Issue by ZacharyRanes** [jimgraygit/Onion#177]
It would be nice if the UI hide the part of a rom name that is inside () that way a rom named "Chrono Trigger (USA).smc" would show up as just "Chrono Trigger"

I am thinking like the tidy rom name in Adam image UI.

**Comment by ismaelzsilva** [comment]
What works for me is to scrap everything on pc and after I use the PowerTool Rename app to rename everything together. Works pretty well. But yeah, using a gamelist.xml like file would be nice, since its used in a lot of other places

**Comment by d0rf3n** [comment]
> What works for me is to scrap everything on pc and after I use the PowerTool Rename app to rename everything together. Works pretty well. But yeah, using a gamelist.xml like file would be nice, since its used in a lot of other places

I also support the gamelist format since it's available. Descriptions and other info would be cool in the one-game-per-page-list-view.
