### ISSUE TITLE
Enable edit Hotkey 

### ISSUE THREAD

**Issue by MrWidge** [jimgraygit/Onion#18]
At the moment I'm trying to edit the Hotkeys for retroarch in the "consoles" section (sadly I really dislike the current shortcut setup)  But everytime I remap them and quit out, it reverts back to how it was.

Also on the snes  because you have fast forward toggle and hold, set to the same command key they cancel each other out. Nothing happens. But When I remapped the toggle to Y it worked perfectly.

**Comment by jimgraygit** [comment]
Hi MrWidge, the hotkey can only be mapped manually from your notepad app of choice.  As for the remap, thanks for the heads up i will change that in the next update.
