### ISSUE TITLE
Arcade/Mame Audio Samples

### ISSUE THREAD

**Issue by bodobear** [jimgraygit/Onion#180]
Hi, is ti possible to use audio samples for Mame/FBA... and where do I have to store them ?
Tried to put them in /roms/arcade/samples but it was not working.
 
Thank you, Bodo

**Comment by dwmccoy** [comment]
Place your audio samples into the folders listed below

Mame2003 Plus      /BIOS/mame2003-plus/samples
Final Burn Neo        /BIOS/fbneo/samples
Final Burn Alpha     /BIOS/fba/samples

**Comment by bodobear** [comment]
Thank you ! Perhaps it would be nice to put these info also in the Wiki / Arcade.
