### ISSUE TITLE
Hibernation not working?

### ISSUE THREAD

**Issue by naddel91** [jimgraygit/Onion#184]
I set the value to 5 mins, but nothing happens.
Does this only work in games? In menu it does not. I am on latest ONION and miyoo OS. 
how to fix this?

**Comment by dwmccoy** [comment]
I can confirm this is not working.  I have two Miyoo Mini's.  Both units have the most current firmware from 20220419. One uses Onion OS, the other uses the current Stock OS.  The hibernation works as expected on the Stock OS but does not work on Onion OS 3.91.

**Comment by naddel91** [comment]
Thanks for confirmation. I almost thought I was too silly to make that simple feature work.

**Comment by Sichroteph** [comment]
Hibernation has been remove from the recent onion version, it will come back when we think it works properly.
