### ISSUE TITLE
Disks and m3u

### ISSUE THREAD

**Issue by Captainzilla418** [jimgraygit/Onion#186]
I have tried to use m3u files for ps1 and it will not play the game also i dont know how to switch disks with multi disk games

**Comment by dwmccoy** [comment]
I'm no expert on this subject but I believe your files need to be in the .bin .cue format.  Files in the .iso format do not work inside of an .m3u file from what I've read.  The .m3u file has to contain the exact file names of your .cue files.  Those names are case sensitive as well.  Your .m3u file is a text file but it can not have a .txt filename extension on it.  In my testing I used the Game Driver 2.  My disc files were labeled like below

Driver 2 (Disc 1) (v1.1)
Driver 2 (Disc 2) (v1.1)

My m3u file was named

Driver 2 (v1.1).m3u

And it's contents were the following

Driver 2 (Disc 1) (v1.1).cue
Driver 2 (Disc 2) (v1.1).cue

When you launch the PlayStation Emulator from the menu you will see the following files to choose from

Driver 2 (Disc 1) (v1.1)
Driver 2 (Disc 2) (v1.1)
Driver 2 (v1.1)

Open the m3u file named

Driver 2 (v1.1)

To change disc in game, use the RetroArch Menu by pressing Select+Menu and go to disc controls to eject/load a new disc when prompted to change disc.

**Comment by Captainzilla418** [comment]
> I'm no expert on this subject but I believe your files need to be in the .bin .cue format. Files in the .iso format do not work inside of an .m3u file from what I've read. The .m3u file has to contain the exact file names of your .cue files. Those names are case sensitive as well. Your .m3u file is a text file but it can not have a .txt filename extension on it. In my testing I used the Game Driver 2. My disc files were labeled like below
> 
> Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1)
> 
> My m3u file was named
> 
> Driver 2 (v1.1).m3u
> 
> And it's contents were the following
> 
> Driver 2 (Disc 1) (v1.1).cue Driver 2 (Disc 2) (v1.1).cue
> 
> When you launch the PlayStation Emulator from the menu you will see the following files to choose from
> 
> Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1) Driver 2 (v1.1)
> 
> Open the m3u file named
> 
> Driver 2 (v1.1)
> 
> To change disc in game, use the RetroArch Menu by pressing Select+Menu and go to disc controls to eject/load a new disc when prompted to change disc.

Well im also having issues with sega saturn and sega dream cast not playing any games even if i use files it says it supports like saturn with .m3u

**Comment by dwmccoy** [comment]
> > I'm no expert on this subject but I believe your files need to be in the .bin .cue format. Files in the .iso format do not work inside of an .m3u file from what I've read. The .m3u file has to contain the exact file names of your .cue files. Those names are case sensitive as well. Your .m3u file is a text file but it can not have a .txt filename extension on it. In my testing I used the Game Driver 2. My disc files were labeled like below
> > Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1)
> > My m3u file was named
> > Driver 2 (v1.1).m3u
> > And it's contents were the following
> > Driver 2 (Disc 1) (v1.1).cue Driver 2 (Disc 2) (v1.1).cue
> > When you launch the PlayStation Emulator from the menu you will see the following files to choose from
> > Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1) Driver 2 (v1.1)
> > Open the m3u file named
> > Driver 2 (v1.1)
> > To change disc in game, use the RetroArch Menu by pressing Select+Menu and go to disc controls to eject/load a new disc when prompted to change disc.
> 
> Well im also having issues with sega saturn and sega dream cast not playing any games even if i use files it says it supports like saturn with .m3u

I do not see an option for Sega Saturn emulator or Sega Dreamcast in Onion OS.  Sega Dreamcast VMU is not the same as Sega Dreamcast.  The Miyoo Mini's hardware will probably never support those systems as they require more system resources than the Miyoo Mini could ever provide.

**Comment by Captainzilla418** [comment]
> > > I'm no expert on this subject but I believe your files need to be in the .bin .cue format. Files in the .iso format do not work inside of an .m3u file from what I've read. The .m3u file has to contain the exact file names of your .cue files. Those names are case sensitive as well. Your .m3u file is a text file but it can not have a .txt filename extension on it. In my testing I used the Game Driver 2. My disc files were labeled like below
> > > Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1)
> > > My m3u file was named
> > > Driver 2 (v1.1).m3u
> > > And it's contents were the following
> > > Driver 2 (Disc 1) (v1.1).cue Driver 2 (Disc 2) (v1.1).cue
> > > When you launch the PlayStation Emulator from the menu you will see the following files to choose from
> > > Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1) Driver 2 (v1.1)
> > > Open the m3u file named
> > > Driver 2 (v1.1)
> > > To change disc in game, use the RetroArch Menu by pressing Select+Menu and go to disc controls to eject/load a new disc when prompted to change disc.
> > 
> > 
> > Well im also having issues with sega saturn and sega dream cast not playing any games even if i use files it says it supports like saturn with .m3u
> 
> I do not see an option for Sega Saturn emulator or Sega Dreamcast in Onion OS. Sega Dreamcast VMU is not the same as Sega Dreamcast. The Miyoo Mini's hardware will probably never support those systems as they require more system resources than the Miyoo Mini could ever provide.

The emulators are on the emulation list and are in expert area of the installation of onion os

**Comment by dwmccoy** [comment]
> > > > I'm no expert on this subject but I believe your files need to be in the .bin .cue format. Files in the .iso format do not work inside of an .m3u file from what I've read. The .m3u file has to contain the exact file names of your .cue files. Those names are case sensitive as well. Your .m3u file is a text file but it can not have a .txt filename extension on it. In my testing I used the Game Driver 2. My disc files were labeled like below
> > > > Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1)
> > > > My m3u file was named
> > > > Driver 2 (v1.1).m3u
> > > > And it's contents were the following
> > > > Driver 2 (Disc 1) (v1.1).cue Driver 2 (Disc 2) (v1.1).cue
> > > > When you launch the PlayStation Emulator from the menu you will see the following files to choose from
> > > > Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1) Driver 2 (v1.1)
> > > > Open the m3u file named
> > > > Driver 2 (v1.1)
> > > > To change disc in game, use the RetroArch Menu by pressing Select+Menu and go to disc controls to eject/load a new disc when prompted to change disc.
> > > 
> > > 
> > > Well im also having issues with sega saturn and sega dream cast not playing any games even if i use files it says it supports like saturn with .m3u
> > 
> > 
> > I do not see an option for Sega Saturn emulator or Sega Dreamcast in Onion OS. Sega Dreamcast VMU is not the same as Sega Dreamcast. The Miyoo Mini's hardware will probably never support those systems as they require more system resources than the Miyoo Mini could ever provide.
> 
> The emulators are on the emulation list and are in expert area of the installation of onion os

What core are you using in the expert mode to try and play Saturn and Dreamcast?  I see no Mednafen core for Sega Saturn and Dreamcast is not in the emulation list.  Do not confuse Dreamcast VMU for Dreamcast, they are not the same.

**Comment by Captainzilla418** [comment]
> > > > > I'm no expert on this subject but I believe your files need to be in the .bin .cue format. Files in the .iso format do not work inside of an .m3u file from what I've read. The .m3u file has to contain the exact file names of your .cue files. Those names are case sensitive as well. Your .m3u file is a text file but it can not have a .txt filename extension on it. In my testing I used the Game Driver 2. My disc files were labeled like below
> > > > > Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1)
> > > > > My m3u file was named
> > > > > Driver 2 (v1.1).m3u
> > > > > And it's contents were the following
> > > > > Driver 2 (Disc 1) (v1.1).cue Driver 2 (Disc 2) (v1.1).cue
> > > > > When you launch the PlayStation Emulator from the menu you will see the following files to choose from
> > > > > Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1) Driver 2 (v1.1)
> > > > > Open the m3u file named
> > > > > Driver 2 (v1.1)
> > > > > To change disc in game, use the RetroArch Menu by pressing Select+Menu and go to disc controls to eject/load a new disc when prompted to change disc.
> > > > 
> > > > 
> > > > Well im also having issues with sega saturn and sega dream cast not playing any games even if i use files it says it supports like saturn with .m3u
> > > 
> > > 
> > > I do not see an option for Sega Saturn emulator or Sega Dreamcast in Onion OS. Sega Dreamcast VMU is not the same as Sega Dreamcast. The Miyoo Mini's hardware will probably never support those systems as they require more system resources than the Miyoo Mini could ever provide.
> > 
> > 
> > The emulators are on the emulation list and are in expert area of the installation of onion os
> 
> What core are you using in the expert mode to try and play Saturn and Dreamcast? I see no Mednafen core for Sega Saturn and Dreamcast is not in the emulation list. Do not confuse Dreamcast VMU for Dreamcast, they are not the same.

Sega Saturn

Emulator: lr-mednafen-saturn
Rom Folder: SATURN
Extensions: .img .IMG .cue .CUE .chd .CHD .iso .ISO .m3u .M3U
Bios: saturn_bios.bin (Optional)
Note: This will never run full speed!

Look at the wiki and once i put my card back in my miyoo mini i will send a picture

**Comment by dwmccoy** [comment]
> > > > > > I'm no expert on this subject but I believe your files need to be in the .bin .cue format. Files in the .iso format do not work inside of an .m3u file from what I've read. The .m3u file has to contain the exact file names of your .cue files. Those names are case sensitive as well. Your .m3u file is a text file but it can not have a .txt filename extension on it. In my testing I used the Game Driver 2. My disc files were labeled like below
> > > > > > Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1)
> > > > > > My m3u file was named
> > > > > > Driver 2 (v1.1).m3u
> > > > > > And it's contents were the following
> > > > > > Driver 2 (Disc 1) (v1.1).cue Driver 2 (Disc 2) (v1.1).cue
> > > > > > When you launch the PlayStation Emulator from the menu you will see the following files to choose from
> > > > > > Driver 2 (Disc 1) (v1.1) Driver 2 (Disc 2) (v1.1) Driver 2 (v1.1)
> > > > > > Open the m3u file named
> > > > > > Driver 2 (v1.1)
> > > > > > To change disc in game, use the RetroArch Menu by pressing Select+Menu and go to disc controls to eject/load a new disc when prompted to change disc.
> > > > > 
> > > > > 
> > > > > Well im also having issues with sega saturn and sega dream cast not playing any games even if i use files it says it supports like saturn with .m3u
> > > > 
> > > > 
> > > > I do not see an option for Sega Saturn emulator or Sega Dreamcast in Onion OS. Sega Dreamcast VMU is not the same as Sega Dreamcast. The Miyoo Mini's hardware will probably never support those systems as they require more system resources than the Miyoo Mini could ever provide.
> > > 
> > > 
> > > The emulators are on the emulation list and are in expert area of the installation of onion os
> > 
> > 
> > What core are you using in the expert mode to try and play Saturn and Dreamcast? I see no Mednafen core for Sega Saturn and Dreamcast is not in the emulation list. Do not confuse Dreamcast VMU for Dreamcast, they are not the same.
> 
> Sega Saturn
> 
> Emulator: lr-mednafen-saturn Rom Folder: SATURN Extensions: .img .IMG .cue .CUE .chd .CHD .iso .ISO .m3u .M3U Bios: saturn_bios.bin (Optional) Note: This will never run full speed!
> 
> Look at the wiki and once i put my card back in my miyoo mini i will send a picture

Ok, after a bit of research the Saturn Emulator is not an installation option with a clean install of Onion OS 3.10 Beta.  It was however installable with Version 3.92 and earlier.  The performance is so poor I can see why it has been omitted from 3.10 so far.  If you want to try it out you will need to install version 3.92.  Once 3.92 has been installed, and you have added the emulator core to the expert menu, perform the following.

1. Edit the config.json file located in the /RApp/mednafen_saturn folder to look like this

{
"label":"mednafen_saturn",
"icon":"mednafen_saturn.png",
"iconsel":"",
"launch":"launch.sh",
"rompath":"../../Roms/SATURN",
"imgpath":"../../Imgs/SATURN",
"useswap":1,
"shortname":0,
"hidebios":1,
"extlist":"cue|chd|ccd|toc|iso|m3u"
}

2. Copy the following BIOS files into the /BIOS folder.  The roms were shipped on your original card that came with the unit.  They would be located in /RetroArch/.retroarch/system

saturn_bios.bin
sega_101.bin
mpr-17933.bin
mpr-18811-mx.ic1
mpr-19367-mx.ic1

3. To play a game using the M3U format, following the instructions I posted above for the PlayStation M3U file creation.  The steps are exactly the same.  I only tested cue files for M3U testing as I had no other multi-disc games available.

**Comment by Sichroteph** [comment]
Leaving this ticket open for future users

**Comment by Sichroteph** [comment]
Added the M3U dmwccoy in the FAQ. Closing now, don't hesitate to continue this in the discussion tab.
