### ISSUE TITLE
Unable to switch themes

### ISSUE THREAD

**Issue by Hazard15301** [jimgraygit/Onion#188]
Patched from 3.8.1 to 3.8.3, then did a fresh install from 3.8.3 to 3.9.2. Went through the installer, set up my cores. When I turn the Mini on, there is no option to switch themes. There is no switcher app under "Apps, and there is no way to install one through the Onion installer. Nothing under the settings menu either.

Should note that I did not format my SD card before the fresh install, just copied the contents of the zip file to the root of my SD card.

**Comment by Hazard15301** [comment]
I did not do my due diligence and search for the issue first. This is a duplicate of [#176](https://github.com/jimgraygit/Onion/issues/176). This suggestion from dwmccoy worked for me: 
"Sounds like your installation got broken. If your trying to avoid a re-install, you could unzip the OnionOS 3.91 zip file and copy the .tmp_update.data\Layer2\Theme switcher\App\ThemeSwitcher folder over to your /APP folder on your SDCARD to see if it resolves your issue."

**Comment by Olywa** [comment]
Hi there, glad to see you solved this. It would be really great if you could close the issue yourself and save the developer a little time in managing issues.
