### ISSUE TITLE
Vibrate motor and force close

### ISSUE THREAD

**Issue by Yahcob** [jimgraygit/Onion#189]
Just recently installed 3.9.2
had zero problems with my older v3
however this new version vibrates on low battery, which is really annoying! 
is there any way to turn off this feature?
also once its done vibrating it force closes whatever game I'm in?
is there a way to disable it from doing that?
its even worse cause it vibrates every 30 seconds so i cannot play any game whilst I'm on low battery!

any help would be appreciated!

Thanks - Yahcob

**Comment by Sichroteph** [comment]
It doesn't force close it. It saves your states so you won't loose any progression.
