### ISSUE TITLE
No games in my SD

### ISSUE THREAD

**Issue by espectrunk** [jimgraygit/Onion#191]
Hi, sorry to bother you. I upgraded my SD card to Onion V3 and I don't have any games in the emulators, how can I get all the games back? Thanks ; )

**Comment by Yahcob** [comment]
hey
make sure all your roms are placed in the correct folders on the SD card
usually in the ROMS folder

**Comment by espectrunk** [comment]
> hey
> 
> make sure all your roms are placed in the correct folders on the SD card
> 
> usually in the ROMS folder

Thnx for your fast reply. In /ROMS folder i have all the retro consoles names folders and them are empty, except /fc with tons of .zip games. And also atari7800 and others. 

![image](https://user-images.githubusercontent.com/1770011/167448000-c2806b71-4110-49e8-a8b9-8880a28ec3cd.jpeg)

![image](https://user-images.githubusercontent.com/1770011/167448016-9b3c4af2-38be-4bb2-8d30-989e296c8e2b.jpeg)

**Comment by Yahcob** [comment]
so just checking, all the other folders are empty? 
except for ATARI and FC?
do these games show up in the atari and FC emulator section on consoles?

**Comment by espectrunk** [comment]
> so just checking, all the other folders are empty? 
> 
> except for ATARI and FC?
> 
> do these games show up in the atari and FC emulator section on consoles?

Nope, dont showing up. All empty.

I have .zip files in: Arcade, atari2600, atari7800, fc, gb, gba (those ones arent .rar), mame2003, mame2010, md, ms, neogeo, ngp, pce (extension .pce), ps, sfc, wsc. 

cps1, cps2 and cps3 (recently copied from arcade/cps1, etc...

No games showed

**Comment by espectrunk** [comment]
cps1, 2 and 3 yes, right now display games

**Comment by Yahcob** [comment]
i know it may seem strange
but have you tried pressing the menu button in the console menu
and refreshing the rom list?

if that doesnt work all i can think of 
is to check the config files within the EMU folder
within each emulator theres a recognised extension part
should look like
"extlist":"zip"
if not try adding one?

**Comment by espectrunk** [comment]
If not... how i can install v3 in SD from scratch with all Content? Any guide? Thnx in advance ^^

**Comment by erazemk** [comment]
> If not... how i can install v3 in SD from scratch with all Content? Any guide? Thnx in advance ^^

Copy/back up your ROMs and Apps to your PC, then go to `RetroArch/.retroarch/` and copy over `saves` and `states` as well.
Then just format your sdcard as FAT32 and extract the latest Onion onto it, like you did with the first install.

When you've set everything up, you can re-copy all the files back, but keep the new folder structure (if it's different) - e.g. manually copy over games if now the folder is called `FC` instead of `fc`.

**Comment by espectrunk** [comment]
> > If not... how i can install v3 in SD from scratch with all Content? Any guide? Thnx in advance ^^
> 
> 
> 
> Copy/back up your ROMs, BIOSes and Apps to your PC, then go to `RetroArch/.retroarch/` and copy over `saves` and `states` as well.
> 
> Then just format your sdcard as FAT32 and extract the latest Onion onto it, like you did with the first install.
> 
> 
> 
> When you've set everything up, you can re-copy all the files back, but keep the new folder structure (if it's different) - e.g. manually copy over games if now the folder is called `FC` instead of `fc`.

Ok, Thnx a lot. Lend me try and anything i wrote you. 

Thnx a lot all for ur help 🤜🤛

**Comment by espectrunk** [comment]
> > If not... how i can install v3 in SD from scratch with all Content? Any guide? Thnx in advance ^^
> 
> Copy/back up your ROMs, BIOSes and Apps to your PC, then go to `RetroArch/.retroarch/` and copy over `saves` and `states` as well. Then just format your sdcard as FAT32 and extract the latest Onion onto it, like you did with the first install.
> 
> When you've set everything up, you can re-copy all the files back, but keep the new folder structure (if it's different) - e.g. manually copy over games if now the folder is called `FC` instead of `fc`.

Hello again, im sorry bother. 

I have reinstalled ONIONV3 on a new Micro SD, from scratch without any problem. Now I'm moving .rar of games to their folders, but many of them I don't know where they go. How can I recognize where to put each game?

For example, on the old system inside "arcade/" I had other folders called "shot", "pgm". The .rar games inside where should I move them?

Thanks in advance ;D

**Comment by espectrunk** [comment]
Good morning! I have finally been able to move the games to each folder. Although I lost all the GBC games ;( 

In V3 they have implemented many new emulators, but no games?  Where can I get all the games from the new emulators?

Have a nice day!

**Comment by erazemk** [comment]
> Although I lost all the GBC games ;(

GBC games should be in the GBC folder, just like before. If you did put them there, try refreshing the game list (I think it's MENU while in the main menu, then there should be an option to refresh).

> In V3 they have implemented many new emulators, but no games? Where can I get all the games from the new emulators?

Onion doesn't distribute games, since that would be illegal. You'll have to find the games on your own, but it's not hard if you do a bit of searching on the internet.

**Comment by espectrunk** [comment]
Great! Thnx a lot all for your help!
