### ISSUE TITLE
shortcuts not working?

### ISSUE THREAD

**Issue by naddel91** [jimgraygit/Onion#193]
I just tried in several emulators and the shortcuts that should be hardcoded do not seem to work.

https://github.com/jimgraygit/Onion#shortcuts

Load/save state in PSX is not functional for example. Only through retroarch menu, but not shortcuts.

Am I missing out on something or is this a bug?

**Comment by Olywa** [comment]
Hi there I have just tested this in PSX and for me (on 3.9.1) the shortcuts are behaving as expected (I was able to save and load states). I think something is wrong with your installation/config. Is it possible you remapped some of the keys in RA at some point, even by accident? You can check (and re-add them) in retroarch:

Start PSX content, go to RA menu-> settings-> input-> hotkeys (set as you wish & make sure to save overrides). 
Alternatively perhaps a clean (re)install of Onion will solve this for you. 

--
If you are satisfied with my response it would be great if you could close the issue yourself and save the developer a little time in managing issues.

**Comment by naddel91** [comment]
Will try a fresh Install and Report Back.

Olywa ***@***.***> schrieb am Mi., 11. Mai 2022, 03:29:

**Comment by viola8757** [comment]
I had the same problem, reinstalled with latest version and save state works fine.

**Comment by Sichroteph** [comment]
Ok closing !
