### ISSUE TITLE
Onion Installer doesn't boot

### ISSUE THREAD

**Issue by mountaindrew52** [jimgraygit/Onion#194]
I updated to the newest official Miyoo firmware on a brand new Mini that just arrived today, then attempted to install Onion. I followed the instructions exactly and used a 64GB Sandisk "extreme" 64gb SD card that I previously used for my 2DS XL, wiped and reformatted it to FAT32 via EaseUS program on Windows (it was already using FAT32, but I wiped and reformatted it to get rid of the 3DS files Windows didn't let me delete), extracted the ".tmp_update" folder to the root of the SD card, inserted it into my Miyoo, and when I hold the power button to power it on and supposedly start the update, it just shows the Miyoo logo and boots into the Miyoo firmware. I did everything right, and it simply did not work. 

Edit: I tried this again with a Sandisk "Ultra" 32GB I had on me, went through the same process, and the Onion Installer worked... My experience, as well as r/palo34 experience with a 64GB Sandisk SD card suggests to me that there may be some issue with that specific SD card variant

**Comment by rsr427** [comment]
Any clarification or guidance on this would be helpful.  I'm in the same boat with a 64 gb card.  Considering I have a 64gb card from the factory it wouldn't make sense to downgrade to a 32gb card.  I kind of need this to work since the Miyoo official update no longer "sees" PS and MD files. I was much better off stock at this point.

**Comment by dwmccoy** [comment]
I currently have two Miyoo Mini's and I routinely swap between 64gb and 128gb cards with no issues.  My experience working with USB flash drives and Micro SD cards would lead me to believe the card is either bad or has data corruption on it.

**Comment by Olywa** [comment]
Hi there, Some cards definitely seem to have issues. From your edit it sounds like you proved it was the card. If it's resolved and you are happy it would be really great if you could close the issue yourself and save the developer a little time in managing issues.

**Comment by rsr427** [comment]
Tried a new Micro Center card (which works in other devices), and a Samsung Evo and I can not get the firmware to update when I plug it in.  It goes straight to a "charging" screen.  Which is comical when it happens when the battery is pulled.  

Is there a crowdsourced list of cards that are known to work (eg. not Sandisk "Extreme" but Sandisk "Ultra".) and what size? Particularly if this entirely depends on the brand.  Otherwise I'd have to order 4-5 cards that may or may not work and send the rest back...

**Comment by dwmccoy** [comment]
The latest firmware released 20220419 is not required for latest Onion OS.  I have only flashed two systems to latest firmware.  The first system I used a 128GB PNY Elite-X.  The 2nd System I used a Samsung EVO Select 64GB Blue Label.  Make sure to put the firmware image on a FAT32 formatted disk. Place the image file "miyoo283_fw.img" on the root of the SDCARD.  Remove the battery.  Place your SDCARD into the Miyoo Mini.  Use a power adapter that does not exceed 5V output and plug it into the Miyoo Mini using the supplied USB cable.  Do not use a USB Port from a PC to supply the Power.  The power adapter I used was commonly shipped with iPhones.

I have also used various flash cards to load Onion and the Stock OS on to the Miyoo Mini.  I have used Sandisk Ultra's, Samsung Evo's, and PNY Elite-X branded flash disk of sizes not to exceed 128GB.  I also DO NOT use the Windows Format utility that ships with any version of Windows.  My experience using that format tool corrupts the cards.  Use the GUI Format Tool from Ridgecrop Consultants or use the HPUSBDisk format tool.

**Comment by rsr427** [comment]
The latest firmware was installed successfully, that was simple.  I use SD Card Formatter (as recommended to install the Miyoo upgrade to the PK V90, that also was successful).  I will try the GUI tool, but I generally don't use the Windows tool.

I purchased two V90s and two Miyoo Minis for friends I'm seeing in June and wanted to update the FWs and clean up the rom lists for them ahead of time.  The V90's were easy to do.  The Minis have been frustrating.  Lots of potential though.

Thank you for taking the time to respond. And thankfully these are popular and the community is fervent. -Ryan

**Comment by rsr427** [comment]
Great news: solved for me!  I could not get GUI format tool to work, but the HPUSBDisk did the trick.  The formatting process took about twice as long as the other tools I'd tried, but when I tried it in the Mini it worked without much hassle.  The upgrade itself worked pretty easily too.  

Highly recommend trying that HP tool to anyone having issues.  Thanks all.

**Comment by Olywa** [comment]
@mountaindrew52 If this issue is resolved for you it would be really great if you could set the status to closed and save the developer a little time in managing issues.
