### ISSUE TITLE
Is there any way to make the thumbnail wider in the detail view?

### ISSUE THREAD

**Issue by squallstar** [jimgraygit/Onion#198]
I was wondering if you know whether it's possible to make the thumbnail wider in the detail view (and of course have a thinner column for the title), see:

![MainUI_000](https://user-images.githubusercontent.com/574210/167666376-838e6e6b-353b-4d3f-ad21-588f3d8de15e.png)

**Comment by Olywa** [comment]
Hi there, this one was requested previously by others, it's defined in the miyoo firmware itself and not the (Onion) Operating System so is not something the OnionOS dev can easily change unfortunately. 

--
If you are satisfied with my response it would be great if you could close the issue yourself and save the developer a little time in managing issues.

**Comment by squallstar** [comment]
Thanks, I appreciate you taking time to respond on this.
