### ISSUE TITLE
Coleco/blueMSX - initial launch error screen loop

### ISSUE THREAD

**Issue by dezign999** [jimgraygit/Onion#20]
blueMSX will appear to be stuck on an error screen when running Coleco games stating you need to power the console down before inserting a cartridge. This error screen will remain no matter what games are launched. It’s simply showing a resumed save state that is misleading. Modifying the configs and restarting the game will exit this screen.

**Comment by bdiederichs** [comment]
Just installed Onion today and I also haver this issue with blueMSX

what modifications did you make to what config file(s) ?
