### ISSUE TITLE
Feature Request: Statistic End Screen after Game round better

### ISSUE THREAD

**Issue by MancusNemo** [jimgraygit/Onion#201]
Hello,

why not upgrade the Score Screen.
At the moment you see only Points/Scores and your Playtime. Not the Kills and Death and the won Medals.
Why do I get Medals when I don't see it in the Score table at the end of every Round?
Used ammo and Hitting ammo and as consequence calculated accuracy.  And what is with your Lolly Points or your Logosprays?
And do not forgot to think about the new Mods like Freezetag.

Can you do there anything?

**Comment by Olywa** [comment]
I would try to help but I'm honestly not sure what you are describing. 
Is this a specific game? 
How does it relate to Onion OS (do you mean the Play Activity app?)? 
Can you provide more context?

**Comment by kuhlmanryan** [comment]
> I would try to help but I'm honestly not sure what you are describing. Is this a specific game? How does it relate to Onion OS (do you mean the Play Activity app?)? Can you provide more context?

It read it and thought I was going crazy haha. It reads like English but sounds like gibberish. Probably a poor Google translate

**Comment by dwmccoy** [comment]
This Issue should be closed.  It's clearly about a particular set of game stats and nothing to do with Onion OS.

**Comment by Sichroteph** [comment]
Closing !
