### ISSUE TITLE
PS1 Games Playing in Fast Forward

### ISSUE THREAD

**Issue by abelogan** [jimgraygit/Onion#206]
I just got my Miyoo Mini yesterday and spent the day installing the latest version of OnionOS and adding my roms.  Everything was going well until I went to play PS1 games.  They're all running like they're in fast forward!  I haven't messed with any of the Retroarch settings to cause this.  How can I play my PS1 games at regular speed?

**Comment by Sichroteph** [comment]
check if the audio fix in the miyoo settings in not set to ON
