### ISSUE TITLE
PSX emulator not working (v3.10)

### ISSUE THREAD

**Issue by srcamarda** [jimgraygit/Onion#211]
PSX's game list will not show .bin files on Onion v3.10.2. It's missing this extension on the config/extlist.

Also, even after including .bin in the file, games with this format are not starting. 
They get stuck on the "Loading" screen (from system, not game).

As far as I know this worked on v3.9, as most of my PSX games are in this format and were running fine. 
Install is fresh, just updated to the new firmware and Onion versions.

**Update:** it seems that the PSX emulator is not working at all for me. None of my games is running. I don't have many, and they are all .img or .bin. I will try to find some with .chd or .pbp or convert to test.

**Update 2:** Tested another games and formats, and it is indeed not working.

**Comment by Olywa** [comment]
@srcamarda Hi there, I am running 3.10.2 and have tested a handful of PSX games and all are working here. 
My roms are a combination of chd and pbp. 

Can you confirm you did a 'fresh installation'? and copied back your BIOS files?
...and you are also on the very latest miyoo fw ?

Could you try opening the onion installer from the apps, uninstall PSX and reinstall it.

**Comment by srcamarda** [comment]
@Olywa Hi, thanks for the response. Yes, I did a fresh install. Only copied roms, saves and bios back after installing Onion. The firmware is the latest (20220419).

I have SCPH1000, 1001, 5000, 5500, 5501, 5502, 5552 and 7003 on BIOS folder. Should they be in some other folder or subfolder?

Also tryed removing from Onion installer and enabling again, but with same results.

**Comment by Olywa** [comment]
@srcamarda Thanks for the update, it's very strange as I've not seen this issue for anyone else so far and as I say, it's working for me. I'm fairly certain it's something particular to your setup...

The root BIOS folder is the correct folder and the PSX bios do not require a subfolder. 
Can you confirm your bios files are named exactly as per the OnionOS Wiki (incl. lowercase)... 
[https://github.com/jimgraygit/Onion/wiki/2.-Onion-Emulators-&-Ports]

One other thought, could you temporarily remove your saves and states for PSX if you have any (move them off somewhere safe). As these things changed location in 3.10.x (now located in root/Saves). It's unlikely this I feel but worth ruling out.

Failing this, can I suggest join the discord. It's a very active & friendly community and we can help you work through it there. [https://discord.com/channels/529983248114122762/891336865540620338]

**Comment by srcamarda** [comment]
Hi @Olywa, in the end it was indeed a problem with the BIOS. 

I got it to work using just scph7502.bin (which I switched to psxonpsp660.bin later, and worked as well). Perhaps having multiple BIOS files was the problem, or one of them was corrupt.

I'm closing the issue. Thanks for the help.

**Comment by Olywa** [comment]
@srcamarda awesome, glad we got there in the end. One of them was probably an incorrect MD5 match (I have multiple bios on mine), it may be useful if you plan to play games from different regions. Thanks for coming back to update and close the ticket.
