### ISSUE TITLE
Favorites list randomly wiped out

### ISSUE THREAD

**Issue by polaris911** [jimgraygit/Onion#212]
Seems to happen after playing Neo Geo games. Happened twice for me.

**Comment by Olywa** [comment]
Hi there, can you provide a little more detail and context please.
Firmware & onion version ?
How does this happen (only after reboot or just when exiting a game and back to the Favourites)?

**Comment by polaris911** [comment]
It happened on 3.8.3 and 3.8.0. I noticed after rebooting that the only thing in my favorites list was "Neo Geo". The last game I was playing was Metal Slug X on Neo Geo both times it happened. For some reason Neo Geo games don't show the title in Favorites, it just says "Neo Geo". All my other favorites were gone. 

I have been trying to reproduce it too and can't seem to make it happen again.

**Comment by Olywa** [comment]
@polaris911 Hi again, Thanks for updating. Maybe it was a problem with an earlier release, it's always best to try the latest version if you are experiencing issues (and to keep a backup of your all roms/bios/saves/states/favourites before upgrading.
V3.10.2 beta is out now and has some great new features.

If you are satisfied the issues no longer occurs can I ask you to set the status to CLOSED as this saves the developer a little time in reading and managing issues.
