### ISSUE TITLE
Color setting not saving on 3.9.2

### ISSUE THREAD

**Issue by khromov** [jimgraygit/Onion#213]
Whever I go to Settings > Color and then change any of the Hue/Saturation/Contrast values, it does not get applied after reboot and the settings get reset to 10/20. When exiting the Color menu you are instructed to "Reboot to apply changes". Turning the system off through either the power button or the "Power off" option under Settings does not retain the value on the next startup.

**Comment by Olywa** [comment]
This issue persists on 3.10.2.

**Comment by Olywa** [comment]
Still present in 3.10.4 - Both Colour and Brightness settings do not persist after reboot. 
A workaround for brightness only  (that someone on the discord discovered) is to use the shortcut key to adjust brightness.
Changes made this way will be maintained after reboot.  These shortcuts are on the wiki:

```
The brightness shortcuts are the Miyoo defaults :
Select + Start + R2 : Brightness up
Select + Start + L2 : Brightness down

It is possible to change them so they don't interfere with your game by using instead : "Menu + Up/Down".
To do this, simply press Start+Select+A+B to switch the logic. (It will last after a restart)
```

**Comment by Olywa** [comment]
@khromov 
This appears to be resolved now with the 3.10.5 release, perhaps you can try?
Be aware, it is necessary to update the miyoo firmware to the latest release (0419), you can follow the instructions for this on the OnionOS download page.

**Comment by Olywa** [comment]
@Sichroteph I think this one should be closed now ;)

**Comment by Olywa** [comment]
Hi @khromov would you mind setting the status to CLOSED please as it saves the developer a little time in managing issues.
Thanks.

**Comment by khromov** [comment]
Thanks for following up @Olywa !
