### ISSUE TITLE
Move screenshots to new saves folder

### ISSUE THREAD

**Issue by andrewkendall** [jimgraygit/Onion#216]
The new saves folder in V3.10.X is an excellent change and greatly improves the upgrade process.

Would it also be worth moving the screenshots directory to saves too?

**Comment by Olywa** [comment]
I don't use screenshots myself but think this is a nice suggestion for those who do.

**Comment by Sichroteph** [comment]
you mean the onion launcher screenshots ? it is indeed in the to do list.

**Comment by Sichroteph** [comment]
closing it because it is not an issue
