### ISSUE TITLE
FEATURE REQUEST: low battery options

### ISSUE THREAD

**Issue by Yahcob** [jimgraygit/Onion#217]
Would love some options to edit what happens when the battery is low.
The ability to turn on/off the rumble? 
Edit the frequency/intensity of the rumble? 
The ability to stop the return to menu when low? 
The ability to choose which battery percentage it triggers at?
The ability to toggle the low battery icon on/off? 
Which corner to have it appear in? 

Would love some options to tweak what happens at low battery, the rumble can be distracting. Plus the save and return home on critical battery, losses several minutes of play time whilst waiting for the battery to die.

I know I've mentioned this before
But how it was in v3 was perfect
Would love some tweakable options

Thanks
Yahcob

**Comment by Sichroteph** [comment]
We can discuss it, however it seems risky to continue to use your mini under 4%
At any time it can turn off and if you were making a save at this moment, corrupt it.
Finally, letting your battery deplete this much is bad for it.
If you want the rumble back, I can activate it in the options. However, in the V2 models the vibration is very strong and distracting.

**Comment by Sichroteph** [comment]
It indeed no longer vibrate. Still a safe game exit at 4%. 
Has been added a battery percentage value when you turn of the console while in game, that should help you tracking it.
