### ISSUE TITLE
Sound doesn't work if directly booting into RetroArch with Onion Launcher

### ISSUE THREAD

**Issue by no008080** [jimgraygit/Onion#220]
I'm a guy who likes to boot directly into RetroArch, so i followed your instructions under **Onion for advanced users** (which is also the way to reproduce this bug):

1. Add the file "RADirectLaunch.enable" to the .tmp_update folder.
2. Activate Onion Launcher, then start a game of your choice. Next time you boot up the device, you're greeted with the RetroArch menu.

However, when starting a game from RetroArch's menu (Playlist, Histoy, Load Content) after booting **directly** into it, the sound won't work and the framerate seems to be unlocked (game is running too fast). This happens on all systems. 

This mimics the behavior of when the **Audio Fix** is turned **off**. 

I also tried on all possible drivers with VSync on (which fixes the framerate, naturally, but not the audio). 
If i load a game with RetroArch after starting it **manually from the App Menu**, everything works as intended. 

My guess is, that when booting into RetroArch, the device somehow circumvents starting the new Audio Driver, which results in the aforementioned behavior.

Is there another way to boot into RetroArch, or do I have to wait for a fix?

Firmware: 20220419
OnionOS: v3.10.2

**Comment by Sichroteph** [comment]
Thanks for this, I will look at it and leave you informed.

**Comment by Sichroteph** [comment]
It is fixed for the next version release (3.10.6)
