### ISSUE TITLE
Volume wheel won't mute the device

### ISSUE THREAD

**Issue by daneom** [jimgraygit/Onion#221]
If I spin the wheel to zero, the device still emits sound.

Could it be hardware issue?

**Comment by Olywa** [comment]
This does sound like a hardware issue, do you have the original SD card & set up? 
You could try with the Miyoo Stock OS to rule out Onion.

**Comment by Olywa** [comment]
Hi @daneom would you mind setting the status to CLOSED please as it saves the developer a little time in managing issues.
Thanks.

**Comment by Sichroteph** [comment]
Closing now, thanks all.

**Comment by daneom** [comment]
Thanks for the inputs, folks!
