### ISSUE TITLE
Multiple Rapp problem

### ISSUE THREAD

**Issue by Wapp92** [jimgraygit/Onion#224]
I did a upgrade and clean install format and all. Actually 2 install because i thought maybe something went wrong the first time, so yeah 2 install on a clean SD.

X68000 
launch.sh needs to be change or the roms doesn't launch, also i had to create X68000 folder inside of Roms
HOME=/mnt/SDCARD/RetroArch/ $progdir/../../RetroArch/retroarch -v -L $progdir/../../RetroArch/.retroarch/cores/px68k_libretro.so "$1"

Xrick 
doesnt work, had to use the old files with the old PATH (also i don't see any data files for the game, even thought the release say it s included)
HOME=/mnt/SDCARD/RetroArch/ $progdir/../../RetroArch/retroarch -v -L $progdir/xrick_libretro.so "$1"

EDUKE3D
Had to create the folder EDUKE inside Roms, i put my DUKE3D.GRP and DUKE.RTS inside that folder, launch it and it exit immedialtly
log say it didn't find DUKE3D.GRP... 

Ps. Just try to put my files into the Rednukem, and the game launch. It should be explain somewhere. Or did i miss it.

**Comment by dwmccoy** [comment]
I can confirm Xrick core was provided in the installation but the data.zip file is not included, nor is there a /Roms/Xrick folder created during the installation.

The Eduke3D launch script is actually expecting the DUKE3D.GRP and DUKE.RTS to be in the /RApp/EDUKE folder and the config.json file is looking for those files in the /Roms/EDUKE folder.  If you edit the config.json file and set the "rompath" to equal "rompath":"../../RApp/eduke", the game will launch and work.

I did not test X68000 as I have no rom sets for that system.

**Comment by Wapp92** [comment]
Thanks, it works now. 

The pathing is correct for Rednukem and Nblood but not for eduke3d.

**Comment by Sichroteph** [comment]
Is this something fixed in the current Onion version or is a change still needed for the next revisions ? From what I can see, all 4 current config.json file refers to the Roms path, which is good to avoid confusion to the user.

**Comment by Sichroteph** [comment]
Closing, don't hesitate to answer here if there are still oath issues I'll fix them.
