### ISSUE TITLE
Nblood

### ISSUE THREAD

**Issue by Wapp92** [jimgraygit/Onion#225]
The character is clipping through the floor. It s like he is too small to jump from the tomb in E1M1.
Anyone have that issue?

**Comment by Sichroteph** [comment]
I forward this to the porting dev.

**Comment by Sichroteph** [comment]
Are you by any chance pressing L2 by accident ?

**Comment by Wapp92** [comment]
I don't thing it has anything to do with the L2 button, i didn't reconfigure any key. Just launch the game. I just made a video, sry for the shitty quality, you can see when the game launch E1M1 the character is clipping, then i am pressing the crouching button and finally trying to jump. 

https://user-images.githubusercontent.com/34622698/169201213-4a8018db-1228-44fd-87fc-42f6d79379e9.mov

**Comment by Wapp92** [comment]
At least i am sure it s on my end, since you don t have the same problem. It's the GOG version. I deleted two cfg files, didn't help. Here is a screenshot of the NBLOOD folder on the miyoo:

![Nblood_Folder](https://user-images.githubusercontent.com/34622698/169287717-d0b5f88d-9dc5-42c7-9dde-68587c8d0a72.png)

**Comment by StupidHoroscope** [comment]
So this is Blood: Fresh Supply? I'll have a look into it.

**Comment by Wapp92** [comment]
Yes, i thought it was the same. I am curious to know if you got the same problem with that version.

**Comment by Sichroteph** [comment]
Can I close this issue now ?
