### ISSUE TITLE
Constant reboot and no sleep after a few days of usage 

### ISSUE THREAD

**Issue by kirqe** [jimgraygit/Onion#232]
With the latest update I'm having the following problem - after a few days of usage, the power button "stops" working. 

I can turn off the device by holding the power button and then confirming that it needs to be turned off. 
But it doesn't go to sleep and constantly reloads. 

Reinstalling the onion works for a few days.

I believe it somehow related to the dos and spectrum emulators because they lag a lot - sometimes you cant go to the main menu without entering the retroarch menu

demo https://gofile.io/d/tvJbIC

**Comment by Olywa** [comment]
Yeah this seem off, no such issue here and first time I'm seeing this. As you say, it _could_ be something pertaining to the emulators you mentioned but they are just RA cores so I'd be surprised. Out of interest do you have another SD card your could try with (are you using the one that came with the device)?

**Comment by kirqe** [comment]
This is a new sd card. After reboot (long press power button and confirm Power off) everything works fine.
But when I press the power button - it reloads again

**Comment by Sichroteph** [comment]
So you mean the bug persist after a reboot ?
Can you zip me the tmp_update folder (without the screenshots to win some space) so I can debug it ?

**Comment by kirqe** [comment]
Yes. 
- Turn off the device
- Boot - works normal
- Long Press the power button - no confirmation dialog - reload loop starts
- Or press it once - no message about saving state - reload loop starts

sorry for the shaky video. included the zip with files there https://gofile.io/d/0dqd55

When I was copying the whole folder from the sd card to a local folder, there was a message "arrowRight.png already exists..." but the folder I was copying to was a newly created one. So I manually copied the files

**Comment by Sichroteph** [comment]
what happen if you simply tap the power button instead of a long press like you did at 26s ?

**Comment by kirqe** [comment]
> what happens
The reload loop starts and there's no message about saving state like it used to be in the first couple days when everything was normal.

On the video I first did a long press and after that multiple single presses.

**Comment by Sichroteph** [comment]
the tmpupdate folder you provided is strange. There are no png file in it and the last game you seems to have played is picross 2, same as stock.

**Comment by Sichroteph** [comment]
can you provide me again you real tmp_folder, with everything but the rom screenshots ?

**Comment by kirqe** [comment]
I've just tested again and noticed that it reloads depending on how many times I press the power button(short press)

1 press - one reload
2 presses - two reloads
etc

[Archive.zip](https://github.com/jimgraygit/Onion/files/8716134/Archive.zip)

**Comment by Sichroteph** [comment]
There are indeed a lot of broken files in your folder.
Missing pngs, corrupted files .. Even files that my binaries barely touches like the charging pngs.
If you trust your SD card, then I would say your sd card reader is faulty.
 
In the same time, in order for you to "fix" temporally this problem, you can unzip this file in the .tmp_update folder :
[tmp_update.zip](https://github.com/jimgraygit/Onion/files/8716229/tmp_update.zip)

Now since there are not other case like this I will close this issue but will stay aware of any new cases that might appear.

**Comment by kirqe** [comment]
I think the problem was in macos indexing

`dot_clean -m /Volumes/MIYOO` used to show some permission error related to `.spotlight-v100` that used to be on my sd card and couldn't be deleted
I added `.metadata_never_index` to the root of the sd card and managed to delete `.spotlight-v100` 

Still have to run `dot_clean` but there's no permission error and boot problems so far.
This is how it currently looks

<img width="224" alt="Screenshot 2022-05-22 at 14 51 54" src="https://user-images.githubusercontent.com/5272402/169693845-e0d407aa-dd7c-484d-8825-6c54987305a4.png">
