### ISSUE TITLE
Atari 800 does not load games.

### ISSUE THREAD

**Issue by jakubboruch** [jimgraygit/Onion#243]
After updating Onion OS from 3.7.1 to 3.10.5, Atari 800 emulator stopped working.
Only a blue screen is displayed with the message:
"Sorry this program needs a real ATARI / OS"

**My BIOS files located in /BIOS folder:**

MD5 hash of ATARIBAS.ROM:
0bac0c6a50104045d902df4503a4c30b

MD5 hash of ATARIOSA.ROM:
eb1f32f5d9f382db1bbfb8d7f9cb343a

MD5 hash of ATARIOSB.ROM:
a3e8d617c95d08031fe1b20d541434b2

MD5 hash of ATARIXL.ROM:
06daac977823773a3eea3422fd26a703

MD5 hash of 5200.ROM:
281f20ea4320404ec820fb7ec0693b38

**Games that I tested and are not working:**
MD5 hash of RiverRaid.zip:
2660aabd6ccce314bb9ce34cd7fdc9e3

MD5 hash of Action Biker (19xx)(Mastertronic).zip:
ca4b22c961977488856655faadb62f69

**Comment by dwmccoy** [comment]
> After updating Onion OS from 3.7.1 to 3.10.5, Atari 800 emulator stopped working. Only a blue screen is displayed with the message: "Sorry this program needs a real ATARI / OS"
> 
> **My BIOS files located in /BIOS folder:**
> 
> MD5 hash of ATARIBAS.ROM: 0bac0c6a50104045d902df4503a4c30b
> 
> MD5 hash of ATARIOSA.ROM: eb1f32f5d9f382db1bbfb8d7f9cb343a
> 
> MD5 hash of ATARIOSB.ROM: a3e8d617c95d08031fe1b20d541434b2
> 
> MD5 hash of ATARIXL.ROM: 06daac977823773a3eea3422fd26a703
> 
> MD5 hash of 5200.ROM: 281f20ea4320404ec820fb7ec0693b38
> 
> **Games that I tested and are not working:** MD5 hash of RiverRaid.zip: 2660aabd6ccce314bb9ce34cd7fdc9e3
> 
> MD5 hash of Action Biker (19xx)(Mastertronic).zip: ca4b22c961977488856655faadb62f69

Please delete the .atari800.cfg file located in /RetroArch  Once you relaunch the Atari800 Emulator it will recreate the .atari800.cfg file so that it can find the correct BIOS folder for your SYSTEM ROMS

**Comment by dwmccoy** [comment]
If this issue was resolved, please close this.  Thanks.
