### ISSUE TITLE
I think Miyoo might have have just shared their source code for the mini

### ISSUE THREAD

**Issue by sheepo99** [jimgraygit/Onion#244]
![Screenshot_2022-05-19_22-46-46](https://user-images.githubusercontent.com/3621746/169406044-b25c19a6-8010-4f09-b41d-451227394c50.png)

So I decided to try asking Miyoo for their firmware's unreleased source via aliexpress chat, and to my surprise, they actually replied! They sent me a link to a google folder to what appears to be an SDK. Is this useful to you folks? I'm not a programmer myself, so can any of you confirm this is the real deal?

https://drive.google.com/drive/folders/1ufEUQcuRELHKzsiyPRSgJMAx6E5kM_ZW

**Comment by dwmccoy** [comment]
This would not be an issue with Onion OS.  Can you close this and move it over to discussions?

**Comment by sheepo99** [comment]
Got it.
