### ISSUE TITLE
Amiga sel icon

### ISSUE THREAD

**Issue by BlackoArt** [jimgraygit/Onion#247]
![amiga_sel](https://user-images.githubusercontent.com/12528490/169500643-065c4654-b306-4c16-88cd-e12740d9886e.png)
![amiga_sel2](https://user-images.githubusercontent.com/12528490/169500667-70062525-7afe-4f62-8417-66ccc8a9c565.png)
Some buddy made it.
And next release I hope the jsons' iconsel become correct in every emu. Thanks.
Add Menu + ← / →: Change state in hotkey list.

**Comment by dwmccoy** [comment]
This is not an issue or bug with Onion OS.  Please close this and move it to discussion area.  Thanks.
