### ISSUE TITLE
[bug] SG1000 is not detecting roms

### ISSUE THREAD

**Issue by ac3nl** [jimgraygit/Onion#253]
I did a fresh install of 3.10.5

Roms are starting, if run from retroarch directly.
I have put the roms in the correct dir, i double checked. This dir was created by Onion self.

Update: seems like pico drive is not playing the SG-1000 roms, but gearsystem is. After fideling with the launch.sh it works now.
Also removing a bit of code from extlist, the roms are found now

**Comment by Sichroteph** [comment]
could you share your modified file so I can add them in the next update ?

**Comment by ac3nl** [comment]
[SEGASGONE.zip](https://github.com/jimgraygit/Onion/files/8749706/SEGASGONE.zip)

of course, addad for you

**Comment by Sichroteph** [comment]
Thanks !
