### ISSUE TITLE
Add VIDEO (multiformats) formats support to a new media player app (complementary to "MP3 Player App" request from fggause)

### ISSUE THREAD

**Issue by scarlet-RS-97** [jimgraygit/Onion#26]
Could it be possible to add a simple VIDEO (multiformats) player as an app, with a lockout that disabled the keys and turned off the screen but kept playing (as requested by fggause for its "MP3 Player App" request) ?

Many thanks for your great job

**Comment by jimgraygit** [comment]
We are looking into support for other forms of media, but its not on our immediate radar
