### ISSUE TITLE
[request] app/shortcut to re-open The Onion Launcher

### ISSUE THREAD

**Issue by ghackett** [jimgraygit/Onion#260]
I love the onion launcher, it's one of my favorite parts of onionOS. Currently, after exiting the onion launcher (to browse for a new game to play) the only way to get back to it is to restart the device (afaik). I would love an app entry/shortcut that would drop me back into the onion launcher's ui, to use when I'm done with the new game and want to go back to an old one.

Onion 3.10.5

**Comment by Sichroteph** [comment]
I agree. On the to do list. Thanks for your kind words.

**Comment by Sichroteph** [comment]
Will be on tonight release (3.10.6)

**Comment by ghackett** [comment]
You're my favorite person on the internet, thank you for all the great work!
