### ISSUE TITLE
[bug] Scummvm core is missing SOUNDFONT

### ISSUE THREAD

**Issue by ac3nl** [jimgraygit/Onion#262]
This is needed to play "Day of The Tentacle""

sorry this one is out of my comfort zone to fix

**Comment by Sichroteph** [comment]
Are you on the last onion version ?

**Comment by ac3nl** [comment]
I am on 3.10.6 . 
soundfont is needed for some games.
games who do not need it,, do work

**Comment by Sichroteph** [comment]
There seems to be a roundabout way to change the sound driver:
- Start a game that actually works
- Go to the ScummVM menu
- Select 'Return to launcher'
- Select 'Global Options'
- Go to the 'Audio' tab
- Change 'Preferred device' to 'AdLib emulator'
- Select 'OK'
- Select 'Quit'
- Relaunch ScummVM

**Comment by ac3nl** [comment]
Cool, that actually worked.
Is there a way, that this setting could be made default in the next onion update?

**Comment by Sichroteph** [comment]
Sure 😊

**Comment by ac3nl** [comment]
Cool, this one can be closed!

**Comment by Sichroteph** [comment]
The thing is, you should have the good audio device by default. Did you copy over files in the BIOS folder by any chance ? Just trying to understand.

**Comment by ac3nl** [comment]
I have all the biosfiles needed.

For scummVm you can add al lot of things, bur they are not all
Needed.
With the adjustment suggested the matter was solved.
