### ISSUE TITLE
MAME2003Plus resume with no audio. And sometimes, to quit from mame rom, i need to press menu button twice or more.

### ISSUE THREAD

**Issue by okletsgobaby** [jimgraygit/Onion#264]
im running latest onion 3.10.6, when i play arcade (mame2003+) sometime, when i press the menu button, it didnt do anything. Sometimes i needed to press it twice to go back to main menu and sometimes it stuck and i had to unplug the battery to power it off.
And when it can go back to main menu, when i choose the same rom again, it did resume but with no ad=udio at all. 
This only happen in 3.10.5 and 3.10.6, because when i was at 3.9.2 everythings fine. Im trying the latest onion just to try the RTC time adjuster.

**Comment by Olywa** [comment]
I think if you press the menu button too quickly after resuming into a game the emulator & launcher have not had time to fully initialise so the key press is not registered. If you wait a second (for any of the OSD text notification to finish and disappear) then the menu button should work ok?

The no audio in mame2003+ after resuming had been an issue for a while (before 3.10) and is known but on 3.10.6 for me it seems resolved (I have just tried a handful of random games, rebooting each time and could not replicate - there was sound each time). 

Maybe this is game specific, can you give some examples where you don't have sound and I can test those games?
If you have no audio (and don't mind losing progress, which may not be such an issue for Arcade games) a workaround would be to go into the retroarch menu (Menu+Select) and choose 'restart'.

**Comment by okletsgobaby** [comment]
thanks for your reply, i press the menu button while in game for at least 5 minutes (playing xmen) and this is happened not only in xmen but other roms too like captain commando, the avenger, battletoads etc. I believe it isnt game specific cause in onion 3.9.2 everything works perfectly fine, even the resuming problem doesnt exist in 3.9.2.
Anyway, is the rtc time in 3.10.6 gonna work if i copypaste it into 3.9.2? Cause so far, the best onion version that works for me is 3.9.2 (I only play gb, gba, gbc, gg, md, nes, snes and mame only).

Once again, Thanks a lot for your quick reply.. Im sorry if my english is bad..

**Comment by ac3nl** [comment]
In mame 2003+ the menu doesn't work UNTILL you press menu + Start first.
The retroarch menu opens, and THEN you can press menu to exit
