### ISSUE TITLE
Problems with Audio

### ISSUE THREAD

**Issue by thytetgc** [jimgraygit/Onion#265]
Everything works fine, but no audio.

After opening the file: .tmp_update/updater

_I commented out line 7_
`#/mnt/SDCARD/miyoo/app/audioserver &`

_I changed line 124_
`LD_PRELOAD="/mnt/SDCARD/miyoo/lib/libpadsp.so" ./MainUI`
for
`./MainUI`

After that, everything went back to working as before.

> OBS: I use ra32.ss to have the original save/load state menu

**Comment by Sichroteph** [comment]
If you modify the system, please don't come like it is an issue
