### ISSUE TITLE
[REQUEST] Long Game Titles

### ISSUE THREAD

**Issue by ndplymale** [jimgraygit/Onion#266]
Hey Onion team! 

Loving the updates that we've been getting lately. I'm not sure if it's been mentioned before but I've noticed that my games that have long titles will get cut off when browsing my games. 

I don't know if it's possible, but if the title is above a certain character count, can we have it do marquee-style scrolling for better readability?

**Comment by ac3nl** [comment]
Pushing dpad to the right gives a little more fileinfo, but still not enough.
Certain no-intro collections do have very long filenames…

**Comment by Sichroteph** [comment]
Not possible for now, but you can open a ticket to miyoo with this request, or try to reduce the title fonts.
