### ISSUE TITLE
Add AUDIOBOOKS (MP3 + M4A) support as an app

### ISSUE THREAD

**Issue by scarlet-RS-97** [jimgraygit/Onion#27]
Could it be possible to add an AUDIOBOOKS (MP3 + M4A) player as an app?

Functionalities:
 - One folder per audiobook because 1 book = 1 or n files
   File structure \AUDIOBOOK\BOOK1\*, AUDIOBOOK\BOOK2\*)
        Example of file structure:
        \AUDIOBOOK\BOOK1\position_file (txt? Json?)
        \AUDIOBOOK\BOOK1\chapter_001.mp3
        \AUDIOBOOK\BOOK1\chapter_002.mp3
        \AUDIOBOOK\BOOK1\chapter_003.mp3 <- files are read by order (chapter_001.mp3 then chapter_002.mp3, etc.)
        \AUDIOBOOK\BOOK2\position_file (txt? Json?)
        \AUDIOBOOK\BOOK2\one_file_audiobook.mp3
        \AUDIOBOOK\BOOK3\position_file (txt? Json?)
        \AUDIOBOOK\BOOK3\chapter_1.m4a
        \AUDIOBOOK\BOOK3\chapter_2.m4a

        The list of book for this example is (the book name is the folder):
        BOOK1
        BOOK2
        BOOK3

 - Sync the last-reached location on start application (one position kept per book: cf. “position_file” above)
 - 10 seconds forward button (R? or right cross pad?)
 - 1 minutes forward button (R2?)
 - 10 seconds backward button (L? or left cross pad?)
 - 1 minutes backward button (L2?)
 - Play/pause button
 - "lockout that disabled the keys and turned off the screen but kept playing" (like requested by fggause for its "MP3 Player App" request)

Many thanks for your great job

**Comment by jimgraygit** [comment]
We are looking into support for other forms of media, but its not on our immediate radar
