### ISSUE TITLE
Black screen after fresh install

### ISSUE THREAD

**Issue by btrsco** [jimgraygit/Onion#272]
Not sure what I've done wrong here.

I tried updating to v3.10.6 following the steps in the FAQ. But this resulted in being stuck at a black screen once the initial setup (installing core, emulators and apps) was over. Once the device shutdown, I turned it back on, once it gets past the boot logo and onion os logo, it just hangs at a black screen for minutes, with no changes. If I hit the power button I see the a shutting down message and it turns off fine.

I decided to try formatting and installing from a fresh install and I had the same experience. Any ideas?

**Comment by dwmccoy** [comment]
> Not sure what I've done wrong here.
> 
> I tried updating to v3.10.6 following the steps in the FAQ. But this resulted in being stuck at a black screen once the initial setup (installing core, emulators and apps) was over. Once the device shutdown, I turned it back on, once it gets past the boot logo and onion os logo, it just hangs at a black screen for minutes, with no changes. If I hit the power button I see the a shutting down message and it turns off fine.
> 
> I decided to try formatting and installing from a fresh install and I had the same experience. Any ideas?

Please update the firmware of your device if you haven't done so already.  It is required for Onion OS 3.10.x.  follow the guide posted here ->[https://user-images.githubusercontent.com/16885275/168298357-23a5b371-ed51-4c60-898b-1caee355fb27.png](url)

**Comment by Olywa** [comment]
@dwmccoy that link doesn't seem to be working (at least from me) although it looks correct. Trying again:

https://user-images.githubusercontent.com/16885275/168298357-23a5b371-ed51-4c60-898b-1caee355fb27.png

**Comment by btrsco** [comment]
> It's very clear there that you MUST upgrade your firmware for Onion.

No worries, just needed some help on this. I'll try this later tonight. I guess skipped that part of the patch notes but was still using your official documentation for the steps to update, sorry for asking I guess.

**Comment by Olywa** [comment]
@btrsco Thanks for closing. It's no problem to ask questions but please be aware the issues tab is for reporting genuine defects/bugs with OnionOS. 
There is a 'discussions' tab at the top for questions (and discussion) and a lot of documentation is already available (on the download page and in the Wiki pages) that will answer most things for you.
