### ISSUE TITLE
Crocods fails to load zipped dsk media

### ISSUE THREAD

**Issue by Noldor73** [jimgraygit/Onion#274]
When I try to use amstrad cpc roms in zipped dsk format the emulator fails to load the internal dsk. If I try from the crocods menu to read the media I get an disk icon error.

**Comment by dwmccoy** [comment]
I can confirm that if I have a DSK file that was zipped, it will not work with the emulator.  If I unzip the same DSK file and open the DSK file, the emulator opens the disk and works fine.

**Comment by Olywa** [comment]
Looking at the online core documentation (https://docs.libretro.com/library/crocods/), and also the info file for the RA core in the OnionOS 'Cores' folder, it would appear that neither zip or 7z are supported and only "dsk|sna|kcr".

@Sichroteph This seems like an error in the config.json for the CPC emulator and Zip/7z should be removed.

**Comment by Sichroteph** [comment]
The new extlist will be in the next version :
"extlist":"sna|SNA|DSK|dsk|kcr|KCR"

The wiki is also changed. Thanks for your feedback.
