### ISSUE TITLE
No Audio for GBA, SFC, FC and MS emulators

### ISSUE THREAD

**Issue by Mennez** [jimgraygit/Onion#276]
I've installed the Onion system successfully and added ROM's and emulators etc. I did this twice now (again with a clean install), to make sure I didn't skip any step the first time.

Everything works perfectly fine. Only thing is that I do not have audio in the GBA, SFC, FC, MS games. The PS, MD, GB games do have audio however.

Any ideas what this issue could be? I really have no idea and can't find anything about in on the internet.

Also it seems that the PLAY ACTIVITY app does not work (I do not see anything here after I played a game for a while). And the battery indicator seems not to be updated when playing on the device for a while.

I am running v.3.10.6 of the Onion OS.
Model number: MY283.

**Comment by ac3nl** [comment]
Did you update to the Miyoo april firmware first?

**Comment by Mennez** [comment]
Yes I did update to the latest Milo firmware from there website. Where is this audio fix setting located? When I go to the settings on the device I only see:

* Power off
* Brightness
* Color
* Language
* Key Mapping
* BGM Volume
* Device Info
* Hardware Test

Also what should the play activity app do? It is always empty on my device...

**Comment by Mennez** [comment]
The original SD card has the onion image now. So I do not have the original files. I was thinking of some driver which is missing maybe? But really don't know why, because I did just install onion via the official online manual...

**Comment by dwmccoy** [comment]
You can boot the Mini without the SDCARD inserted.  You could then go to the Settings Menu, Fixes, Turn OFF Audio Fix.  Power Down System.  Re-Insert SDCARD and test again.  I do not know if this would help any at all.  The Audio Fix setting has been removed from Onion OS as it was not intended for 3rd party OS's.

**Comment by ac3nl** [comment]
> The original SD card has the onion image now. So I do not have the original files. I was thinking of some driver which is missing maybe? But really don't know why, because I did just install onion via the official online manual...

This is not a good idea. The original sd card tends to get corrupt real fast. Buy another SD card, and install onion again.

**Comment by Olywa** [comment]
@Mennez I really cannot emphasise enough what @ac3nl has already said above...

The SD Card that comes with the mini (and the USB card reader too) is of VERY poor quality. It can (and will) corrupt/damage/lose files. We've seen users where these cards lasted only 10minutes before dying, some are lucky to get a few days. Really, please buy yourself a replacement known brand card (sandisk/samsung/kingston) from a reputable supplier.

**Comment by Sichroteph** [comment]
Your issue is very specific and in my knowledge unprecedented. It should be a bad hardware.

**Comment by Sichroteph** [comment]
> You can boot the Mini without the SDCARD inserted. You could then go to the Settings Menu, Fixes, Turn OFF Audio Fix. Power Down System. Re-Insert SDCARD and test again. I do not know if this would help any at all. The Audio Fix setting has been removed from Onion OS as it was not intended for 3rd party OS's.

This way of doing will break the audio and the battery percentages. The miyoo audio fix is not a good implementation and will confuse the user. I tried to remove it and did not realize that the user can still do it this way.
If you encounter any standalone app that has sound issues, I posted a way of fix it more easily and permanently than this fix on the FAQ :
https://github.com/jimgraygit/Onion/wiki/3.-FAQ-(Frequently-asked-questions)

**Comment by ac3nl** [comment]
> > You can boot the Mini without the SDCARD inserted. You could then go to the Settings Menu, Fixes, Turn OFF Audio Fix. Power Down System. Re-Insert SDCARD and test again. I do not know if this would help any at all. The Audio Fix setting has been removed from Onion OS as it was not intended for 3rd party OS's.
> 
> This way of doing will break the audio and the battery percentages. The miyoo audio fix is not a good implementation and will confuse the user. I tried to remove it and did not realize that the user can still do it this way. If you encounter any standalone app that has sound issues, I posted a way of fix it more easily and permanently than this fix on the FAQ : https://github.com/jimgraygit/Onion/wiki/3.-FAQ-(Frequently-asked-questions)

Can you explain the battery percentages?

**Comment by Sichroteph** [comment]
@Mennez could you try a new installation with another SD ?

**Comment by Mennez** [comment]
I will try it with a new good SD card then. Can I just do a fresh install without the original Miyoo Mini files? Since these will also be possibly corrupted with the old crappy stock SD?

**Comment by Olywa** [comment]
If you have already or will source your own Rom & Bios files (all easy to find with google) then you should not need anything from the Miyoo SD Card. The Roms included on the Miyoo Card are not really great anyway.

**Comment by Mennez** [comment]
@Sichroteph @Olywa I just did a clean install on my Samsung 64GB SD card. Same issues remains with a fresh clean install on this card. Still no sound for GBA, SFC, FC and MS emulators. Maybe some data is corrupt in my BIOS files? What (.bin) files are there for the sound effects for these emulators? Then I can replace / add these and check if the issue is fixed. This is the launch.sh script for example in the GBA emulator folder:

```
#!/bin/sh
echo $0 $*
progdir=`dirname "$0"`
homedir=`dirname "$1"`
./cpufreq.sh
cd $progdir
HOME=$homedir $progdir/ra32.ss -v -L $progdir/libmgba.so "$1"
```

**Comment by ac3nl** [comment]
Your problem doesn’t seem to be related to OnionOs.
Opening again wouldn’t solve your problem

i think it is hardware related

**Comment by Olywa** [comment]
Great to see you are using a new card but something is very wrong with the launch.sh you shared, it has lots of incorrect info and also explains why play activity does not work. Did you edit the launch.sh or copy it from your original (likely corrupt) card? Maybe you are using the USB reader that came with the Miyoo (also not good).

Did you redownload OnionOS 3.10.6 for this clean install?

**Comment by Mennez** [comment]
I did copy the emulator folder from the original card (since this has the images for the consoles etc.). Onion OS only provided 2 files for each emulator folder without a launch.sh. I am not using the USB reader provided with the Miyoo, but the SD adapter provided with the new CD card and connected this one directly to my iMac.

Yes, I did download OnionOS 3.10.6 and did a clean install on this new SD card.

**Comment by dwmccoy** [comment]
The only data that should be copied from the original card to a clean Onion OS installation would be the ROMS, BIOS, and Imgs.  I would not copy any other data over as it is provided by Onion OS.  My guess is that you have overwritten files required for Onion OS to work correctly.  I would suggest a clean install and ONLY move your ROMS over for starts.  Most systems work fine without any bios files and the Imgs are just eye candy.  If you do a clean install, and only move your ROMS over and it works, you can move the other files over afterward.

**Comment by Mennez** [comment]
Nice, that seems to be the problem! I deleted the folders from the GBA, SFC, FC and MS emulators, and installed them again with the onion launcher. Added the Miyoo Mini emulator icons to the folder and updated the config.json to link to the imaged I provided in the folder itself.
