### ISSUE TITLE
Battery % not accurate??

### ISSUE THREAD

**Issue by ac3nl** [jimgraygit/Onion#277]
I never fill my battery to 100%
Full gives 85%

Is it because i have a v2 battery?

**Comment by ac3nl** [comment]
Led turns blue means full right?

**Comment by Olywa** [comment]
Hi @ac3nl 
My V2 batteries reach 100%. Have you often fully depleted the battery while in use? Or frequently left it on charge overnight maybe? I'm no battery expert but I believe doing so is bad for Lipo batteries and can reduce capacity. 

There seems to be some common rules within communities that rely on these battery types in other devices (Drones, RC Cars, etc.) [V](https://www.thedronegirl.com/2015/02/07/lipo-battery/)

Either way, this seems more hardware related than an OnionOS issue. I'd suggested closing it as an issue and moving to the 'Discussions' tab.

**Comment by ghackett** [comment]
I could have sworn the Miyoo Mini battery was Li-ion not LiPo. Can anyone confirm?

**Comment by Olywa** [comment]
V1 batteries are definitely LI-ion (it's printed on the battery) but V2 I had read are LiPO but I can't say for certain & happy to be corrected. I wonder if the newer V2 batteries (with a printed sticker on them) give an indication.

**Comment by ghackett** [comment]
Good thinking, just checked that new retro game corps video of the transparent black and the new battery sticker also says Li-Ion
