### ISSUE TITLE
Fix mouse usage in UAE (Amiga + Amiga CD)

### ISSUE THREAD

**Issue by scarlet-RS-97** [jimgraygit/Onion#28]
It is not possible to use the mouse in Amiga emulators (uae distributions).
It is certainely due to the fact that uae uses analog pads to emulate mouse. But we don't have analog pad on the Miyo mini.
As the direction cross is visibly already mapped as joystick, we can perhaps imagine using using combination like start + direction cross.
But it seems not possible for the moment.

Many thanks in advance and again thank you for your great job.

**Comment by jimgraygit** [comment]
Hi Scarlet, please refer to the readme and wiki regarding experimental/expert mode cores: they are not supported by the team or developers and are there for testing and experimentation only. if you do find a solution, let us know and we will implement it, as this would bring us a step closer to having full support for this core
