### ISSUE TITLE
[BUG]ONS GAMES NO VOICE [No Fix audio option in setting menu] V3.10.6

### ISSUE THREAD

**Issue by graythen** [jimgraygit/Onion#283]
I download the latest firmware vision V3.10.6. When I run the ONScripter, games run without voice. This problem is easy to solve in the official firmware. Just turn off the Fix audio in the setting menu, the ONS games will run with normal voice. But I can't find the Fix audio option in setting menu of Onion firmware. How can this problem be solved?

**Comment by Sichroteph** [comment]
https://github.com/jimgraygit/Onion/wiki/3.-FAQ-(Frequently-asked-questions)
