### ISSUE TITLE
Console Year

### ISSUE THREAD

**Issue by Yahcob** [jimgraygit/Onion#284]
anyone know in the console selector how to change the titles?
or re add the years to have them in year order?
i quite liked that feature!

thanks again
Yahcob 

P.S. keep up the amazing work :D

**Comment by ac3nl** [comment]
You can change that yourself, just edit every config.json in the EMU map.
Only change the LABEL name, keep the rest intact.

**Comment by Yahcob** [comment]
that is EXACTLY what i wanted to hear! 
thank you!
