### ISSUE TITLE
FEATURE REQUEST: Suggestion for displaying images when browsing

### ISSUE THREAD

**Issue by senditron** [jimgraygit/Onion#287]
Hello, I just wanted to suggest / request a little upgrade on the browsing page (Showing the scrapped box art / screen caps etc).

Something with a side list and a larger area for the art to be displayed would be awesome!

Thank you so much Onion team, we love your work and we all apricate your efforts!

-S

Current:
https://ibb.co/WkgFXjS

Example upgrade:
https://ibb.co/1rFPqQ0

**Comment by Olywa** [comment]
I think Onion is not able to easily change what is already there from Miyo if terms of the page layouts beyond themes but what we have today is already not really too far from your request. 
I appreciate you were showing the 'gameinfo' screen but, are you on a recent (3.10.x) version, the main game list menu should look like this if you have added artwork...
![image](https://user-images.githubusercontent.com/98862735/170717057-9614915b-7f1b-4cf9-aa59-cbc970c3832a.png)

**Comment by Olywa** [comment]
Hi @senditron if the above helped and answered your question could I ask you to please change the issue status to CLOSED.

Many thanks.

**Comment by senditron** [comment]
Hi Thanks @Olywa yes it helped. The image is still pretty small though. I think a nice display of game art is something a lot of people really would love though.

Maybe there could be some options on how it is displayed? if it could be made bigger that would be great!

Just opinion and feedback however, understand it might not be a high priority.

Thanks again!

**Comment by Sichroteph** [comment]
Thanks for your feedback ! There are indeed some things in the main menu that are hard to change without referring to Miyoo directly. Closing now !
