### ISSUE TITLE
Miyoo MiniOnionOS ver 3.10.5 blank Screen

### ISSUE THREAD

**Issue by Toatspirate001** [jimgraygit/Onion#289]
Hi, 

I followed the installation of the Onion operating system Retro Game Corps Youtube channel and it installed to the point were I was reading the instructions on screen and adding the consoles. (I skipped adding any apps) When that was all completed the Miyoo Mini shut down and Ioaded all the required roms/ Bios and Retroarch files that I backed up from the old micro SD card. I put the card back in, turned it on and it has the Onion OS 3.10.5 title page then everything goes blank. When I press the power button it has the shutting down screen.

Is there a file I'm missing?

Thanks in advance

**Comment by ac3nl** [comment]
Did you use a new sd card, or the original miyoo sd card?

**Comment by Toatspirate001** [comment]
Regarding the firmware, I thought I did. I put the Disk Image File in the top directory of the original SD card and put it back in and placed the system on charge to install. The Miyoo went directly to the Neo Genesis style icon and I stupidly thought that it the firmware was already up to date. 
Regarding the SD cards, I used the original to try and update the firmware but a new 128g one that was formatted with Fat32 to install Onion.

**Comment by ac3nl** [comment]
Are you absolute sure you have a valid 128gb card. There are a lot of fake ones out there ...

**Comment by Toatspirate001** [comment]
I have a SanDisk 128g MicroSD card that I got from a reputable office store.

If I have to remove everything how do I remove the Onion firmware that has already been installed onto the Miyoo Mini?

**Comment by Toatspirate001** [comment]
I check the Miyoo Mini without the SD car (didn't know I could do that) and the system page says that I havn't updated the firmware.
Can I put in the original SD card (with the original files) in the Miyoo with the Disk Image File on it and try to update the firmware again or do I have to do something different because of installing Onion.

**Comment by Olywa** [comment]
Onion doesn't ever install anything on the Mini itself, it runs 100% from the SD Card only.

You _can_ use the original card to update the firmware but I would suggest there is more risk as the Miyoo cards are **very** prone to failure. You would be safer to use another card. Just be sure to backup all your games/bios/saves. 

Follow the guide that is linked at the top of the Onion download page for the fw 'update instructions' (but you do **not** need to remove the battery)

**Comment by Olywa** [comment]
@Toatspirate001 Please come back and comment once you are up and running and if all sorted, please change the status to CLOSED. 

Many Thanks
