### ISSUE TITLE
Disable hotkey menu+A = reset

### ISSUE THREAD

**Issue by sebboop** [jimgraygit/Onion#29]
It's not possible to use fast forward (menu+R2) on many games since if you hit A to mash text, this hotkey (menu+A) actives too and resets your game

**Comment by jimgraygit** [comment]
Hi sebboop, good call. Do you think "B" would work best or should we just drop that shortcut altogether and leave reset in the quick menu

**Comment by issac-temp** [comment]
Not that you're asking me, but I would personally prefer it dropped. I don't reset games often enough to need a shortcut like that. 
One option could be (if it is possible) to have a checkbox menu where some shortcuts can be enabled or disabled. Like if someone don't want to accidentally save or load their games, and only want fast forward, or something along those lines).

**Comment by goocy** [comment]
SD://RetroArch/retroarch.cfg:2639
set input_reset to "nul"
