### ISSUE TITLE
RICHIESTA FUNZIONE: Suggerimento per la visualizzazione di immagini dei giochi

### ISSUE THREAD

**Issue by luinchio** [jimgraygit/Onion#290]
come faccio a mettere immagine dei giochi? vorrei sapere come mettere immagini giochi ma devo creare delle cartelle ? mi potete far sapere come fare grazie 1000

**Comment by Olywa** [comment]
Hi there @luinchio, there is a 'discussions' tab above for questions, the 'issues' tab should only be used to raise genuine bugs or issues with OnionOS.

The Wiki (also on the ribbon above) answers lots of questions already and includes a ton of useful information. 
You will find a guide there on how to use Skraper to add images: https://github.com/jimgraygit/Onion/wiki/3.-FAQ-(Frequently-asked-questions)

Please can you change the status of this issue to CLOSED.

Thanks :)
