### ISSUE TITLE
[bug?] theme switcher doesn’t work any more…

### ISSUE THREAD

**Issue by ac3nl** [jimgraygit/Onion#292]
I just started scraping some boxart with skraper.

i did scrape
Game Gear (no-intro) full set
Mame 2003plus full set

Now the theme is suddenly back to the purple one
Theme switcher app works, but no theme is changed.

is this a memory problem? Too much covers?

**Comment by Sichroteph** [comment]
Do you use the stock SD card ?

**Comment by ac3nl** [comment]
Definitely not, a certified Sandisk 256gb

**Comment by Sichroteph** [comment]
Not sure how it is related. Can you look at appconfigs / system.json and tell me what is a theme variable ?

**Comment by ac3nl** [comment]
I really can't find that file

**Comment by ac3nl** [comment]
I went into the miyoo settings without an sd card.
Went into the fixes menu
Did not change ANYTHING
Shutdown normal way

Now i have my theme back …
Wtf?

**Comment by Sichroteph** [comment]
That makes sense since rebooting without the SD reset the file i mentioned. If it happens again i am interested by this value. I am closing glad you fixed it.
