### ISSUE TITLE
Booting crash #291

### ISSUE THREAD

**Issue by Bryan7z** [jimgraygit/Onion#293]
I followed the GitHub page recommendations/instructions
every file is in its designated location and has correct file format

The problem is for Arcade and NEO GEO
The issue is the games boots when launching from retro arch, but crashes/kicks out  when launching from menu consoles section. Others like GBA, SFC   etc. work.

If the issue was BIOS, it wouldn't work in retro arch either, but it does?

Some else also created this same issue but was closed

v3.10.6

**Comment by Sichroteph** [comment]
Did you copy the neogeo.zip in the rom folder ?

**Comment by Bryan7z** [comment]
yes

**Comment by Bryan7z** [comment]
I even installed onion like 3 times from testing several  bios, ROMs etc.

**Comment by Sichroteph** [comment]
What core do you choose when launching the game from Retroarch?

**Comment by Bryan7z** [comment]
final burn neo

**Comment by Sichroteph** [comment]
Do you use the bios files provided by miyoo ?

**Comment by Bryan7z** [comment]
Yes and also tried others

**Comment by Bryan7z** [comment]
When I don't use onion just stock OS it works

**Comment by Sichroteph** [comment]
The main maln menu uses FBALPHA 2012 for neogeo, it doesn't seem to work well on your system. Pretty sure it's the rom.

**Comment by Bryan7z** [comment]
Would reinstalling onion fix that or is that miyoo bio

**Comment by Sichroteph** [comment]
Required ROM Version: FBAlpha v0.2.97.29 (v0.2.97.40, v0.2.97.42, v0.2.97.43 and v0.2.97.44 may work as well).
Rom Folder: NEOGEO

**Comment by Sichroteph** [comment]
Please choose an adequate rom for FBALPHA 2012

**Comment by Bryan7z** [comment]
Is that
 Arcade FB Alpha 2012 neo geo

**Comment by Sichroteph** [comment]
> When I don't use onion just stock OS it works

That doesn't mean that onion is broken, just that it uses a different core for performance reasons. You need roms compatible with this core.

**Comment by Bryan7z** [comment]
Is there a place I could find them or would that be off limits

**Comment by Sichroteph** [comment]
Unfortunately for my mental sanity it is off limits.

**Comment by Bryan7z** [comment]
understandable

**Comment by Sichroteph** [comment]
If the rom you download works for another core, you can change the core name in the launch.sh file

**Comment by Bryan7z** [comment]
Ok where would that launch.sh be I have seen several

**Comment by Sichroteph** [comment]
In emu neogeo

**Comment by Bryan7z** [comment]
it didn't work

**Comment by Bryan7z** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/106444882/170849399-a25cff9e-4ec4-4fb0-b485-5de88fc719a2.png)

this it what i changed it to

**Comment by Bryan7z** [comment]
I changed the launched file to default fbalpha2012 core and working core no luck

**Comment by Sichroteph** [comment]
Closing as you did not read the instructions. spoke with other users and there is a consensus :
Find a 0.2.97.29 romset, 0.2.97.43 or 44 should work as well
