### ISSUE TITLE
New game add to Roms don't show up in the list of that emu

### ISSUE THREAD

**Issue by synozhang** [jimgraygit/Onion#294]
After I install onion os, when i first add several games into the Roms folder (such as Roms/GBA), all the games could be seen.
However, when i then add another several games to the same folder, the newly added game could not be seen.
How to fix this?

**Comment by synozhang** [comment]
It seems like, after the emulator do the first scan of its dir, it would not scan any other later added roms into its list...

**Comment by Sichroteph** [comment]
Press the option button in the console list and select update.
