### ISSUE TITLE
RTC GBC Games Break Onion Launcher

### ISSUE THREAD

**Issue by whitt-e** [jimgraygit/Onion#305]
On the latest version, when onion launcher is enabled, attempting to resume a GBC RTC game will freeze the device, requiring a force reboot and launcher disable to proceed. The launcher will only begin working again after being shut off (twice, from apps), then enabled.

The GBC game will continue to freeze the device upon save state resume until the clock is set from the apps section.

Not sure how much of this is expected for RTC games but I wanted to bring it up!

**Comment by Sichroteph** [comment]
Yes sorry we don't support ROM hacks. They are well known to create the issues you describe.

**Comment by SirPrimalform** [comment]
That's good news! It was closed prematurely before but it seems like it doesn't need re-opening now.
