### ISSUE TITLE
Emu folder missing on install?

### ISSUE THREAD

**Issue by jdbiggs** [jimgraygit/Onion#306]
I did a fresh install and the Emu folder is empty. None of the emu icons are appearing and when I run Retroarch manually it doesn't appear that the controls are mapped correctly. Not sure what I'm seeing but I could use a bit of direction. Moved files on Mac OS and using V2 hardware. Thanks.

**Comment by Sichroteph** [comment]
Did you use the installer to select the consoles you want ?

**Comment by jdbiggs** [comment]
Yes, and the apps.

**Comment by jdbiggs** [comment]
Is there a folder somewhere I can find them and drag them out?

**Comment by Olywa** [comment]
@jdbiggs did you solve the issue ?

**Comment by imthisguymike** [comment]
I am using macOS and had a similar issue. My resolution (with a new microSD) was between copying .tmp_update and booting the miyoo mini with the new microSD:

I opened the .tmp_update folder in terminal and ran:
`find . -type f -name "._*" -exec rm "{}" \;`

Then I booted up the miyoo mini and it worked better than before.

**Comment by Sichroteph** [comment]
Thanks for your participation.
