### ISSUE TITLE
Fix controller 1 dualshock disabled in many PSX games (Consoles/1194: PSX)

### ISSUE THREAD

**Issue by scarlet-RS-97** [jimgraygit/Onion#31]
It appears that there is an issue in terms of configuration for the PSX core (Consoles/1194: PSX from the main menu).

In many games, controller 1 is disabled. 
 - For example, it is not possible to turn left or right in Ridge Racer Type 4 (E)
 - Another example: the nofification "no controller 1" appears in Need For Speed - V-Rally

Workarounds but disable rumble effect:
 - Put contfroller 1 as standard instead or Dualshock
 - Or create another PSX_stock folder in Emu and copy here the PSX emulator from Miyoo stock firmware

I wish you a nice day

**Comment by Sichroteph** [comment]
Thanks, it will be fixed in the next Onion version.
