### ISSUE TITLE
Onion Shortcut Keys override RetroArch hotkeys

### ISSUE THREAD

**Issue by ParkRomn116** [jimgraygit/Onion#312]
Deleted the global or core-specific config file doesnt solve this to my knowledge.
Using the updated Onion os, I tried to make a different hotkey enabler (select) and
in place of the MENU button on the device, when I did, each time I try to save with
the save state it says "SAVE STATES ARENT SUPPORTED ON THIS CORE". I cannot go
back to using the MENU button instead of SELECT to enable hotkeys anymore either
none of the Onion shortcut keys work anymore. Is there a hidden config file overriding
Onion Shortcut keys?  Thank You

**Comment by Olywa** [comment]
Confirmed with user on reddit that this is resolved following a clean install.
@ParkRomn116 don't forget point 4 ;)

**Comment by ParkRomn116** [comment]
Closed issue, user error not an Onion OS issue. Note: Don't delete the Retroarch.config file in the.retroarch folder.
