### ISSUE TITLE
Language for Onion

### ISSUE THREAD

**Issue by MardSilva** [jimgraygit/Onion#316]
Hi anyone! 
There's a way do add/help on translation language file for PT-BR? 👍🏽 
If have one way, tell me how i need to do to help the project.

**Comment by Sichroteph** [comment]
This belong to the discussion tab, here all i try is to close the ticket :) 
Check the lang folder inside the miyoo folder, you will see files for different languages. You can make a new one and translate all strings.  Thanks for your help !

**Comment by MardSilva** [comment]
Sorry for my lazy response. Where they are located? Thanks!!
