### ISSUE TITLE
OnionLauncher stops loading certain systems on startup, works fine when launched with the shortcut in OnionOS

### ISSUE THREAD

**Issue by rcnino** [jimgraygit/Onion#317]
The OnionLauncher is a great way to focus on my current rotation of games and really makes the Miyoo/Onion experience, but after a few days it stops loading certain systems on startup, yet it works perfectly when launched from the shortcut in App. I detailed my testing in this post: https://www.reddit.com/r/MiyooMini/comments/v223rc/onionlauncher_doesnt_start_games_on_startup_works/

I reinstalled OnionOS for the second time this week to fix it. Is there a way to resolve this without having to reinstall Onion? Maybe delete a cache file or check a config file for startup tasks?

**Comment by Sichroteph** [comment]
You seem to be an isolated case. Reading your previous post, it seems that your issue with the launcher is old, making it even more rare.
From what I understand, you seem to do something in the next days after the installation that breaks the launcher.
What I will need from you is to "break" the launcher, then to send me this file :
Saves\CurrentProfile\lists\content_history.lpl

**Comment by rcnino** [comment]
I was in the middle of a reinstall as I created this issue. OnionLauncher broke immediately after with Genesis. I can't say I know what I am doing that causes this to happen or I would mention it. I have only played this one ROM today which came with the Mini.

Github wouldn't accept the file as .lpl so I changed it to .txt
[content_history - Copy.txt](https://github.com/jimgraygit/Onion/files/8835981/content_history.-.Copy.txt)

**Comment by Olywa** [comment]
The lpl doesn't really offer any clues (at least to me - maybe it helps @Sichroteph.

It makes no sense that it would work and later not (but still from Recents) so my suggestions may seem illogical but... 

Have you refreshed your game lists (Highlight the console, press menu->refresh to update)

When you reinstalled, you deleted **everything** leaving **ONLY** Roms/Bios/Saves folders on the SD card and added the .tmp_update folder from the Onion download?

You've not deleted anything from the card after the Onion install or changed/replaced any retroarch config/settings/files ?

If you go to Emu->MD and open config.json, looking at the rompath there - does it match your rom location (and rom path in the lpl file) exactly (including the case).

Are you using the roms that came with the mini - possibly source a couple of genesis roms from the web to try those?

I saw that you are using a new card (great), are you using the USB card reader that came with the mini (it's poorly made and we have seen this corrupt data/good cards).

**Comment by rcnino** [comment]
Not only from Recents, but it works like it's supposed to using the "Start launcher" app to manually start OnionLauncher and will continue to work until I power off. The issue only occurs when starting up after being powered off by pushing the power button to "Save + Shutdown".

- Yes, game lists have been refreshed.
- This last reinstall, I formatted the card then copied back my Roms, BIOS, Saves, Themes.
- I have not made any changes to the OS.
- Yes, using ROMs that came with the Mini. Even with the few ROMs that I have added, the issue occurs with that system (ex. Genesis)
- I am using a Sabrent USB 3.0 card reader.

Video of issue: https://1drv.ms/v/s!Ahsy1sR0QuXytIodJn0kPTVoQF9Niw?e=C1u1OH
This demonstrates NeoGeo functioning correctly on startup using OnionLauncher but not SNES. Then it shows OnionLauncher functioning correctly from within the OS. Yes, I am demonstrate with a patched ROM, but the Miyoo plays it just fine so it can't be that.

**Comment by Olywa** [comment]
So do you ONLY have this issue when using patched roms?

Maybe you can try temporarily disabling auto loading of save states in retroarch?

- Launch the game and press Menu+Select to got to RetroArch menu.

- Press B to go back one level to RA Main Menu, then Settings->Saving->Load State Automatically (toggle this to off)

- Now Press B twice to get back to the RA Main Menu and go to Quick Menu->Overrides->Save game overrides*

*you can go back and delete the game override later.

**Comment by Sichroteph** [comment]
@rcnino is it really only with rom hacks ?

**Comment by rcnino** [comment]
I disabled auto loading save states and it did not solve the problem. 

@Sichroteph @Olywa this happens with ALL ROMS on the affected system.

**Comment by Sichroteph** [comment]
I fixed a bug that seems completely unrelated but still, did you use often the light sleep feature ? (Menu + power)

**Comment by Sichroteph** [comment]
I also reverted in 3.11 some binary hacks i did that affected the roms folder scan, could it help you too ?

**Comment by rcnino** [comment]
@Sichroteph I only use the single power button push to save + shutdown. 

I updated to v3.11 today (delete all but BIOS, Roms, Saves, Themes). Launcher is still behaving the same. 

My next troubleshooting step is to reinstall without my Save folder. I’ll post back with results.

**Comment by Sichroteph** [comment]
One save or one config you drag from before could indeed cause why your bug still after a full install.
On my side I tried to reproduce your issue with the same rom but it works :
https://youtu.be/ra7F91IM-5c
I also parsed your history file but it seems fine.

**Comment by rcnino** [comment]
@Sichroteph @Olywa I figured it out: rewind. 

I enable rewind with the settings 3, 100, 10. Play a bit to fill the buffer. Power off (save + shutdown), power on, issue occurs. 

Interestingly, if I power on with rewind disabled then try to enable rewind, the system freezes and I have to Start+Select+L2+R2. 

I dropped the buffer size to 20 and have no problems now. 20 MB is also plenty of rewind history for the games I’m playing, rom hacks and all ;-)

**Comment by Olywa** [comment]
...so... even after a 'clean install' you were first going into RA and increasing the RW buffer size by 80mb on those 'failing' systems before testing? :D

I believe the RW buffer feature pre-allocates ram for the purpose so 'losing' 100mb from the minis already very limited 128mb makes sense that it could cause some strange behaviour.

In any case, congrats! I'm glad you were able to figure it out. If you are satisfied that the issue is resolved maybe you can change the status to 'Closed'.

**Comment by rcnino** [comment]
The rewind settings were part of my Saves, so it would persist after reinstalling Onion. Since the games never had a problem running when launched from the shortcut, I didn’t make the connection. Starting with no saved configuration helped me find it. 

Thank you @Olywa and @Sichroteph for your help.

**Comment by Olywa** [comment]
Good to know, thanks. Maybe this will at least provide another troubleshooting path for future strange or isolated issues (i.e. clean install without copying over the saves). 

Thanks for closing :)

**Comment by Sichroteph** [comment]
That was interesting to read. And always satisfying to find the culprit. Glad it works fine now.
