### ISSUE TITLE
"Imgs" folder disappearing

### ISSUE THREAD

**Issue by chapulanga** [jimgraygit/Onion#318]
Hello all.

Second time it happens: suddenly the operating system stops showing the images of the roms. Then when I check the sd card the "Imgs" folder is gone. Currently on 3.10.6, folder created on card root.

**Comment by Olywa** [comment]
When you say "folder created on card root"...
Onion expects images to be in Roms/[system_name]/Imgs _not_ in a root 'Imgs' folder (which was how the stock miyoo OS handled it). [Please see the wiki for more info on images](https://github.com/jimgraygit/Onion/wiki/3.-FAQ-(Frequently-asked-questions))

----
If this resolves your issue please change the status to Closed.
