### ISSUE TITLE
TyrQuake, Rednukem and other Doom Variants?

### ISSUE THREAD

**Issue by Gordon1972** [jimgraygit/Onion#319]
Hi there,
i just installed OnionOS 3.11.1 and wondered where the TyrQuake-Port went?
Has it just disappeared or am i missing out something?

The ECWolf-Instructions are not helpful. By reading them, i still wonder where to put the Wolf3D files?
Your instructions are unclear, please be more precise here (-> what is the "wolf dos" folder???)

Have you itched the RedNukem port in favor of eDuke32 or what is the reason only eDuke32 is left?

Can we add TNT and Plutonia Pack (Doom) anywhere? No instructions on where to put these .wads.

I also found that NBlood and VoidSW have disappeared? What happened?

BTW: OpenBOR is still not working...

Thanks for reading.

**Comment by Sichroteph** [comment]
If you liked the new port organization you can try to add some and submit them in the discussion page. Other porta are here : https://github.com/jimgraygit/Onion/wiki/6.-Miyoo-mini-apps

**Comment by Sichroteph** [comment]
I tried to show you the way while leaving you the old alternatives. However I put some ports out in order to leave the experimental tab more for alternative system cores.

**Comment by Sichroteph** [comment]
I'll looks at open bor in the following days. Closing now.

**Comment by Gordon1972** [comment]
Thanks for your Information. I now know how to deal with the seperate Ports sections. It wasn’t clear to me at the first sight.
The „external Ports“ are well hidden on your Wiki page placed most top-down in the list 😉. Maybe you’d like to merge the Ports sections in the future for a better understanding?
That would be nice. Keep up the good work @Onion OS, it’s a very good piece of Software.

Cheers,
  Gordon
Von: Sichroteph
Gesendet: Sonntag, 5. Juni 2022 08:27
An: jimgraygit/Onion
Cc: Gordon1972; Author
Betreff: Re: [jimgraygit/Onion] TyrQuake, Rednukem and other Doom Variants?(Issue #319)

I tried to show you the way while leaving you the old alternatives. However I put some ports out in order to leave the experimental tab more for alternative system cores.
