### ISSUE TITLE
[bug] after update to 3.11.1 MSX/SVI/Colecovision  (bluemsx) core doesn't work

### ISSUE THREAD

**Issue by ac3nl** [jimgraygit/Onion#321]
on 3.10.6 this was working 100%

steps i took:

i removed all content except
Bios, Saves, Themes and Roms
copied .tmp map and went with the install.
did not select anything in installer
exited
copied EMU map back to SD card 

alle emulators work, except MSX (1 and 2) and coleco
even when i open retroarch, they don't work
I can see the coleco screen, but gives a warning that i need ro turn off before switching games?.
Games don’t start, did some fideling with the options, but nothing works

all bios are in place, as they were on 3.10.6

anyone??

can i copy back the old bluemsx core to the retroarch map?
UPDATE:
copy back old core doesn't solve problems

Update 2:
did copy my 3.10.6 files back to sd card, still Bluemsx won't work
deleted all core overrides from Saves dir (bluemsx only) , now everything works again
copied back all 3.11.1 files, still works now.

at the end, think i had a corrupt core override or so

solved!

**Comment by Sichroteph** [comment]
Thanks for your feedback, closing!
