### ISSUE TITLE
Onion is not seeing any of my roms

### ISSUE THREAD

**Issue by lindtobias** [jimgraygit/Onion#322]
I installed Onion on my Miyoo Mini the other day and it seems no matter what I put on my SD card it shows up as empty in Onion.

Not sure how to proceed, did I break my Miyoo Mini?

**Comment by Olywa** [comment]
You cannot copy the 'Roms' folder wholesale from the Miyoo card to an Onion installation/card, the system names in the Roms folder are different. Please refer to the rom folder per system in the wiki and make sure you are placing them in the correct folders (folders are also cases sensitive). https://github.com/jimgraygit/Onion/wiki/2.-Onion-Emulators-&-Ports

Once you have added roms, you should highlight the system in the console menu and press Menu button-->refresh.  
 
--
If this resolves you issue please come back and comment with an update and set the status to CLOSED.

**Comment by lindtobias** [comment]
Why case sensitive?

Anyway, I renamed the folders to match that link and made sure they're all caps and it still shows up as empty - even though I refreshed roms.

right now gba is in /ROMS/GBA/ for example and it's still shows empty. Is that not correct?

**Comment by ac3nl** [comment]
Try a rescan.
Press menu in the main menu, and select

**Comment by Olywa** [comment]
is you 'ROMS' folder in capitals like that ? It must be '**Roms**/GBA/'

**Comment by lindtobias** [comment]
Yeah, I assume they all had to be caps based on that document you linked.

You really ought to mention somewhere in the installation instructions that it’s case sensitive though, especially since it doesn’t follow the Miyoo Mini defaults.

This has wasted so much of my time and I have been unable to use my Miyoo Mini for days.
