### ISSUE TITLE
[SUGGESTION] Wiki -> MAME samples folder

### ISSUE THREAD

**Issue by tarikalmashni** [jimgraygit/Onion#323]
### Discussed in https://github.com/jimgraygit/Onion/discussions/315

<div type='discussions-op-text'>

<sup>Originally posted by **tarikalmashni** June  3, 2022</sup>
You should add to the **ARCADE** paragraph in the emulator wiki where to place the samples folder that comes with MAME rom sets.
I don't have my Miyoo Mini yet but I guess they go here:
[RetroArchBiosFolder]/mame2003-plus/samples/[zips in here]
At least I would put them there according to the official Libretro docs (don't have my own Mini yet, so can't verify): https://docs.libretro.com/library/mame2003_plus/#audio-samples</div>

**Comment by ac3nl** [comment]
This is more of a Discussions type of question.
I see you allready opened it there too.

**Comment by Sichroteph** [comment]
Thanks for your suggestion. We are currently rewriting the arcade part and It will be added too.
