### ISSUE TITLE
RetroArch cheats not working

### ISSUE THREAD

**Issue by wanderer-84** [jimgraygit/Onion#33]
Downloaded correct .cht files onto SD card (RetroArch\.retroarch\cheats), enabled cheat entry in quick menu, enabled and applied cheat but nothing happens even after restarting the game. Tested on PSX (Final Fantasy VII) and SNES (Breath of Fire)

**Comment by Sichroteph** [comment]
Thanks, we do not support cheats files yet. If you find a solution to your issue please tell us.
