### ISSUE TITLE
Is it possible to make the overlay works?

### ISSUE THREAD

**Issue by realjackwang** [jimgraygit/Onion#330]
I saw the miyoo mini using overlay someone sent on a forum, but unfortunately the current version of RetroArch doesn't support overlay

It would be great if it woks on Onion!

![image](https://user-images.githubusercontent.com/29890029/172170765-d8c515fc-9e7f-4f09-ac89-565202408ba6.png)

![image](https://user-images.githubusercontent.com/29890029/172170794-c29464ae-5a18-44a3-8d0e-9da4ac252398.png)

**Comment by Sichroteph** [comment]
Unfortunately Eggs prefers to disable to them for now to maximize the performances
