### ISSUE TITLE
V3.11 - 20220604 SNES not working.

### ISSUE THREAD

**Issue by joshwillcock** [jimgraygit/Onion#333]
Unsure of the specific information to help investigate.
Previously used V3.09 without issue. Fresh install today 3.11 / 20220604 and SNES games do not load via the console menu. They do load if opening Retroarch and then manually loading the ROM. Other consoles continue to work.

**Comment by Sichroteph** [comment]
Can you try to refresh the rom list ?

**Comment by joshwillcock** [comment]
> Can you try to refresh the rom list ?

I literally reinstalled it three times, used a different card. Did I refresh the rom list? No. I'm guessing it stores it somewhere not on the SD Card?

PICNIC issue... Sorry & Many Thanks!

**Comment by Sichroteph** [comment]
You are very welcome !
