### ISSUE TITLE
Menu button results in a+b button presses in NES

### ISSUE THREAD

**Issue by pfroo40** [jimgraygit/Onion#334]
On 3.11.2, release notes say this issue is fixed in these latest releases, but when I press menu, it results in in-game button presses of A and B buttons.

**Comment by Sichroteph** [comment]
I believe that's because you overwrite the fix with your settings.
Copy this file in 
C:\Users\Christophe\Dropbox\Onion Growers\Onion V3\Onion.V3.11.2\.tmp_update\.data\Core\Saves\CurrentProfile\config\remaps\FCEUmm
[FCEUmm.zip](https://github.com/jimgraygit/Onion/files/8845614/FCEUmm.zip)
