### ISSUE TITLE
2021 Stock Theme zip actually contains Onion Boy Theme

### ISSUE THREAD

**Issue by jeff93063** [jimgraygit/Onion#34]
In the Theme Repository, clicking on the "2021 Stock by Miyoo" theme downloads a zip called Theme-OldStock.zip. But inside this zip is a folder called Theme-OnionBoy. Installing this in Onion OS gives the OnionBoy theme.

**Comment by eth101** [comment]
Noticed the same thing as well.

**Comment by Sichroteph** [comment]
Thanks, we will fix that in the next version !
