### ISSUE TITLE
wolfenstein 3D / ecwolf core - Command line ?

### ISSUE THREAD

**Issue by schmurtzm** [jimgraygit/Onion#340]
Hi, 
In retroarch, if I add the right bios, load the ecwolf core manually and then load the rom (manually too) I'm able to run Wolfenstein 3D (with some crashs when playing but anyway).
So I try to create a "launch.sh" to run it directly from the new PORTS menu ... without success at this time : when running it always return to the menu.

```
#!/bin/sh
echo $0 $*
progdir=`dirname "$0"`
homedir=`dirname "$1"`



if [ -f "/mnt/SDCARD/Emu/PORTS/Binaries/Wolfenstein 3D/Wolfenstein 3D/vgahead.wl6" ]; then
	# Timer initialisation
	cd /mnt/SDCARD/App/PlayActivity
	./playActivity "init"

	cd /mnt/SDCARD/RetroArch/
	HOME=/mnt/SDCARD/RetroArch/ /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/ecwolf_libretro.so

	# Timer registration
	cd /mnt/SDCARD/App/PlayActivity
	./playActivity "Wolfenstein 3D"
else
	cd "/mnt/SDCARD/Emu/PORTS/Binaries/missingFile"
	./infoPanel
fi


```

What I'm missing ?

**Comment by Olywa** [comment]
I've not played with this or even ports at all but I think you need to follow more closely what is already there. So I think it should be more:

```
if [ -f "/mnt/SDCARD/Emu/PORTS/Binaries/Wolfenstein3D.port/FILE_HERE/vgahead.wl6" ]; then
	# Timer initialisation
	cd /mnt/SDCARD/App/PlayActivity
	./playActivity "init"

	cd /mnt/SDCARD/RetroArch/
	HOME=/mnt/SDCARD/RetroArch/ /mnt/SDCARD/RetroArch/retroarch -v -L /mnt/SDCARD/RetroArch/.retroarch/cores/ecwolf_libretro.so "/mnt/SDCARD/Emu/PORTS/Binaries/Wolfenstein3D.port/FILE_HERE/vgahead.wl6"

	# Timer registration
	cd /mnt/SDCARD/App/PlayActivity
	./playActivity "Wolfenstein 3D"
else
	cd "/mnt/SDCARD/Emu/PORTS/Binaries/missingFile"
	./infoPanel
fi
```

...I suspect you already did this part you you will need to:
Create an empty text file in **Emu\PORTS\PORTS\** called Wolfenstein3D.port (.port is the extension instead of .txt)
and
Put your files in a folder named exactly: **Binaries\Wolfenstein3D.port\FILE_HERE\**

**Comment by schmurtzm** [comment]
You're right, I've forgot the rom path in my example.
Now it's working perfectly, thank you.

**Comment by Olywa** [comment]
@schmurtzm Awesome! Thanks for confirming and closing the issue :)

**Comment by Sichroteph** [comment]
Can you share us the zip of the part so we can add it on future releases?

**Comment by dwmccoy** [comment]
I will upload my files for you.  I created two sets.  PORTS_ECWolf_SW.zip includes my files for Wolfenstein 3D Shareware Version.  PORTS_ECWolf.zip includes my files for Wolfenstein 3D registered version.

[PORTS_ECWolf_SW.zip](https://github.com/jimgraygit/Onion/files/8850191/PORTS_ECWolf_SW.zip)
[PORTS_ECWolf.zip](https://github.com/jimgraygit/Onion/files/8850192/PORTS_ECWolf.zip)

**Comment by dwmccoy** [comment]
Also please note that ECWolf does require the BIOS file named ecwolf.pk3.  It should be placed into the /BIOS folder

**Comment by schmurtzm** [comment]
> Can you share us the zip of the part so we can add it on future releases?

Hi @Sichroteph , this is my share for Wolfenstein, very similar to dwmccoy's one, the only differences are : 
- the path contains space ("Wolfenstein 3D.port" and not "Wolfenstein3D.port", seems more logical to me because previous ports have spaces and "playActivity" contains a space.
- My image thumbnails is not stretched (but that's a matter of taste 😉 )
https://www.dropbox.com/s/23p01sy53gy3azv/wolfenstein.zip?dl=0


I've made a beautiful collection for the four episods of Quake, may be you will change some details in directories names but it works very well.  https://dl.dropbox.com/s/ydw8me04d8qipc7/Quake.zip?dl=0


I have to say that I don't like the "FILE_HERE" folder name, I think it's confusing : "should I put my data files where I see "FILE_HERE" or inside the folder "FILE_HERE"" ?. Now I know because I read config files but may be simply Roms, Data or Files are better names.
