### ISSUE TITLE
Load state hotkey

### ISSUE THREAD

**Issue by zebramonkeylizard** [jimgraygit/Onion#348]
Intermittently, the hotkey for loading save states switches from (Menu + L2) to (Menu + L1) when using the default NES emulator. Restarting the miyoo mini resolves the issue.

**Comment by Sichroteph** [comment]
That's very strange. Any way to replicate it ?

**Comment by zebramonkeylizard** [comment]
If I boot up with the Onion launcher enabled them then the hotkey works as expected. If I then exit out of the game, then out of Onion Launcher, and then relaunch the game from Recent, then I have the issue.

**Comment by Sichroteph** [comment]
Did you change the keys in the miyoo button  panel by any chance ?

**Comment by Olywa** [comment]
I followed your steps exactly and tried several times but have not been able to replicate this issue. L2 is always 'load state' both from the launcher and when quitting the game and starting it again (outside of the launcher). I tried with NES only.

Can you pop your SD card into a PC and see if you find any files in RetroArch\ .retroarch\config\remaps (there should not be any).

You can try also, going to Saves\CurrentProfile\config\FCEUmm and delete any files there and replace them with those I have attached. [FCEUmm.zip](https://github.com/jimgraygit/Onion/files/8882507/FCEUmm.zip)

See if you can still reproduce (for NES). 

Honestly, I'm not sure this help as I think something went wrong with your installation (maybe you overwrote some files/folders when copying to the SD card or you left your old retroarch folder in place when installing/upgrading?). You may be looking at a clean install to resolve this.

**Comment by zebramonkeylizard** [comment]
I tried under Guest Mode (uses the default Onion config) with the same issue. I also noticed under Guest Mode that my Favorites and Recent were still listed from the main profile. Is that supposed to happen? If not, maybe there is an issue with my installation. I will give it a fresh install.

**Comment by zebramonkeylizard** [comment]
Fresh install fixed the load state issue :) but I still see the main profile Favorites and Recent under the Guest profile so I will open am issue for that ;).

**Comment by Olywa** [comment]
Since the original issue is resolved (and you have logged the profiles issue separately) please could you set the status of this one to CLOSED.

Thanks.

**Comment by zebramonkeylizard** [comment]
Thank you for the quick responses and all your efforts.
