### ISSUE TITLE
Pico-8 wiki correction: .png files appear to be supported

### ISSUE THREAD

**Issue by RetroBreeze** [jimgraygit/Onion#356]
I've tested over 25 Pico-8 games in .PNG formate and all of them have worked so far. I propose this update to the Wiki:

```
**Pico-8**

- Emulator: **fake-08**
- Rom Folder: PICO
- Extensions: .p8 .P8 .png
- Notes: Compatibility is improving, but not perfect.
```

 I wanted to submit a PR directly but apparently you can't do so on Wikis.

**Comment by Olywa** [comment]
Hi there, another good catch! This one was already on the radar. The wiki is a little out of date as earlier Onion releases did not have support for .png but it was later added. Please close for me and if you check back next week the wiki should have been updated 👍

Again, thanks for reporting.
