### ISSUE TITLE
Sharp X68000 Wiki ROM folder correction

### ISSUE THREAD

**Issue by RetroBreeze** [jimgraygit/Onion#357]
Under Sharp X68000, the wiki says the ROM folder is "SHARP", which should be corrected to "X68000".

**Comment by Olywa** [comment]
Hey there, thanks a lot for reporting this. The wiki will be updated along with some other additions in the next few days and so this will be corrected (at the same time we will link you 'Arcade' video 😎 )

I've made a note of it separately so if you could set the issue to closed for me it would be really appreciated.

**Comment by RetroBreeze** [comment]
Roger that!
