### ISSUE TITLE
Battery percentage meter corrupt, post v3.11.2 upgrade?

### ISSUE THREAD

**Issue by bigjoestretch** [jimgraygit/Onion#358]
Hi guys, have you guys come across an issue with the v3.11.2 where the battery percentage meter appears corrupt? I have a screenshot of the issue via the link below.

https://1drv.ms/u/s!AhmQJpFIe1KCtooGggo3MtMmAa1Ieg

**Comment by Olywa** [comment]
Hi there, thanks for providing a screenshot. This is a strange one and it's not something I've seen reported (on here, reddit or discord) so seems unique to your install/config.

Can I suggest:

1) Switch themes to see if it occurs with another theme (and if not try switching back to this theme and see if it's still a problem

2) Try reinstalling your themes - just pop your SD into the pc, delete the contents of your 'Themes' folder and copy them back to the card again either the from [Onion.V3.11.2.zip](https://github.com/jimgraygit/Onion/releases/download/20220604/Onion.V3.11.2.zip) or download the themes you want by clicking on the images in the [themes repository](https://github.com/jimgraygit/Onion/wiki/4.-Theme-Repository) 

Please report back if it helps.

**Comment by bigjoestretch** [comment]
Hi there, thanks for responding. I tried switching to various themes, but no luck with that. I then proceeded to remove all themes, then re-add them from the link you provided, but that was unsuccessful as well. I'll try wiping the SD card and re-installing Onion OS v3.11 and report back.

Thanks
