### ISSUE TITLE
Removing Console Icons

### ISSUE THREAD

**Issue by ProvokedCashew** [jimgraygit/Onion#36]
Fallowing a YouTube guide, I was informed moving or deleting folders from the "roms" directory would remove the corresponding consoles from the console option in onion os. I relocated the folders related to systems I would not be using to a new folder in the root directory, however the systems still appear in the "consoles" option in onion os.

**Comment by DaPiMan** [comment]
I watched the same video. Actually move the folders of the systems you don't want in the menu from the /EMU folder not /ROMS

**Comment by ProvokedCashew** [comment]
Thank you, that was my issue. Sometimes it's too much to try and follow along at the same time.
