### ISSUE TITLE
Picodrive - Freezing

### ISSUE THREAD

**Issue by zebramonkeylizard** [jimgraygit/Onion#367]
Picodrive is a great emulator for many games, but it freezes on Lightening Force (Thunderforce IV), a very popular game. Genesis Plus GX works flawlessly with every game I've tested and performance is excellent. I vote for Genesis Plus GX to be the default Sega Genesis/Mega Drive emulator. Maybe a Picodrive update?

**Comment by Olywa** [comment]
Will leave this one for the Onion devs to comment but can you give an example of how to replicate the freezing?

**Comment by zebramonkeylizard** [comment]
I've tested a different rom version and encountered the same random freezing. I googled it and found others have reported the same issue with Picodrive where the video freezes, but the audio continues.

**Comment by Olywa** [comment]
hey again, it seems from reading here: https://forum.recalbox.com/topic/6741/thunder-force-4-megadrive-freezes/5
that the issue only affects the Europe release of the game and not the USA/Japan versions - If I have understood that correctly maybe you can use the USA rom (for now)?
