### ISSUE TITLE
Cannot run PC Engine CD games

### ISSUE THREAD

**Issue by Geyb712** [jimgraygit/Onion#37]
When I try to run Rondo of Blood or any other PC Engine CD games, the screen states "loading" and I get kicked back to the main PC Engine CD rom list. 

I checked for the syscard1 through 3 bios files and all three are showing in both the SD card Bios folder and Retroarch's system folder. Additionally, I've also attempted to run the games in both bin/cue and CHD formats, but all attempts resulted in getting kicked back to the rom list screen.

**Comment by ljewe7** [comment]
Did you manage to solve this?

**Comment by beanorx** [comment]
Rondo runs for me.

**Comment by ljewe7** [comment]
nice! - in what format? Any tips to run that game would be great.
