### ISSUE TITLE
custom themes not visible in v3.11

### ISSUE THREAD

**Issue by Thelittlestpropshop** [jimgraygit/Onion#370]
Hi, just put onion on my miyoo mini and im very impressed with it however i cant seem to get any custom themes to show up on my device.  I downloaded 4 from the repository here and none of them show up after unzipping them in to my themes folder

**Comment by dwmccoy** [comment]
Did you install the theme switcher app to switch between themes?

**Comment by Thelittlestpropshop** [comment]
yes i did, got the 6 or so ones that come preloaded but the ones i have downloaded from the theme page dont seem to be found at all

________________________________

**Comment by dwmccoy** [comment]
I just downloaded Miyoo.Jazz.zip.  I unzipped the file and it created a directory called Miyoo.jazz.  Inside of that directory is a directory called Miyoo jazz.  Copy the directory named Miyoo jazz to the /Themes folder on the root of the SDCARD.  Used Theme switcher to successfully switch theme to Miyoo jazz.  

Please make sure your unzipping the file.  Please make sure your copying the correct directory to the themes folder.

**Comment by Thelittlestpropshop** [comment]
cracked it now thanks for the help

________________________________

**Comment by dwmccoy** [comment]
If you have resolved your issue, please close your ticket please.  Thanks.
