### ISSUE TITLE
Confused By Port Instructions (DukeNukem, Doom, Doom 2)

### ISSUE THREAD

**Issue by ABoyWithoutAClue** [jimgraygit/Onion#371]
I saw in the Emulators & Ports page the instructions for Duke Nukem, Doom, Doom 2, but I am confused by them. They all say to copy a file, but what do I do with it after I copy it?

For example: Copy the doom1.wad file in \Emu\PORTS\Binaries\Doom.port\FILE_HERE
rename your .wad file in necessary, caps are important.

After I copy it, where do I put it or paste it?
When I try to play DN3d, Doom, Doom 2 I receive the error "One or more elements are missing to make this port work, which we can't share for legal reasons". I'm confused by the "copy this file" instructions in the WikiPage though. My apologies and thank you in advanced, I am entirely new to these emulators and handheld devices as I just received my first one this past week and am still learning.

**Comment by RetroBreeze** [comment]
I can chime in here. The files must be named and placed as such:

-  /Emu/PORTS/Binaries/Doom.port/FILE_HERE/doom1.wad
- /Emu/PORTS/Binaries/Doom2.port/FILE_HERE/doom2.wad
- /Emu/PORTS/Binaries/Duke nukem 3D.port/FILE_HERE/duke3d.grp
