### ISSUE TITLE
DukeNukem 3D Port - File Name?

### ISSUE THREAD

**Issue by ABoyWithoutAClue** [jimgraygit/Onion#376]
Hello,
On Wiki-2. Onion Emulators & Ports, under Duke Nukem 3d it says: 

     Duke Nukem 3d (Port : Stupid Horoscope)

     Copy the duke3d.grp file in \Emu\PORTS\Binaries\Duke nukem 3D.port\FILE_HERE

When I go into the PORTS folder, the file is called "Duke nukem 3D.port" not "duke3d.grp" as mentioned in the Emulators & Ports page.

If I copy and paste the file "Duke nukem 3D.port" into the FILE_HERE folder, the game does not load. I receive an error when I try to play that there is a file missing.

An earlier post said the file name must be named and placed as such:
/Emu/PORTS/Binaries/Duke nukem 3D.port/FILE_HERE/duke3d.grp

If I copy and paste the file "Duke nukem 3D.port" into the FILE_HERE folder and change the name of the file to "duke3d.grp", the game does not load. I receive an error when I try to play that there is a file missing.

I'm confused. 

In my PORTS folder the file is called "Duke nukem 3D.port". Somebody else said it should be .grp

1. What is the exact file name supposed to be?
2. Can I take the "Duke nukem 3D.port" file, copy it, paste it into FILE_HERE and simply change the name?

Thank you.

**Comment by dwmccoy** [comment]
You would not place the Duke nukem 3D.port file into the FILE_HERE folder.  The file is an empty blank text file named Duke nukem 3D.port and it is placed into the /EMU/PORTS/PORTS folder.  If you installed the PORTS using the Onion installer, that file should already be there for you and you should not need to create it or move it.  The duke3d.grp file should be placed into the /Emu/PORTS/Binaries/Duke nukem 3D.port/FILE_HERE folder.  The names are specific and case sensitive.  Do NOT rename.

**Comment by ABoyWithoutAClue** [comment]
So I just take the duke3d.grp file and place that into the FILE_HERE. I didn't see that file. I'll do a search for it. 

Do you recall which folder the duke3d.grp file was in?

**Comment by dwmccoy** [comment]
The duke3d.grp is the actual duke nukem game file that has to be provided by you.  You place that file into the folder named FILE_HERE.  FILE_HERE is not a file, it is a folder.  It's basically a play on words meaning Place Your File(s) Here.

**Comment by ABoyWithoutAClue** [comment]
Gotcha! So I need to download duke3d.grp then place it in the folder called FILE_HERE.

One more (stupid) question, where do I download it? I'm sorry for the lack of knowledge, I'm completely new to this.

**Comment by ABoyWithoutAClue** [comment]
Thank you very much. I appreciate you.

**Comment by dwmccoy** [comment]
The game came in various versions.  If you did not buy the game you should be able to download a shareware version.  A simple internet search for Duke Nukem 3D shareware would do.

**Comment by Olywa** [comment]
@ABoyWithoutAClue Firstly, I apologise to you for hijacking your issue and causing you a notification ;)
@dwmccoy if you are on discord could you please message me related to this issue and the possibility of improving the Wiki.

Thanks :)
