### ISSUE TITLE
GBA crackling sound after latest update

### ISSUE THREAD

**Issue by MetalBert88** [jimgraygit/Onion#379]
After the 3.11.2 update I’m having audio crackling on GBA emulation. I’ve tried with a clean install but the problem still there.
The GBA emulation was fine with the previous firmware.

**Comment by Olywa** [comment]
Hi there, which Onion version did you come from?
Is it happening also on a GBA game you have not played before - I'm wondering if this could relate to your save states (and changes in the emulator core that are conflicting with previous states).
Could you try using the Profiles App in the APP section (may need to install it from The Onion Installer) to switch to the guest profile and launch one of the games you have seen audio issue with please?

**Comment by Olywa** [comment]
Thanks for confirming, it seems like something must have changed in the core between versions. I would suggest to follow these steps:

1. Load the game with the main (current) profile, let it load your save state and now play to any point where you can save 'in-game' (i.e. as you would with real hardware/cartridge, within the games own menu/save system).
2. This will create a normal game save in Saves\CurrentProfile\**saves**\gpSP
3. Now go to Saves\CurrentProfile\**states**\gpSP and rename any old **save states** for the game  to ('yourgamename').state.auto.OLD
4. Next load the game again, it should start 'fresh' at the game menu but with an option to load your save file (not state),  in-game, again as you would with real hardware.
5. Now you can make a new save state (either manually or if using the launcher just exit the game).

This assumes the game has in-game saving.

Please report back :)

**Comment by MetalBert88** [comment]
Now it works perfectly!!!
Thank you so much.

**Comment by MetalBert88** [comment]
Solved.
