### ISSUE TITLE
Unable to run Atari Lynx games

### ISSUE THREAD

**Issue by Geyb712** [jimgraygit/Onion#38]
I've noticed that Atari Lynx games are not able to run either. Entering a game brings up a screen that states "loading." After that screen, I'm booted back to the Lynx rom list.

**Comment by jimgraygit** [comment]
Lynx requires a bios file, check the wiki

**Comment by denverslair** [comment]
Even with the BIOS, files that open on Retroarch (handy) on PC aren't working for me, Goes straight back to menu.

**Comment by Sichroteph** [comment]
Can you check the information panel that the core is well in place ?

**Comment by Sichroteph** [comment]
Stock Onion 3.6, I just loaded alien VS predator fine. Either this issue is fixed by now or it is a bios issue. (I use the default miyoo bios folder that I moved to sdcard / Bios )
