### ISSUE TITLE
power off button not working

### ISSUE THREAD

**Issue by leorock07** [jimgraygit/Onion#381]
Suddenly i realized that my power button is not working anymore (inside the game or outside). My only way to shut it down is going to options and select it. The Button works fine for power on the device.

**Comment by leorock07** [comment]
Really funny, it does not seen onion related, cause the reaction is the same...nothing happens...wth, the device Just bricked?! Cause Its not hardware since It Powers on the device ...

**Comment by dwmccoy** [comment]
I would have to conclude it is indeed a probable hardware issue.  I'd consider pressing the button down for more than 30 seconds to see if it shuts off.  I'd also consider plugging in the charger while it's on and then pressing the power button to see if it shuts off.  Last thing I'd try is re-flashing the firmware.  It's definitely not an Onion OS or SDCARD issue for sure.  This issue should be closed as Onion OS is not the problem causing your trouble.
