### ISSUE TITLE
WonderSwan directory should be WS not WSC

### ISSUE THREAD

**Issue by johnwfrancis** [jimgraygit/Onion#385]
The WonderSwan emulation section in the wiki indicates the the directory name should be WSC. The correct directory name is WS.

**Comment by Olywa** [comment]
Hi there, appreciate you for reporting this. The Wiki is in the the process of being updated and I have just corrected this folder in the forthcoming version so it will be reflected soon. 

Could I ask you to set the status of the issue to Closed please. 

Many thanks.
