### ISSUE TITLE
Screen still displaying wrong aspect ratio for vertical games

### ISSUE THREAD

**Issue by MrFaust** [jimgraygit/Onion#390]
UPDATE: I learned that there is a need to go into the RA main menu, settings, video, video filter, select Vertical3x4 and then same an overrider per game or per folder if you setup a folder for vertical games only.

still happening in Onion 3.11.2 
Under the MAME 2003-Plus core, the aspect ratio is squished in both landscape and tate modes. Also FPS reports its in the high 50s but the audio is at a high pitch.
![squished_in_landscape-mame2003plus_core](https://user-images.githubusercontent.com/68164545/174311408-eb254e45-3028-4688-9d50-2071bac70f5e.jpg)
![squished_in_tate-mame2003plus_core](https://user-images.githubusercontent.com/68164545/174311415-c17b1f61-baaa-4e2a-85c5-9aea85603003.jpg)

Under the Final Burn Neo core, the aspect ratio is stretched to fill the screen in both landscape and vertical (alternative) modes. The FPS show in the low 50's and audio is slowed down as it would at that framerate.

**Comment by MrFaust** [comment]
Under the Final Burn Neo core, the aspect ratio is stretched to fill the screen in both landscape and vertical (alternative) modes. The FPS show in the low 50's and audio is slowed down as it would at that framerate
![stretched_in_landscape-fbneo_core](https://user-images.githubusercontent.com/68164545/174335655-eec76251-cdcd-45de-9415-3c4fcce14a33.jpg)
![stretched_in_vertical_alternative-fbneo_core](https://user-images.githubusercontent.com/68164545/174335657-4c6346d7-b2a4-4ab2-a8e1-386248e027f1.jpg)
.

**Comment by MrFaust** [comment]
by the way, this game is Ketsui (ket.zip)

**Comment by Olywa** [comment]
The correct steps for vertical games in Mame2003+ are:

- Menu + Select to enter Retroarch menu
- Select Video Filter: Vertical3x4.filt
- Set scaler Keep Aspect Ratio: OFF
- Save game Overrides 

It seems from your update above that you have resolved this, Could I please ask you to set the status to CLOSED.

These types of things are not issues with OnionOS (more associated with familiarity with Retroarch, which Onion is using and such things should be raised in the discussions tab please.

Many thanks.
