### ISSUE TITLE
ScummVM

### ISSUE THREAD

**Issue by TetrisSQC** [jimgraygit/Onion#40]
Maybe not directly onion related, but I am somehow unable to get scummvm running.

**Comment by Hulu2234** [comment]
Hello, I have the same problem whenever I start a game, Loading comes up and then I'm back in the menu.  Do the games have to be in a certain file format?

**Comment by TetrisSQC** [comment]
Sorry, my request was maybe a bit too short. It does work, but the .scummvm files do not load the emulated game like in other systems. It starts up scummvm, but I receive a "Error running game: Game data not found" message. After I hit ok, i can load the game by selecting it.

**Comment by denverslair** [comment]
I have a directory /ROMS/SCUMMVM/ and in that I have a directory per game, e.g. /ROMS/SCUMMVM/Loom/ and in that are all the files for that game. 
Then if I choose the ScummVM emulator, it takes me to the directory list... select the directory... and then it lists all the files and if I then select any one of the files it loads the game (a bit of weird UI, but at least it works).

**Comment by TetrisSQC** [comment]
Oh, this is embarrassing. You are absolutely right it works for almost all the scummvm files I have here too. I was just too focused on the .scummvm system from my other systems which anyhow seem to be broken in general.
