### ISSUE TITLE
Feature Request - Video previews for game list.

### ISSUE THREAD

**Issue by VonSparq** [jimgraygit/Onion#400]
I don't know if it's even possible to do it on the Mini but I didn't see an Issue about it so I thought I'd suggest it.

I would love to get a video preview for the game's list just like on 351ELEC, at first showing just a scraped image (screenshot, title, boxart etc.) and if you pause on that entry for a second or two it starts playing a short scraped gameplay video for the selected title.

Much love and huge thanks for developing this project and please add this is an amazing feature if at all possible, I would love to have it on the Mini!

**Comment by ac3nl** [comment]
There is a lot that has to be done before video preview.
Like diplaying the gamelist.xml gamedata first.
As from now, only the gamename is picked from this list
Would be nice if it would display the year, manufacturers and description too
