### ISSUE TITLE
Pole position, rad mobile  (MAME) accelerator not assigned

### ISSUE THREAD

**Issue by baritonomarchetto** [jimgraygit/Onion#403]
Hello, sorry for bothering, I have noticed that more than one racing games in MAME have the accel pedal not assigned to any button. May I ask how to assign it?

I have tried by calling the retroarch menu (middle botton + start) but I had no luck by surfing the menus...

Thanks!

**Comment by ac3nl** [comment]
You can remap mame itself:

goto mame menu
Goto options
Goto system
Enable display mame menu
Resume game -> mame menu is here now
Goto input thia game
Config paddle 1 and 2 with the buttons you prefer
Back to mame menu
Goto options
Goto system
Enable display mame menu
resume game -> mame menu is gone, buttons work

**Comment by baritonomarchetto** [comment]
Thank you very much. I am used at MAME and it's configuration, but was missing that MAME menu enable :)
