### ISSUE TITLE
Roms folders don't match Console names

### ISSUE THREAD

**Issue by zebramonkeylizard** [jimgraygit/Onion#406]
Sega Genesis: Roms folder is MD
Nintendo: Roms folder is FC
Super Nintendo: SFC

There may be more, but I have these installed.

**Comment by dwmccoy** [comment]
This is not an issue with Onion OS.  This should be closed.  Please refer to the following educational links...

Sega Genesis: Roms folder is MD -->> https://en.wikipedia.org/wiki/Sega_Genesis
Nintendo: Roms folder is FC -->> https://en.wikipedia.org/wiki/Nintendo_Entertainment_System
Super Nintendo: SFC -->> https://en.wikipedia.org/wiki/Super_Nintendo_Entertainment_System

MD = Mega Drive
FC =  Famicom
SFC = Super Famicom

**Comment by ac3nl** [comment]
> Sega Genesis: Roms folder is MD
> 
> Nintendo: Roms folder is FC
> 
> Super Nintendo: SFC
> 
> 
> 
> There may be more, but I have these installed. 
> 
> 

With a lot of editing, you can change this. These are the Default directories that Miyoo uses for the card that comes with your mini.

Start editing all the scripts in the Emu folders, if your really care about the naming. After that change the directory names. 

Please close this one

**Comment by zebramonkeylizard** [comment]
This is a missed opportunity to make the entire experience more intuitive and consistent. If the argument against updating it is that it's the Miyoo Mini default then why are there any differences between Onion OS and stock? Plus, there's the fact that EU MD games are PAL and US Genesis games are NTSC and run at different speeds and have different localisations so there's more to it than just the names.

**Comment by ac3nl** [comment]
> This is a missed opportunity to make the entire experience more intuitive and consistent. If the argument against updating it is that it's the Miyoo Mini default then why are there any differences between Onion OS and stock? Plus, there's the fact that EU MD games are PAL and US Genesis games are NTSC and run at different speeds and have different localisations so there's more to it than just the names.

And you can create different directories for all of them, by yourself
It is not that hard…

i have split msx 1 and 2, gameboy and gameboy colour, wonderswan and wonderswan colour
Really easy..
