### ISSUE TITLE
mGBA, vba_Next, and VBA-M sound issues 

### ISSUE THREAD

**Issue by samsquanch3000** [jimgraygit/Onion#411]
Get no sound with mGBA, sound lags on vba_next and VBA-M. Noticed when I edited the launch.sh file to launch mGBA in console menu. This happens in expert menu as well. mGBA works fine when selecting core through RetroArch but haven't tested vba_next and VBA-M. Hopefully this issue gets resolved since mGBA is the only core that doesn't get the “1m sub-circuit board is not installed” error when playing my favorite hacked Pokémon roms like Ultra Violet.

**Comment by dwmccoy** [comment]
Is this by chance a hacked ROM that is giving you no sound using mGBA?  I can use mGBA from the expert menu and make it the default for consoles and I have no sound issues.  The sound works as expected.

**Comment by samsquanch3000** [comment]
Tried a normal Pokémon rom and couple other roms and still getting no sound through expert menu. I'll try doing a fresh install of onion and see if the problem persist.

**Comment by samsquanch3000** [comment]
The fresh install did the job, getting sound on all my roms hacked and unhacked lol.
