### ISSUE TITLE
Duke Nukem Total Meltdown PS1 freeze

### ISSUE THREAD

**Issue by robertacurtis** [jimgraygit/Onion#413]
Duke Nukem Total Meltdown for PS1 freezes if you die, and try to restart the first level. The progress bar gets stuck at 10% and doesn’t advance.

**Comment by dwmccoy** [comment]
This is a known issue with this game.  Load the game, then open the Retroarch menu by pressing MENU+Select.  Choose Options, Choose PSX CPU Clock and change default value of 57 to 85. Go back one menu level and choose Overrides.  Choose Save Game Overrides.  Exit the Game or Retroarch and relaunch it.  Issue should be resolved.  Let us know if this fixed your issue.

**Comment by robertacurtis** [comment]
> This is a known issue with this game. Load the game, then open the Retroarch menu by pressing MENU+Select. Choose Options, Choose PSX CPU Clock and change default value of 57 to 85. Go back one menu level and choose Overrides. Choose Save Game Overrides. Exit the Game or Retroarch and relaunch it. Issue should be resolved. Let us know if this fixed your issue.

This did fix it thank you, but it only worked after restarting the device, just restarting retroarch didn’t work for some reason.

**Comment by dwmccoy** [comment]
@robertacurtis , if this fixed your issue can you please close the ticket.  Thanks for letting us know it's working for you.
