### ISSUE TITLE
Selecting Cartridge then choosing a theme as the "cartridge" causes major issues

### ISSUE THREAD

**Issue by Mips96** [jimgraygit/Onion#45]
I selected Cartridge from the apps menu, then immediately decided to swap themes instead of choosing a game. This causes a variety of issues:

First, the system thinks that changing to a new theme _is_ the cartridge, so every time I turn the system on, it re-selects the theme, which shuts the system off again without an option to remove the cartridge. I can mash buttons right after the OS boots to escape the sequence of trying to select the cartridge, but at the end of the sequence, the system continues to press the A button on its own indefinitely (once per second, maybe more). I can remove the cartridge by navigating to a game while in this state then pressing Menu, but this introduces a new issue: games no longer boot... at all. All games crash immediately upon startup, even after resetting the system.

The only way to set everything back to normal once this happens (as far as I can tell) is to go into settings and do a factory reset. I was able to recreate all this using the described order of events, so it's not a one-time fluke.

**Comment by VorgonBattlecruiser** [comment]
When the cartridge window pops up and tells you what its doing after boot, try quickly pressing the "Menu" button.

**Comment by Mips96** [comment]
> When the cartridge window pops up and tells you what its doing after boot, try quickly pressing the "Menu" button.

There’s no cartridge window, and pressing Menu during this process doesn’t remove the cartridge.

**Comment by Sichroteph** [comment]
It shoud if you press it several times at startup, the menu button is an escape key.
Onion V3 will improve a lot on this.
