### ISSUE TITLE
CPS3 launch script is non-functional

### ISSUE THREAD

**Issue by rgstoian** [jimgraygit/Onion#47]
The last line of launch.sh from the  /Emu/CPS3/ folder (the actual launch command) is commented out on the latest version of Onion:
![Code_NB73XmMjJd](https://user-images.githubusercontent.com/49798196/152329727-553cb105-543a-4cc7-b68e-0abcf4a40ef2.png)

**Comment by y-ewe** [comment]
Yeah, confirmed. Even with manual removal of the hash from line 6, I wasn't able to get the launch working. Was hoping to workaround it...

**Comment by MasterEmerald** [comment]
Easy enough - just point CPS3 at FBneo instead of FBalpha2012. See the self-resolved issue I posted and closer here.
