### ISSUE TITLE
Trouble with pokémon crystal

### ISSUE THREAD

**Issue by leorock07** [jimgraygit/Onion#48]
Hi are you my friends
When i play pok crystal/gold/silver, the system always freezes when i shutdown the device and load the game again.
Or it goes to a gray screen or freezes on the last game frame before i quit.
I thing it may be related to these games internal clock, but i'm not sure.
any solution for this?

**Comment by Sichroteph** [comment]
Sorry, we can't reproduce your issue. Can you please try with a fresh install ?
It should not be related to the internal clock.
