### ISSUE TITLE
Nxengine fails to load Cave Story

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [jimgraygit/Onion#51]
I copied over the "Cave Story" content download from my desktop-install of Retroarch to the rom-folger "NXENGINE".
Upon trying to launch "Doukutsu.exe" it attempts to start and then returns to the UI.

I tried several alternative versions of the game from various sources online, but none manage to launch.

**Comment by Sichroteph** [comment]
Hello, the expert section needs tinkering and we don't support it right now, if you find anything to make it work you can report to us thanks !

**Comment by Jimmy-Z** [comment]
This should probably be kept open for people thinking it's their problem, like me.

Or a known issues section would be nice.
