### ISSUE TITLE
Mr. Boom can't be launched since it asks for a ROM

### ISSUE THREAD

**Issue by Mips96** [jimgraygit/Onion#52]
The current config file for the Mr. Boom core asks for a ROM, but since this core is meant to be standalone, it can't be launched.

I made a new config/launch file for the Mr. Boom core based off OpenBOR, since that's an existing application that isn't launched alongside another file. Simply extract this zip into `sdcard:\RApp\mrboom` (overwrite when asked) and the core will work:

[MrBoomConfig.zip](https://github.com/jimgraygit/Onion/files/8012152/MrBoomConfig.zip)

**Comment by Sichroteph** [comment]
Thank you very much, it will be added in the next version.

**Comment by schmurtzm** [comment]
Hi, not working for me, still asking for rom... Even with the files from Mips96...
I don't understand why...
