### ISSUE TITLE
incorrect MAME2003 launch script

### ISSUE THREAD

**Issue by rgstoian** [jimgraygit/Onion#54]
.\RApp\mame2003\launch.sh, line 7:
HOME=/mnt/SDCARD/RetroArch/ $progdir/../../RetroArch/retroarch -v -L $progdir/mame2003_plus_libretro.so "$1"
mame2003_plus_libretro.so is being called instead of mame2003_libretro.so

**Comment by Sichroteph** [comment]
Thanks, it should be fixed in the next onion version
