### ISSUE TITLE
Sound crackling fix

### ISSUE THREAD

**Issue by Oddisey000** [jimgraygit/Onion#58]
Hello, recently I found that increasing:
audio_max_timing_skew to 0.130000
audio_rate_control_delta to 0.013000

Help a lot with audio crackling problem, now I have clear and nice sound.

Could you please make this settings as default value on RetroArch/retroarch.cfg
In all future Onion release?

Thanks

**Comment by Oddisey000** [comment]
Thanks for quick response.
  1.Audio crackling issue occures in:
    Playstation (most frequent on this system),
    Snes,
    Sega Genesis,
    GBA

That is all systems I checked right now.
Mostly it happens when you use PAL roms.

  2. I found solution on RetroArch forum where people 
   recommend to change audio_skew, audio_delta 
   settings. 

The exact value I found by experimenting until I don't hear any crackling in games

**Comment by Sichroteph** [comment]
Thanks, but I cannot reproduce your cracking sound issue. On GBA for
exemple can you recommend a Rom experiencing this ?

**Comment by Oddisey000** [comment]
On GBA I try "Breath Of Fire" ROM
You can hear some sound crackling when you reach "Camlon Castle" location, it's not so obvious as on other systems.

On Snes "Super Mario RPG" ROM
Has lot of crackling in first location when Mario reach the castle and start fighting some enemies.

On Playstation "Xenogears" ROM
You hear a lot of crackling after first cut scene, while you reading text intro.

**Comment by Sichroteph** [comment]
It is possible that this fix makes sound distortion too so for now we prefer not to apply it before further testings.
![Capture d’écran 2022-02-14 000638](https://user-images.githubusercontent.com/16885275/153779290-5c940464-8c8b-491d-9708-675dc13d8c6b.jpg)
In the same time you can try to add "tinymix set 6 100" in your system launch.sh file, users reports that it fixes the issue too.

**Comment by Oddisey000** [comment]
Thank you very much
