### ISSUE TITLE
RTC (Real-Time Clock) emulation

### ISSUE THREAD

**Issue by Wapp92** [jimgraygit/Onion#63]
I just can't get it to work. And i can't find a explanation anywhere.

I test 2 games Pokemon Emerald on gpSP, open RTC app open the game and no change.
Pokemon Gold on gambatte, open RTC app open the game no change and the game is broken hang. I can't make it run again, had to delete the auto save state to get into the game again. I suspect that auto save when closing the game is broken in conjunction with rtc emulation.

So How exactly is this feature use, What emulator and game are compatible? What are the step to take to make it work without breaking a game.

**Comment by Sichroteph** [comment]
from the 3.6, your internal time will be increased by 4 hours each time you restart.
