### ISSUE TITLE
Retroarch crashes when Menu+A restart is used

### ISSUE THREAD

**Issue by aaronsantiago** [jimgraygit/Onion#64]
Not much more to go on than this, unfortunately. I've been playing mainly GBA but I noticed this happening once or twice in other consoles.

**Comment by Sichroteph** [comment]
The default restart feature shortcut had been dropped. Instead, you can use the retroarch menu or do your own binning.
The retroarch binaries changed a lot since your message, I believe your stability issue had been solved.
