### ISSUE TITLE
Onion V3: Definitive Edition | PSX screen flickering, performance issue, texture glitches

### ISSUE THREAD

**Issue by dEFLASH** [jimgraygit/Onion#68]
Before updates it was ok.
Now after updates:
- screen flickering in most PSX games
- performance issue (slowing down from time to time)
- textures glitches

BIOS Used
psxonpsp660.bin

**Comment by Xtremis77** [comment]
I can confirm this issue as well at least for Tekken 3 and psxonpsp660.bin or scph101.bin.
I tried Tony Hawk 2 and the game seemed to run correctly.
However, when I try to restart any PSX game through Retroarch "restart" option, it crashes back to the main Onion menu.

**Comment by doubled1** [comment]
For a couple of games I've tested, I disabled the Normal2x video filter and everything went back to normal.

**Comment by Xtremis77** [comment]
> For a couple of games I've tested, I disabled the Normal2x video filter and everything went back to normal.

I confirm that for Tekken 3. I believe the video filter was configured in the previous version as well, but not sure.

**Comment by dEFLASH** [comment]
> > For a couple of games I've tested, I disabled the Normal2x video filter and everything went back to normal.
> 
> I confirm that for Tekken 3. I believe the video filter was configured in the previous version as well, but not sure.

Filter is set by default in new version, checked it by file-to-file compare old and v3 release.

**Comment by anibaldeboni** [comment]
I can confirm for Final Fantasy VII (game is unplayable) and Warcraft II (flickering during load screen)

**Comment by Julian-MJK** [comment]
I also have some issues with PSX, Tenchu 2 randomly jarringly skips frames. It can be recreated by just going to the very first tutorial map, turning 180 degrees, and holding UP+LEFT, so you walk in a circle that gets very close to the wall.
