### ISSUE TITLE
Onion v3.03 installer does not install any Layer1 or Layer2 items in tutorial/first boot mode 

### ISSUE THREAD

**Issue by UpdogUpdogUpdog** [jimgraygit/Onion#70]
I did the thing with deleting everything except BIOS and Roms paths, dragged the .tmp_archive over, booted up, made my selections with the installer, pressed start, watched the list of things i chose scroll by, then it booted into the Lilla theme. 

When it did, I have nothing under the consoles list, and none of the apps I chose are visible. 

Tried nuking the DB since that usually helps when I can't see what I'm expecting, but nay. 

I open the installer and everything is marked with a red X still.

**Comment by Sichroteph** [comment]
it is fixed
