### ISSUE TITLE
gambatte defaulting to brown for GB games

### ISSUE THREAD

**Issue by Furemu1** [jimgraygit/Onion#71]
GB colorization is broken

**Comment by markb44z** [comment]
When a game is loaded press Menu and Select to access Retroarch then from the Quick Menu, scroll down to Options, select ‘Internal’ for GB Colorization, then ‘GB-DMG’ for Internal Palette, then press B to return to the Quick Menu, scroll down to Overides, select ‘Select Content Directory Overides’ which will save those settings for all GB games, then press B to go to the Main Menu, select Quit Retroarch and all your GB games should now be in Gameboy Green!

**Comment by Sichroteph** [comment]
Thanks, the default preset was the wrong one. Should be fixed now.
