### ISSUE TITLE
Show controls on the Onion Launcher input screen, in case someone forgets them

### ISSUE THREAD

**Issue by Julian-MJK** [jimgraygit/Onion#72]
As the title says. If someone forgets the menu+a shortcut after using Onion Launcher _(say they're using it for the first time and have been playing the same game for a while)_, they're a little bit softlocked unless they quit manually through the retroarch shortcut, which everyone might not be familiar with. 

A simple fix for this is to just put "Press menu+a to return to Miyoo menu" or "Press menu+A to remove the cartridge" on the pre-shutdown screen.

**Comment by Julian-MJK** [comment]
After writing this, somebody on the Discord experienced what I thought was a possibility, they didn't know how to exit the Onion Launcher and thought they were soft-locked, after it tried opening an invalid "game" (a theme app).

**Comment by Sichroteph** [comment]
Done in the newest versions.
