### ISSUE TITLE
Onion Launcher behaves incorrectly if there's no game or an invalid game/app in the recent games list

### ISSUE THREAD

**Issue by Julian-MJK** [jimgraygit/Onion#73]
After upgrading I wanted to try out Onion Launcher, so launched that first, this made the shutdown-prompt start whenever I turned on my Miyoo Mini, as no game was selected.
This has happened again multiple times, I assume because the game/app I was playing had crashed, or something like that.

Adding a fallback for when the last played game/app isn't valid or isn't there at all would be nice

**Comment by Sichroteph** [comment]
Code were added to cope with this.
Also this shortcut : start+select+menu+r2+l2 force uninstall the launcher
