### ISSUE TITLE
Wonderswan Color games run poorly. choppy audio and graphical slowdown.

### ISSUE THREAD

**Issue by SnarkyJay** [jimgraygit/Onion#74]
I fired up Guilty Gear Petit after updating to the latest Onion OS (V3) and now my WSC games are choppy. This issue was not present in the updated stock OS, as I have two devices and ran them side by side. I have tested about 15 games, and they all suffer from the same issue. I am running without video filters as suggested. Issue still exists.

**Comment by Sichroteph** [comment]
It is fixed.
