### ISSUE TITLE
Unzip error due to Pok?tch theme directory name

### ISSUE THREAD

**Issue by angramainyu74** [jimgraygit/Onion#75]
Using Raspios, can't unzip without an error due the Pok?tch directory name, e.g.:

checkdir error:  cannot create _destpath_/.tmp_update/.data/Layer2/Theme Pack - Retro/App/ThemeSwitcher/Themes/Pok?tch
    invalid argument
    unable to process .tmp_update/.data/Layer2/Theme Pack - Retro/App/ThemeSwitcher/Themes/Pok?tch/.

(repeat for every file/dir in theme)

Same errors with -U option to unzip.

**Comment by hungtcs** [comment]
This issues still exist on v3.6

**Comment by Sichroteph** [comment]
Thanks, it is changed for a future release.
