### ISSUE TITLE
Pico8 doesn't recognize .png (or .p8.png) extension files

### ISSUE THREAD

**Issue by scottjl** [jimgraygit/Onion#80]
A lot of Pico-8 game 'carts' come with file names ending in .png or .p8.png, is there a way to get the emulator to recognize these extensions? Or at worst case, not filter them out in the picker list?

**Comment by CroMagas** [comment]
I just renamed them all by removing the .png and leaving it as .p8.  

An extra step but yah, would be nice to have the emulator recognize it all.

**Comment by scottjl** [comment]
yes, i can rename them, but i've got a couple hundred of 'cart' files, and some multi-cart games rely on the file being a specific name. all extensions are valid within pico-8, it's the launcher that won't recognize them. to be fair, it should.

**Comment by Sichroteph** [comment]
It is a core limitation. We will try to always push its latest updates.
