### ISSUE TITLE
No images for CPS1 or CPS2 (CPS3 is fine). Solution included.

### ISSUE THREAD

**Issue by Olywa** [jimgraygit/Onion#82]
Hi, Thank you for your great work on Onion!. CPS1 and 2 do not show screenshots in the Imgs folder. This is because the path is case sensitive and not named correctly in the config.json for both CPS1 and 2 (although is correct for CPS3).

Please can both be edited from:

"imgpath":"../../Roms/**cps1**/Imgs",

To be:

"imgpath":"../../Roms/**CPS1**/Imgs",

Thanks

**Comment by Olywa** [comment]
Still present in latest fw (v3.53 BETA).

**Comment by Sichroteph** [comment]
Thanks. It is fixed for a future release.
