### ISSUE TITLE
Ignore "._" files generated by macOS

### ISSUE THREAD

**Issue by btrsco** [jimgraygit/Onion#93]
Theres an issue with Fat32 and macOS where mac will generate files with the prefix `._` for every single file and directory, I have to manually remove these files before I eject the SD card from my Macbook. But it would be nice if theres a way the team could implement a way for Onion to ignore these files in the selection menus for games and anywhere else files are shown.

Example: `Drill Dozer (USA).zip` would show `._Drill Dozer (USA).zip` right above it in the game selection menu.

**Comment by akeigher** [comment]
I'm having this same issue with installing the various consoles as well. I end up with ._ versions of every app to install. Doesn't matter what application I use to format the SD card.

**Comment by redconedev** [comment]
Not a fix in Onion itself, but if you're comfortable doing some command line work I wrote a one-line solution into my .zshrc file that I just run on the entire drive when it's mounted that goes through and finds and cleans those up. It's just a shell command that would probably be pretty easy to implement as an app in Onion. (Wrote another to just sort my Favorites.) I'm still trying to figure out how to contribute, though.

**Comment by muzll0dr** [comment]
Not a fix in Onion itself, but if you're comfortable doing some command line work I wrote a one-line solution into my .zshrc file that I just run on the entire drive when it's mounted that goes through and finds and cleans those up. It's just a shell command that would probably be pretty easy to implement as an app in Onion. (Wrote another to just sort my Favorites.) I'm still trying to figure out how to contribute, though.

**Comment by BenKesselring** [comment]
On MacOS, you can also just run `dot_clean -m /Volumes/MIYOO` (or whatever you named the partition on your SD card).

**Comment by muzll0dr** [comment]
> On MacOS, you can also just run `dot_clean -m /Volumes/MIYOO` (or whatever you named the partition on your SD card).

This is someone who has been around MacOS longer than me. :D Great, elegant solution. Guess I can get rid of my "turdfree" alias.

**Comment by btrsco** [comment]
I have been using this, but its pretty annoying to do this every time I plugin my sd card to my MacBook. I back up my stuff often, would be nice if it was just built into the Onion OS itself to ignore files/directories prefixed with "._" when deciding to render the item in a list. `dot_clean -m` is more of a work around, not a solution.
