### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by punkonjunk** [jimgraygit/Onion#95]
By default, the bios location on the included SD card is T:\MIYOO BACKUP\RetroArch\.retroarch\system. There is no flat BIOS folder on the root. This causes your instructions to be unclear, should I leave just the retroarch bios folder and delete all other things?

**Comment by Olywa** [comment]
Onion does move the BIOS folder to the root of the SD (and configures Retroarch to point to it). I've been through the process twice myself so I'm not sure this is an issue. What was the process of upgrading to Onion that you followed (full install, not just the patch I assume)? Maybe jump on to the reddit /r/miyoomini sub and make a post so I (and others) can try to help you.
