### ISSUE TITLE
Manual Saves are not supported anymore on arcade games on 3.54?

### ISSUE THREAD

**Issue by InertiAGruik** [jimgraygit/Onion#96]
Hello, the core selected by default for arcade games on 3.54 seem to not support saving games anymore.
Is that normal?
(my old saves are loading when I enter a game, but the auto save fonction is not working anymore too, when I left a game and get back in my progression is still the old save I hade before patching to 3.54, the menu+L2 or R2 does not save or load and a message specify that the core does not support saving)
Emulation is way better for system 16 btw.

**Comment by 7zxkv** [comment]
same with auto save states for arcade core.....

**Comment by Sichroteph** [comment]
If the core does not support saving there is not much we can do.
