### ISSUE TITLE
Battery icon flicker

### ISSUE THREAD

**Issue by EdHeller** [jimgraygit/Onion#97]
Using v3.54 running any SNES or GBA game there's a battery icon in the upper right showing red and flickering... (even when the device is plugged in and fully charged) not sure if it's related to ADC or Charging state. 

Can I just turn that battery icon off somehow? Could you maybe make that a setting in an ini or something? (so I don't need to DIY a build.)

**Comment by Sichroteph** [comment]
You can use the launcher
