### ISSUE TITLE
Integer Overscale functionality missing

### ISSUE THREAD

**Issue by LukeGreatwow** [jimgraygit/Onion#98]
For Gameboy Advance games on a 4:3 screen like this, I'd like to have the ability to integer scale at 3x resolution with the left and right sides of the screen slightly trimmed, but that option seems to be missing in this retroarch build. I've tried adding it directly to the core configs, but that doesn't have an effect either.

**Comment by Sichroteph** [comment]
Thanks, we added it to our to do list.
